using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.IE;
using OpenQA.Selenium.Firefox;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;

namespace Selenium3
{
    class Agent
    {
        public static void AcceptScheduleAppointment()
        {
            // Accept Schedule Appointment - Datetime Now
            SeleniumSetMethods.Wait(ElementType.LinkText, "Tasks");
            SeleniumSetMethods.Click(ElementType.LinkText, "Tasks");
            SeleniumSetMethods.Wait(ElementType.Id, "clearButton");
            SeleniumSetMethods.Click(ElementType.Id, "clearButton");
            SeleniumSetMethods.Wait(ElementType.Id, "Address");
            SeleniumSetMethods.EnterText(ElementType.Id, "Address", Global.StreetAddress);
            int tries = 0;
            bool IsAppointmentPresent = false;
            while (IsAppointmentPresent == false)
            {
                try
                {
                    SeleniumSetMethods.Click(ElementType.Id, "searchButton1"); // refreshing results
                    tries = tries + 1;
                    Global.ConsoleOut("Attempting to Schedule Appointment: " + tries + " Attempt(s)");
                    SeleniumWindowMethods.Sleep(2);
                    SeleniumSetMethods.Click(ElementType.PartialLinkText, "Schedule Appointment (Agent)");
                    Global.ConsoleOut("Appointment Found");
                    IsAppointmentPresent = true;
                    break;
                }
                catch (Exception) { }
                if (tries == 10)
                {
                    Global.ConsoleOut("Appointment Not Found");
                    break; // handle error and break/return
                }
                SeleniumWindowMethods.Sleep(25);
                SeleniumSetMethods.Click(ElementType.LinkText, "Tasks");
                SeleniumWindowMethods.Sleep(5);
            }
            SeleniumWindowMethods.Sleep(3);
            SeleniumSetMethods.Wait(ElementType.Id, "AppointmentDate");
            SeleniumSetMethods.Click(ElementType.Id, "AppointmentDate");
            SeleniumWindowMethods.Sleep(1);
            SeleniumSetMethods.Click(ElementType.XPath, "//button[@type='button']");
            SeleniumSetMethods.Wait(ElementType.Id, "btnSubmit");
            SeleniumSetMethods.Click(ElementType.Id, "btnSubmit");
            SeleniumWindowMethods.Sleep(1);
            Global.ConsoleOut("Accepted Scheduled Appointment @: "+ DateTime.Now);
            SeleniumWindowMethods.Sleep(2);
            Global.ConsoleOut("Manually run Amp Order sync now");
        }

        public static void OpenBPO()
        {
            // Open BPO Task

            Global.ConsoleOut("Opening BPO :"+ Global.OrderID+"  @: " + DateTime.Now);
            SeleniumSetMethods.Wait(ElementType.LinkText, "Tasks");
            SeleniumSetMethods.Click(ElementType.LinkText, "Tasks");
            SeleniumSetMethods.Wait(ElementType.Id, "clearButton");
            SeleniumSetMethods.Click(ElementType.Id, "clearButton");
            SeleniumSetMethods.Wait(ElementType.Id, "Address");
            SeleniumSetMethods.EnterText(ElementType.Id, "Address", Global.StreetAddress);

            int tries = 0;
            bool IsOrderPresent = false;
            while (IsOrderPresent == false)
            {
                try
                {
                    SeleniumSetMethods.Click(ElementType.Id, "searchButton1"); // refreshing results
                    tries = tries + 1;
                    Global.ConsoleOut("Attempting to find BPO: " + tries +" Attempt(s)");
                    SeleniumWindowMethods.Sleep(2);
                    SeleniumSetMethods.Click(ElementType.LinkText, "BPO");
                    Global.ConsoleOut("BPO Found");
                    IsOrderPresent = true;
                    break;
                }
                catch (Exception) { }
                    if (tries == 15)
                    {
                        Global.ConsoleOut("BPO not found");
                        break; // handle error and break/return
                    }
                SeleniumWindowMethods.Sleep(25);
                SeleniumSetMethods.Click(ElementType.LinkText, "Tasks");
                SeleniumWindowMethods.Sleep(5);
            }
           
        }

        public static void U53Order()
        {
            // Open 5th 3rd BPO Task and Enter Data
            SeleniumWindowMethods.Sleep(10);
            SeleniumSetMethods.Wait(ElementType.CssSelector, "button.r-button.r-button-collapse-all");
            SeleniumSetMethods.Click(ElementType.CssSelector, "button.r-button.r-button-collapse-all");
            SeleniumSetMethods.Click(ElementType.CssSelector, "button.r-button.r-button-expand-all");

            // Clear maskMoney
            SeleniumSetMethods.Clear(ElementType.Id, "SalesLow");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.Clear(ElementType.Id, "SalesHigh");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.Clear(ElementType.Id, "SubjectListPrice");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.Clear(ElementType.Id, "SubjectListPast12MoOriginalListPrice");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.Clear(ElementType.Id, "HoaFee");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.Clear(ElementType.Id, "Taxes");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.Clear(ElementType.Id, "SaleComparableData_0__ListPriceAtSale");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.Clear(ElementType.Id, "SaleComparableData_1__ListPriceAtSale");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.Clear(ElementType.Id, "SaleComparableData_2__ListPriceAtSale");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.Clear(ElementType.Id, "SaleComparableData_0__OriginalListPrice");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.Clear(ElementType.Id, "SaleComparableData_1__OriginalListPrice");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.Clear(ElementType.Id, "SaleComparableData_2__OriginalListPrice");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.Clear(ElementType.Id, "SaleComparableData_0__SalePrice");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.Clear(ElementType.Id, "SaleComparableData_1__SalePrice");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.Clear(ElementType.Id, "SaleComparableData_2__SalePrice");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.Clear(ElementType.Id, "ListComparableData_0__ListPrice");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.Clear(ElementType.Id, "ListComparableData_1__ListPrice");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.Clear(ElementType.Id, "ListComparableData_2__ListPrice");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.Clear(ElementType.Id, "ListComparableData_0__OriginalListPrice");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.Clear(ElementType.Id, "ListComparableData_1__OriginalListPrice");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.Clear(ElementType.Id, "ListComparableData_2__OriginalListPrice");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.Clear(ElementType.Id, "AsIsValue");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.Clear(ElementType.Id, "AsisListPrice");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.Clear(ElementType.Id, "RepairedValue");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.Clear(ElementType.Id, "RepairedListPrice");
            SeleniumWindowMethods.ThrottlingSleep();

            // Entering input
            SeleniumSetMethods.Click(ElementType.Id, "InspectedDate");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.Click(ElementType.XPath, "(//button[@type='button'])[9]");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.SelectDropDown(ElementType.Id, "PropertyType", "Single Family");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(ElementType.Id, "ParcelNumber", "5565112");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(ElementType.Id, "BpoBrokerLicenseNumber", "64655513");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.Click(ElementType.Id, "MarketConditions");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.SelectDropDown(ElementType.Id, "MarketConditions", "Increasing");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.Click(ElementType.CssSelector, "option[value=\"Increasing\"]");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.SelectDropDown(ElementType.Id, "EmploymentConditions", "Improving");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(ElementType.Id, "SalesLow", "450000");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.Click(ElementType.Id, "SalesLow");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(ElementType.Id, "SalesHigh", "675000");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.Click(ElementType.Id, "SalesHigh");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(ElementType.Id, "MarketingDays", "15");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.Click(ElementType.Id, "IsSubjectListed");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.SelectDropDown(ElementType.Id, "IsSubjectListed", "Yes");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.Click(ElementType.CssSelector, "option[value=\"True\"]");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(ElementType.Id, "SubjectListPrice", "500500");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.Click(ElementType.Id, "SubjectListPrice");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.Click(ElementType.Id, "SubjectListDate");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.Click(ElementType.LinkText, "1");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(ElementType.Id, "SubjectDom", "20");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(ElementType.Id, "ListingBrokerName", "Agent");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.SelectDropDown(ElementType.Id, "IsSubjectListedPast12Mo", "Yes");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(ElementType.Id, "SubjectListPast12MoOriginalListPrice", "500011");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.Click(ElementType.Id, "SubjectListPast12MoOriginalListDate");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.Click(ElementType.LinkText, "1");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(ElementType.Id, "TotalDOM", "10");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.Click(ElementType.Id, "MandatoryAssociation");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.SelectDropDown(ElementType.Id, "MandatoryAssociation", "Yes");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.Click(ElementType.CssSelector, "#MandatoryAssociation > option[value=\"True\"]");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(ElementType.Id, "HoaFee", "350");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.Click(ElementType.Id, "HoaBillingCycle");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.SelectDropDown(ElementType.Id, "HoaBillingCycle", "Monthly");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.Click(ElementType.CssSelector, "option[value=\"monthly\"]");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(ElementType.Id, "HoaCompany", "Irvine Company");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(ElementType.Id, "HoaPhone", "(949) 555-3456");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.SelectDropDown(ElementType.Id, "SubjectOccupancyStatus", "Occupied");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.SelectDropDown(ElementType.Id, "Condition", "Excellent");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.SelectDropDown(ElementType.Id, "LocationType", "Suburban");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.SelectDropDown(ElementType.Id, "MarketPriceStability", "Increased");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(ElementType.Id, "MarketPriceStabilityPercent", "10");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(ElementType.Id, "Taxes", "10000");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(ElementType.Id, "PropertyComments", "I really like this property.  It's so beautiful");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(ElementType.Id, "ListingComments", "Listing Comments about listing things");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(ElementType.Id, "LocationFactors", "Good For Solar");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(ElementType.Id, "HighTensionWires", "I would try to walk them");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(ElementType.Id, "Boardups", "none here");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(ElementType.Id, "CommercialUses", "probably not ideal");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(ElementType.Id, "FreewayHighway", "Near by");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(ElementType.Id, "RRTracks", "can not hear the train");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(ElementType.Id, "AirPortFlightpath", "can not see or hear airplanes");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(ElementType.Id, "WaisteFacilities", "near by");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(ElementType.Id, "FloodPlain", "does not apply");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(ElementType.Id, "NeighDetailsAddnlComments", "would buy in a heart beat");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.Click(ElementType.Id, "AsIsOrRepaired");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.SelectDropDown(ElementType.Id, "AsIsOrRepaired", "As Is");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.Click(ElementType.CssSelector, "#AsIsOrRepaired > option[value=\"True\"]");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(ElementType.Id, "ReviewersComment", "Turn Key, Move in Ready");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(ElementType.Id, "SaleComparableData_0__StreetAddress", "101 Rose Arch");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(ElementType.Id, "SaleComparableData_1__StreetAddress", "102 Rose Arch");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(ElementType.Id, "SaleComparableData_2__StreetAddress", "103 Rose Arch");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(ElementType.Id, "SaleComparableData_0__City", "Irvine");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(ElementType.Id, "SaleComparableData_1__City", "Irvine");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(ElementType.Id, "SaleComparableData_2__City", "Irvine");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.SelectDropDown(ElementType.Id, "SaleComparableData_0__State", "California");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.SelectDropDown(ElementType.Id, "SaleComparableData_1__State", "California");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.SelectDropDown(ElementType.Id, "SaleComparableData_2__State", "California");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(ElementType.Id, "SaleComparableData_0__PostalCode", "92620");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(ElementType.Id, "SaleComparableData_1__PostalCode", "92620");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(ElementType.Id, "SaleComparableData_2__PostalCode", "92620");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(ElementType.Id, "SaleComparableData_0__ProximityDistance", "1");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(ElementType.Id, "SaleComparableData_1__ProximityDistance", "1");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(ElementType.Id, "SaleComparableData_2__ProximityDistance", "1");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.SelectDropDown(ElementType.Id, "SaleComparableData_0__SaleType", "Fair Market Value");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.SelectDropDown(ElementType.Id, "SaleComparableData_1__SaleType", "Fair Market Value");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.SelectDropDown(ElementType.Id, "SaleComparableData_2__SaleType", "Fair Market Value");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(ElementType.Id, "SaleComparableData_0__ListPriceAtSale", "500000");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.Click(ElementType.Id, "SaleComparableData_0__ListPriceAtSale");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(ElementType.Id, "SaleComparableData_1__ListPriceAtSale", "500001");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.Click(ElementType.Id, "SaleComparableData_1__ListPriceAtSale");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(ElementType.Id, "SaleComparableData_2__ListPriceAtSale", "500002");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.Click(ElementType.Id, "SaleComparableData_2__ListPriceAtSale");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(ElementType.Id, "SaleComparableData_0__OriginalListPrice", "500100");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.Click(ElementType.Id, "SaleComparableData_0__OriginalListPrice");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(ElementType.Id, "SaleComparableData_1__OriginalListPrice", "500101");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.Click(ElementType.Id, "SaleComparableData_1__OriginalListPrice");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(ElementType.Id, "SaleComparableData_2__OriginalListPrice", "500102");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.Click(ElementType.Id, "SaleComparableData_2__OriginalListPrice");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(ElementType.Id, "SaleComparableData_0__Dom", "31");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(ElementType.Id, "SaleComparableData_1__Dom", "32");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(ElementType.Id, "SaleComparableData_2__Dom", "33");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.SelectDropDown(ElementType.Id, "DataSource", "MLS");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.SelectDropDown(ElementType.Id, "SaleComparableData_0__DataSource", "MLS");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.SelectDropDown(ElementType.Id, "SaleComparableData_1__DataSource", "MLS");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.SelectDropDown(ElementType.Id, "SaleComparableData_2__DataSource", "MLS");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(ElementType.Id, "SaleComparableData_0__SalePrice", "500006");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.Click(ElementType.Id, "SaleComparableData_0__SalePrice");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(ElementType.Id, "SaleComparableData_1__SalePrice", "500007");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.Click(ElementType.Id, "SaleComparableData_1__SalePrice");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(ElementType.Id, "SaleComparableData_2__SalePrice", "500010");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.Click(ElementType.Id, "SaleComparableData_2__SalePrice");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.Click(ElementType.Id, "SaleComparableData_0__SaleDate");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.Click(ElementType.LinkText, "1");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.Click(ElementType.Id, "SaleComparableData_1__SaleDate");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.Click(ElementType.LinkText, "1");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.Click(ElementType.Id, "SaleComparableData_2__SaleDate");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.Click(ElementType.LinkText, "1");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(ElementType.Id, "SaleComparableData_0__PropertySoldDom", "30");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(ElementType.Id, "SaleComparableData_1__PropertySoldDom", "30");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(ElementType.Id, "SaleComparableData_2__PropertySoldDom", "30");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.SelectDropDown(ElementType.Id, "SaleComparableData_0__PropertyType", "Single Family");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.SelectDropDown(ElementType.Id, "SaleComparableData_1__PropertyType", "Single Family");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.SelectDropDown(ElementType.Id, "SaleComparableData_2__PropertyType", "Single Family");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.SelectDropDown(ElementType.Id, "Style", "2 Story");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.SelectDropDown(ElementType.Id, "SaleComparableData_0__Style", "2 Story");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.SelectDropDown(ElementType.Id, "SaleComparableData_1__Style", "2 Story");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.SelectDropDown(ElementType.Id, "SaleComparableData_2__Style", "2 Story");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.SelectDropDown(ElementType.Id, "SaleComparableData_0__LocationType", "Suburban");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.SelectDropDown(ElementType.Id, "SaleComparableData_1__LocationType", "Suburban");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.SelectDropDown(ElementType.Id, "SaleComparableData_2__LocationType", "Suburban");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.SelectDropDown(ElementType.Id, "LotSizeUnitType", "Sq. Ft.");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(ElementType.Id, "LotSize", "4000");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(ElementType.Id, "SaleComparableData_0__LotSize", "4250");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(ElementType.Id, "SaleComparableData_1__LotSize", "4000");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(ElementType.Id, "SaleComparableData_2__LotSize", "4500");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(ElementType.Id, "SubjectPropertyUnits", "1");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(ElementType.Id, "SaleComparableData_0__Units", "1");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(ElementType.Id, "SaleComparableData_1__Units", "1");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(ElementType.Id, "SaleComparableData_2__Units", "1");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(ElementType.Id, "YearBuilt", "2014");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(ElementType.Id, "SaleComparableData_0__YearBuilt", "2014");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(ElementType.Id, "SaleComparableData_1__YearBuilt", "2014");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(ElementType.Id, "SaleComparableData_2__YearBuilt", "2014");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.SelectDropDown(ElementType.Id, "SaleComparableData_0__Condition", "Good");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.SelectDropDown(ElementType.Id, "SaleComparableData_1__Condition", "Good");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.SelectDropDown(ElementType.Id, "SaleComparableData_2__Condition", "Good");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(ElementType.Id, "Rooms", "3");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(ElementType.Id, "SaleComparableData_0__Rooms", "3");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(ElementType.Id, "SaleComparableData_1__Rooms", "3");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(ElementType.Id, "SaleComparableData_2__Rooms", "3");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(ElementType.Id, "Beds", "3");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(ElementType.Id, "SaleComparableData_0__Beds", "3");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(ElementType.Id, "SaleComparableData_1__Beds", "3");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(ElementType.Id, "SaleComparableData_2__Beds", "3");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(ElementType.Id, "Baths", "3");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(ElementType.Id, "SaleComparableData_0__Baths", "3");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(ElementType.Id, "SaleComparableData_1__Baths", "3");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(ElementType.Id, "SaleComparableData_2__Baths", "3");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(ElementType.Id, "GrossLivingArea", "2000");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(ElementType.Id, "SaleComparableData_0__GrossLivingArea", "2000");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(ElementType.Id, "SaleComparableData_1__GrossLivingArea", "2000");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(ElementType.Id, "SaleComparableData_2__GrossLivingArea", "2000");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(ElementType.Id, "Bsmt", "0");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(ElementType.Id, "SaleComparableData_0__Bsmt", "0");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(ElementType.Id, "SaleComparableData_1__Bsmt", "0");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(ElementType.Id, "SaleComparableData_2__Bsmt", "0");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.SelectDropDown(ElementType.Id, "ConstructionType", "Brick");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.SelectDropDown(ElementType.Id, "SaleComparableData_0__ConstructionType", "Brick");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.SelectDropDown(ElementType.Id, "SaleComparableData_1__ConstructionType", "Brick");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.SelectDropDown(ElementType.Id, "SaleComparableData_2__ConstructionType", "Brick");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.SelectDropDown(ElementType.Id, "GarageType", "Attached");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.Click(ElementType.Id, "SaleComparableData_0__GarageType");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.SelectDropDown(ElementType.Id, "SaleComparableData_0__GarageType", "Attached");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.SelectDropDown(ElementType.Id, "SaleComparableData_1__GarageType", "Attached");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.SelectDropDown(ElementType.Id, "SaleComparableData_2__GarageType", "Attached");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(ElementType.Id, "GarageCount", "2");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(ElementType.Id, "SaleComparableData_0__GarageCount", "2");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(ElementType.Id, "SaleComparableData_1__GarageCount", "2");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(ElementType.Id, "SaleComparableData_2__GarageCount", "2");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(ElementType.Id, "PoolSpa", "1");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(ElementType.Id, "SaleComparableData_0__PoolSpa", "1");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(ElementType.Id, "SaleComparableData_1__PoolSpa", "1");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(ElementType.Id, "SaleComparableData_2__PoolSpa", "1");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(ElementType.Id, "FunctionalUtility", "1");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(ElementType.Id, "SaleComparableData_0__FunctionalUtility", "1");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(ElementType.Id, "SaleComparableData_1__FunctionalUtility", "1");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(ElementType.Id, "SaleComparableData_2__FunctionalUtility", "1");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.SelectDropDown(ElementType.Id, "SaleComparableData_0__Comparability", "Equal");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.SelectDropDown(ElementType.Id, "SaleComparableData_1__Comparability", "Equal");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.SelectDropDown(ElementType.Id, "SaleComparableData_2__Comparability", "Equal");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(ElementType.Id, "CheckListSales1Comments", "Testing 12345");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(ElementType.Id, "CheckListSales2Comments", "Testing 67890");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(ElementType.Id, "CheckListSales3Comments", "Testing 101112");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(ElementType.Id, "ListComparableData_0__StreetAddress", "101 Rush Lily");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(ElementType.Id, "ListComparableData_1__StreetAddress", "102 Rush Lily");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(ElementType.Id, "ListComparableData_2__StreetAddress", "103 Rush Lily");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(ElementType.Id, "ListComparableData_0__City", "Irvine");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(ElementType.Id, "ListComparableData_1__City", "Irvine");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(ElementType.Id, "ListComparableData_2__City", "Irvine");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.SelectDropDown(ElementType.Id, "ListComparableData_0__State", "California");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.SelectDropDown(ElementType.Id, "ListComparableData_1__State", "California");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.SelectDropDown(ElementType.Id, "ListComparableData_2__State", "California");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(ElementType.Id, "ListComparableData_0__PostalCode", "92620");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(ElementType.Id, "ListComparableData_1__PostalCode", "92620");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(ElementType.Id, "ListComparableData_2__PostalCode", "92620");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(ElementType.Id, "ListComparableData_0__ProximityDistance", "1");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(ElementType.Id, "ListComparableData_1__ProximityDistance", "1");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(ElementType.Id, "ListComparableData_2__ProximityDistance", "1");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.SelectDropDown(ElementType.Id, "L1SaleType_LookupId", "Fair Market Value");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.SelectDropDown(ElementType.Id, "L2SaleType_LookupId", "Fair Market Value");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.SelectDropDown(ElementType.Id, "L3SaleType_LookupId", "Fair Market Value");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(ElementType.Id, "ListComparableData_0__ListPrice", "510001");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.Click(ElementType.Id, "ListComparableData_0__ListPrice");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(ElementType.Id, "ListComparableData_1__ListPrice", "510002");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.Click(ElementType.Id, "ListComparableData_1__ListPrice");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(ElementType.Id, "ListComparableData_2__ListPrice", "510003");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.Click(ElementType.Id, "ListComparableData_2__ListPrice");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(ElementType.Id, "ListComparableData_0__OriginalListPrice", "510004");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.Click(ElementType.Id, "ListComparableData_0__OriginalListPrice");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(ElementType.Id, "ListComparableData_1__OriginalListPrice", "510005");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.Click(ElementType.Id, "ListComparableData_1__OriginalListPrice");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(ElementType.Id, "ListComparableData_2__OriginalListPrice", "510006");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.Click(ElementType.Id, "ListComparableData_2__OriginalListPrice");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(ElementType.Id, "ListComparableData_0__Dom", "30");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(ElementType.Id, "ListComparableData_1__Dom", "45");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(ElementType.Id, "ListComparableData_2__Dom", "30");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.SelectDropDown(ElementType.XPath, "(//select[@id='DataSource'])[2]", "MLS");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.SelectDropDown(ElementType.Id, "ListComparableData_0__DataSource", "MLS");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.SelectDropDown(ElementType.Id, "ListComparableData_1__DataSource", "MLS");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.SelectDropDown(ElementType.Id, "ListComparableData_2__DataSource", "MLS");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(ElementType.Id, "ListComparableData_0__CurrentListPriceDom", "30");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(ElementType.Id, "ListComparableData_1__CurrentListPriceDom", "31");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(ElementType.Id, "ListComparableData_2__CurrentListPriceDom", "32");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.SelectDropDown(ElementType.Id, "ListComparableData_0__PropertyType", "Single Family");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.SelectDropDown(ElementType.Id, "ListComparableData_1__PropertyType", "Single Family");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.SelectDropDown(ElementType.Id, "ListComparableData_2__PropertyType", "Single Family");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.SelectDropDown(ElementType.XPath, "(//select[@id='Style'])[2]", "2 Story");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.SelectDropDown(ElementType.Id, "ListComparableData_0__Style", "2 Story");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.SelectDropDown(ElementType.Id, "ListComparableData_1__Style", "2 Story");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.SelectDropDown(ElementType.Id, "ListComparableData_2__Style", "2 Story");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.SelectDropDown(ElementType.Id, "ListComparableData_0__LocationType", "Suburban");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.SelectDropDown(ElementType.Id, "ListComparableData_1__LocationType", "Suburban");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.SelectDropDown(ElementType.Id, "ListComparableData_2__LocationType", "Suburban");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.SelectDropDown(ElementType.XPath, "(//select[@id='LotSizeUnitType'])[2]", "Sq. Ft.");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(ElementType.Id, "ListComparableData_0__LotSize", "4000");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(ElementType.Id, "ListComparableData_1__LotSize", "4250");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(ElementType.Id, "ListComparableData_2__LotSize", "4000");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(ElementType.XPath, "(//input[@id='SubjectPropertyUnits'])[2]", "1");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.Click(ElementType.Id, "ListComparableData_0__Units");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(ElementType.Id, "ListComparableData_0__Units", "1");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.Click(ElementType.Id, "ListComparableData_1__Units");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(ElementType.Id, "ListComparableData_1__Units", "1");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.Click(ElementType.Id, "ListComparableData_2__Units");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(ElementType.Id, "ListComparableData_2__Units", "1");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(ElementType.XPath, "(//input[@id='YearBuilt'])[2]", "2014");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.Click(ElementType.Id, "ListComparableData_0__YearBuilt");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(ElementType.Id, "ListComparableData_0__YearBuilt", "2014");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.Click(ElementType.Id, "ListComparableData_1__YearBuilt");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(ElementType.Id, "ListComparableData_1__YearBuilt", "2014");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.Click(ElementType.Id, "ListComparableData_2__YearBuilt");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(ElementType.Id, "ListComparableData_2__YearBuilt", "2014");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.SelectDropDown(ElementType.Id, "ListComparableData_0__Condition", "Good");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.SelectDropDown(ElementType.Id, "ListComparableData_1__Condition", "Good");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.SelectDropDown(ElementType.Id, "ListComparableData_2__Condition", "Good");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(ElementType.XPath, "(//input[@id='Rooms'])[2]", "3");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(ElementType.Id, "ListComparableData_0__Rooms", "3");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(ElementType.Id, "ListComparableData_1__Rooms", "3");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(ElementType.Id, "ListComparableData_2__Rooms", "3");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(ElementType.XPath, "(//input[@id='Beds'])[2]", "3");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(ElementType.Id, "ListComparableData_0__Beds", "3");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(ElementType.Id, "ListComparableData_1__Beds", "3");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(ElementType.Id, "ListComparableData_2__Beds", "3");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(ElementType.XPath, "(//input[@id='Baths'])[2]", "3");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(ElementType.Id, "ListComparableData_0__Baths", "3");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(ElementType.Id, "ListComparableData_1__Baths", "3");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(ElementType.Id, "ListComparableData_2__Baths", "3");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(ElementType.XPath, "(//input[@id='GrossLivingArea'])[2]", "1999");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(ElementType.Id, "ListComparableData_0__GrossLivingArea", "2000");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(ElementType.Id, "ListComparableData_1__GrossLivingArea", "2000");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(ElementType.Id, "ListComparableData_2__GrossLivingArea", "2000");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(ElementType.XPath, "(//input[@id='Bsmt'])[2]", "0");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(ElementType.Id, "ListComparableData_0__Bsmt", "0");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(ElementType.Id, "ListComparableData_1__Bsmt", "0");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(ElementType.Id, "ListComparableData_2__Bsmt", "0");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.SelectDropDown(ElementType.XPath, "(//select[@id='ConstructionType'])[2]", "Brick");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.SelectDropDown(ElementType.Id, "ListComparableData_0__ConstructionType", "Brick");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.SelectDropDown(ElementType.Id, "ListComparableData_1__ConstructionType", "Brick");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.SelectDropDown(ElementType.Id, "ListComparableData_2__ConstructionType", "Brick");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.SelectDropDown(ElementType.XPath, "(//select[@id='GarageType'])[2]", "Attached");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.SelectDropDown(ElementType.Id, "ListComparableData_0__GarageType", "Attached");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.SelectDropDown(ElementType.Id, "ListComparableData_1__GarageType", "Attached");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.SelectDropDown(ElementType.Id, "ListComparableData_2__GarageType", "Attached");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(ElementType.XPath, "(//input[@id='GarageCount'])[2]", "2");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(ElementType.Id, "ListComparableData_0__GarageCount", "2");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(ElementType.Id, "ListComparableData_1__GarageCount", "2");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(ElementType.Id, "ListComparableData_2__GarageCount", "2");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(ElementType.XPath, "(//input[@id='PoolSpa'])[2]", "1");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(ElementType.Id, "ListComparableData_0__PoolSpa", "1");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(ElementType.Id, "ListComparableData_1__PoolSpa", "1");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(ElementType.Id, "ListComparableData_2__PoolSpa", "1");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(ElementType.XPath, "(//input[@id='FunctionalUtility'])[2]", "1");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(ElementType.Id, "ListComparableData_0__FunctionalUtility", "1");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(ElementType.Id, "ListComparableData_1__FunctionalUtility", "1");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(ElementType.Id, "ListComparableData_2__FunctionalUtility", "1");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.SelectDropDown(ElementType.Id, "ListComparableData_0__Comparability", "Superior");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.SelectDropDown(ElementType.Id, "ListComparableData_1__Comparability", "Superior");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.SelectDropDown(ElementType.Id, "ListComparableData_2__Comparability", "Superior");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(ElementType.Id, "CheckListSubjectComments", "Testing again 123");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(ElementType.Id, "CheckListListing1Comments", "Testing again 234");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(ElementType.Id, "CheckListListing2Comments", "Testing again 567");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(ElementType.Id, "CheckListListing3Comments", "Testing again 789");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(ElementType.Id, "AsIsValue", "500007");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.Click(ElementType.Id, "AsIsValue");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(ElementType.Id, "RepairedValue", "550000");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.Click(ElementType.Id, "RepairedValue");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(ElementType.Id, "AsisListPrice", "500001");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.Click(ElementType.Id, "AsisListPrice");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(ElementType.Id, "RepairedListPrice", "500002");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.Click(ElementType.Id, "RepairedListPrice");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.SelectDropDown(ElementType.Id, "CheckList01", "Yes");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.SelectDropDown(ElementType.Id, "CheckList02", "No");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.SelectDropDown(ElementType.Id, "CheckList03", "No");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.SelectDropDown(ElementType.Id, "CheckList04", "No");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.SelectDropDown(ElementType.Id, "CheckList05", "No");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.SelectDropDown(ElementType.Id, "DecliningValues", "No");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(ElementType.Id, "CheckListComments", "Check List Comments 132456");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(ElementType.Id, "ProviderComments", "hello it's me");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.Wait(ElementType.CssSelector, "button.r-button.r-button-collapse-all");
            SeleniumSetMethods.Click(ElementType.CssSelector, "button.r-button.r-button-collapse-all");

            Global.ConsoleOut("Coffee Break Started at for 60 seconds " + DateTime.Now);
            SeleniumWindowMethods.Sleep(60);
        }

        public static void U53ExteriorAttachments()
        {
            SeleniumSetMethods.Wait(ElementType.CssSelector, "button.r-button.r-button-expand-all");
            SeleniumSetMethods.Click(ElementType.CssSelector, "button.r-button.r-button-expand-all");
            // Add Exterior Attachments to U53 Order
            Global.ConsoleOut("Begin adding images at " + DateTime.Now);
            SeleniumSetMethods.Clear(ElementType.Id, "63_1_fileupload");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(ElementType.Id, "63_1_fileupload","\\\\hqfs1\\Public\\IT\\QA\\Pictures\\C1.jpg");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.Clear(ElementType.Id, "65_1_fileupload");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(ElementType.Id, "65_1_fileupload", "\\\\hqfs1\\Public\\IT\\QA\\Pictures\\C2.jpg");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.Clear(ElementType.Id, "66_1_fileupload");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(ElementType.Id, "66_1_fileupload", "\\\\hqfs1\\Public\\IT\\QA\\Pictures\\C3.jpg");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.Clear(ElementType.Id, "70_1_fileupload");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(ElementType.Id, "70_1_fileupload", "\\\\hqfs1\\Public\\IT\\QA\\Pictures\\C4.jpg");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.Clear(ElementType.Id, "71_1_fileupload");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(ElementType.Id, "71_1_fileupload", "\\\\hqfs1\\Public\\IT\\QA\\Pictures\\C5.jpg");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.Clear(ElementType.Id, "72_1_fileupload");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(ElementType.Id, "72_1_fileupload", "\\\\hqfs1\\Public\\IT\\QA\\Pictures\\C6.jpg");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.Clear(ElementType.Id, "73_1_fileupload");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(ElementType.Id, "73_1_fileupload", "\\\\hqfs1\\Public\\IT\\QA\\Pictures\\C7.jpg");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.Clear(ElementType.Id, "74_1_fileupload");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(ElementType.Id, "74_1_fileupload", "\\\\hqfs1\\Public\\IT\\QA\\Pictures\\C8.jpg");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.Clear(ElementType.Id, "75_1_fileupload");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(ElementType.Id, "75_1_fileupload", "\\\\hqfs1\\Public\\IT\\QA\\Pictures\\C9.jpg");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.Clear(ElementType.Id, "16_fileupload");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(ElementType.Id, "16_fileupload", "\\\\hqfs1\\Public\\IT\\QA\\Pictures\\AUpload.pdf");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.Clear(ElementType.Id, "27_fileupload");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(ElementType.Id, "27_fileupload", "\\\\hqfs1\\Public\\IT\\QA\\Pictures\\AUpload.pdf");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.Clear(ElementType.Id, "productUpload_230_fileupload");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(ElementType.Id, "productUpload_230_fileupload", "\\\\hqfs1\\Public\\IT\\QA\\Pictures\\AUpload.pdf");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.WaitMinutes(ElementType.CssSelector, ".r-footer > div:nth-child(1) > div:nth-child(1) > button:nth-child(3)", 5);
            SeleniumWindowMethods.ThrottlingSleep();
            Global.ConsoleOut("Start praying for the next 30 seconds, beginning at  " + DateTime.Now);
            SeleniumWindowMethods.Sleep(30);
            SeleniumSetMethods.Click(ElementType.CssSelector, ".r-footer > div:nth-child(1) > div:nth-child(1) > button:nth-child(3)");
            Global.ConsoleOut("Submit button Clicked " + DateTime.Now);
            SeleniumWindowMethods.WindowType(WinType.Popup);
            SeleniumSetMethods.Click(ElementType.XPath, "(//button[@type='button'])[10]");
            SeleniumWindowMethods.WindowType(WinType.Main);
            SeleniumWindowMethods.Sleep(3);
            SeleniumSetMethods.Click(ElementType.Id, "ctl00_ctl00_ctrHeader_LoginState1_hlLogout");

        }


    }


}
