using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.IE;
using OpenQA.Selenium.Firefox;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;

namespace Selenium3
{
    class AutoFill
    {
        public static void REOPNMAC()
        {
            //REO PNMAC BPO 
            SeleniumWindowMethods.Sleep(2);
            Global.ConsoleOut("Pause Me");
            SeleniumWindowMethods.Sleep(5);
            SeleniumSetMethods.EnterText(ElementType.Id, "subApn", "123-22");
            SeleniumSetMethods.EnterText(ElementType.Id, "subOrderNo", "123");
            SeleniumSetMethods.EnterText(ElementType.Id, "subOrderType", "BPO");
            SeleniumSetMethods.EnterText(ElementType.Id, "subVendorOrderNo", "vorder#132");
            SeleniumSetMethods.EnterText(ElementType.Id, "subBorrower", "Qa test");
            SeleniumSetMethods.EnterText(ElementType.Id, "subOwner", "owner of public");
            SeleniumSetMethods.EnterText(ElementType.Id, "subCounty", "orange");
            SeleniumSetMethods.Click(ElementType.Id, "subPropTypeSFR");
            SeleniumSetMethods.EnterText(ElementType.Id, "subHoa", "180");
            SeleniumSetMethods.Click(ElementType.Id, "subUCNo");
            SeleniumSetMethods.Click(ElementType.Id, "subDisNo");
            SeleniumSetMethods.Click(ElementType.Id, "subDisYes");
            SeleniumSetMethods.EnterText(ElementType.Id, "subDisDescr", "04/15/2015");
            SeleniumSetMethods.Click(ElementType.Id, "subListedYes");
            SeleniumSetMethods.Click(ElementType.XPath, "//table[@id='tabBorder1']/tbody/tr/td/div[3]/div[19]/div[2]/label");
            SeleniumSetMethods.EnterText(ElementType.Id, "subDOM", "35");
            SeleniumSetMethods.Click(ElementType.Id, "subSoldYes");
            SeleniumSetMethods.EnterText(ElementType.Id, "subSP", "575000");
            SeleniumSetMethods.EnterText(ElementType.Id, "subSPDt", "09/10/2015");
            SeleniumSetMethods.EnterText(ElementType.Id, "subOLP", "580000");
            SeleniumSetMethods.EnterText(ElementType.Id, "subOLPDt", "08/11/2015");
            SeleniumSetMethods.EnterText(ElementType.Id, "subLLP", "579000");
            SeleniumSetMethods.EnterText(ElementType.Id, "subLLPDt", "09/01/2016");
            SeleniumSetMethods.Click(ElementType.Id, "subOccupancyOwner");
            SeleniumSetMethods.Click(ElementType.XPath, "//table[@id='tabBorder1']/tbody/tr/td/div[3]/div[25]/div[2]/label");
            SeleniumSetMethods.Click(ElementType.Id, "subInspectExterior");
            SeleniumSetMethods.EnterText(ElementType.Id, "subInspectDt", "07/25/2016");
            SeleniumSetMethods.Click(ElementType.Id, "subSecureYes");
            SeleniumSetMethods.Click(ElementType.XPath, "//table[@id='tabBorder1']/tbody/tr/td/div[3]/div[27]/div[2]/label");
            SeleniumSetMethods.EnterText(ElementType.Id, "subZoning", "Zoning");
            SeleniumSetMethods.EnterText(ElementType.Id, "subZoningSrce", "Zone Datas source");
            SeleniumSetMethods.EnterText(ElementType.Id, "subUseCur", "current");
            SeleniumSetMethods.EnterText(ElementType.Id, "subUseProj", "projected use");
            SeleniumSetMethods.EnterText(ElementType.Name, "txtSubNotes", "Test subject property comments:");
            SeleniumSetMethods.Click(ElementType.Id, "hoodLocSuburban");
            SeleniumSetMethods.Click(ElementType.Id, "hoodValuesStable");
            SeleniumSetMethods.EnterText(ElementType.Id, "hoodDOM", "45");
            SeleniumSetMethods.EnterText(ElementType.Id, "hoodRent", "1800");
            SeleniumSetMethods.SelectDropDown(ElementType.Name, "hoodReoTrend", "Stable");
            SeleniumSetMethods.SelectDropDown(ElementType.Name, "hoodTrend", "Increasing");
            SeleniumSetMethods.Click(ElementType.Id, "hoodOccOwner");
            SeleniumSetMethods.Click(ElementType.Id, "hoodIndusYes");
            SeleniumSetMethods.Click(ElementType.Id, "hoodVacancy20");
            SeleniumSetMethods.Click(ElementType.Id, "hoodNewConstructYes");
            SeleniumSetMethods.Click(ElementType.Id, "hoodDisYes");
            SeleniumSetMethods.EnterText(ElementType.Id, "hoodDisDt", "04/20/2015");
            SeleniumSetMethods.EnterText(ElementType.Id, "hoodListings", "5");
            SeleniumSetMethods.EnterText(ElementType.Id, "hoodLpTo", "370,000");
            SeleniumSetMethods.EnterText(ElementType.Id, "hoodLpFrom", "425,000");
            SeleniumSetMethods.EnterText(ElementType.Id, "hoodSales", "3");
            SeleniumSetMethods.EnterText(ElementType.Id, "hoodSpTo", "380,000");
            SeleniumSetMethods.EnterText(ElementType.Id, "hoodSpFrom", "430,000");
            SeleniumSetMethods.EnterText(ElementType.Name, "txtHoodDescr", "neighborhood description");
            SeleniumSetMethods.EnterText(ElementType.Name, "txtHoodMktCondition", "market condition :");
            SeleniumSetMethods.Click(ElementType.Id, "rfDamaged");
            SeleniumSetMethods.Click(ElementType.Id, "rfEnvironmental");
            SeleniumSetMethods.Click(ElementType.Id, "rfZoning");
            SeleniumSetMethods.Click(ElementType.Id, "rfMktActivity");
            SeleniumSetMethods.Click(ElementType.Id, "rfOther");
            SeleniumSetMethods.EnterText(ElementType.Name, "txtRfNotes", "Red flag comments:");
            SeleniumSetMethods.EnterText(ElementType.Id, "repName1", "repair1");
            SeleniumSetMethods.Click(ElementType.Id, "repIE1I");
            SeleniumSetMethods.EnterText(ElementType.Id, "repCost1", "180");
            SeleniumSetMethods.EnterText(ElementType.Id, "repName2", "rapair2");
            SeleniumSetMethods.EnterText(ElementType.Id, "repName3", "repair3");
            SeleniumSetMethods.Click(ElementType.Id, "repIE2E");
            SeleniumSetMethods.Click(ElementType.Id, "repIE3I");
            SeleniumSetMethods.EnterText(ElementType.Id, "repCost2", "2");
            SeleniumSetMethods.EnterText(ElementType.Id, "repCost3", "3");
            SeleniumSetMethods.EnterText(ElementType.Id, "repName4", "repair4");
            SeleniumSetMethods.Click(ElementType.Id, "repIE4E");
            SeleniumSetMethods.Click(ElementType.XPath, "//table[@id='tabReps']/tbody/tr[5]/td[2]/label[2]");
            SeleniumSetMethods.EnterText(ElementType.Id, "repCost4", "4");
            SeleniumSetMethods.EnterText(ElementType.Id, "repName5", "5");
            SeleniumSetMethods.Click(ElementType.Id, "repIE5I");
            SeleniumSetMethods.EnterText(ElementType.Id, "repCost5", "5");
            SeleniumSetMethods.EnterText(ElementType.Id, "repName6", "6");
            SeleniumSetMethods.Click(ElementType.Id, "repIE6E");
            SeleniumSetMethods.EnterText(ElementType.Id, "repCost6", "6");
            SeleniumSetMethods.EnterText(ElementType.Id, "repName7", "7");
            SeleniumSetMethods.Click(ElementType.Id, "repIE7I");
            SeleniumSetMethods.EnterText(ElementType.Id, "repCost7", "7");
            SeleniumSetMethods.EnterText(ElementType.Id, "repName8", "8");
            SeleniumSetMethods.Click(ElementType.Id, "repIE8E");
            SeleniumSetMethods.Click(ElementType.XPath, "//table[@id='tabReps']/tbody/tr[9]/td[2]/label[2]");
            SeleniumSetMethods.EnterText(ElementType.Id, "repCost8", "8");
            SeleniumSetMethods.EnterText(ElementType.Id, "repName9", "9");
            SeleniumSetMethods.Click(ElementType.Id, "repIE9E");
            SeleniumSetMethods.EnterText(ElementType.Id, "repCost9", "9");
            SeleniumSetMethods.EnterText(ElementType.Id, "maYrBuilt", "1999");
            SeleniumSetMethods.EnterText(ElementType.Id, "maGLA", "2500");
            SeleniumSetMethods.EnterText(ElementType.Id, "maLotSize", "6500");
            SeleniumSetMethods.EnterText(ElementType.Id, "maBeds", "4");
            SeleniumSetMethods.EnterText(ElementType.Id, "maBaths", "25");
            SeleniumSetMethods.EnterText(ElementType.Id, "maBaths", "2");
            SeleniumSetMethods.EnterText(ElementType.Id, "maUnits", "15");
            SeleniumSetMethods.EnterText(ElementType.Id, "maUnits", "1");
            SeleniumSetMethods.EnterText(ElementType.Id, "maSrchRadius", "15");
            SeleniumSetMethods.SelectDropDown(ElementType.Name, "maPropType", "SFR");
            SeleniumSetMethods.Click(ElementType.Id, "maCompAge12");
            SeleniumSetMethods.Click(ElementType.XPath, "//table[@id='tabBorder1']/tbody/tr/td/div[11]/table/tbody/tr[10]/td[2]/label[2]");
            SeleniumSetMethods.EnterText(ElementType.Id, "maClosedSales", "6");
            SeleniumSetMethods.EnterText(ElementType.Id, "ma6moAbRate", "25");
            SeleniumSetMethods.EnterText(ElementType.Id, "maListsPendings", "33");
            SeleniumSetMethods.EnterText(ElementType.Id, "maMoSupply", "4");
            SeleniumSetMethods.EnterText(ElementType.Id, "ma6MoAvgLP", "411,111");
            SeleniumSetMethods.EnterText(ElementType.Id, "ma3MoAvgLP", "422,222");
            SeleniumSetMethods.EnterText(ElementType.Id, "ma6MoAvgSP", "433,333");
            SeleniumSetMethods.EnterText(ElementType.Id, "ma3MoAvgSP", "444,444");
            SeleniumSetMethods.EnterText(ElementType.Id, "ma6MoSLRatio", "15");
            SeleniumSetMethods.EnterText(ElementType.Id, "ma3MoSLRatio", "25");
            SeleniumSetMethods.Click(ElementType.Name, "btnSave");
            SeleniumSetMethods.Click(ElementType.CssSelector, "a > img");
            SeleniumSetMethods.EnterText(ElementType.Id, "txts1Addr", "2");
            SeleniumSetMethods.EnterText(ElementType.Id, "s1City", "Irvine");
            SeleniumSetMethods.EnterText(ElementType.Id, "s1Zip", "92620");
            SeleniumSetMethods.EnterText(ElementType.Id, "txts2Addr", "3");
            SeleniumSetMethods.EnterText(ElementType.Id, "s2City", "Irvine");
            SeleniumSetMethods.EnterText(ElementType.Id, "s2Zip", "92620");
            SeleniumSetMethods.EnterText(ElementType.Id, "txts3Addr", "4");
            SeleniumSetMethods.EnterText(ElementType.Id, "s3City", "Irvine");
            SeleniumSetMethods.EnterText(ElementType.Id, "s3Zip", "92620");
            SeleniumSetMethods.EnterText(ElementType.Id, "txtl1Addr", "5");
            SeleniumSetMethods.EnterText(ElementType.Id, "l1City", "Irvine");
            SeleniumSetMethods.EnterText(ElementType.Id, "l1Zip", "92620");
            SeleniumSetMethods.EnterText(ElementType.Id, "txtl2Addr", "6");
            SeleniumSetMethods.EnterText(ElementType.Id, "l2City", "Irvine");
            SeleniumSetMethods.EnterText(ElementType.Id, "l2Zip", "92620");
            SeleniumSetMethods.EnterText(ElementType.Id, "txtl3Addr", "7");
            SeleniumSetMethods.EnterText(ElementType.Id, "l3City", "Irvine");
            SeleniumSetMethods.EnterText(ElementType.Id, "l3Zip", "92620");
            SeleniumSetMethods.EnterText(ElementType.Id, "sbSrce", "sub Data");
            SeleniumSetMethods.EnterText(ElementType.Id, "s1Srce", "sale#1 Data");
            SeleniumSetMethods.EnterText(ElementType.Id, "s2Srce", "sale#2 Data");
            SeleniumSetMethods.EnterText(ElementType.Id, "s3Srce", "Sale#3 Data");
            SeleniumSetMethods.EnterText(ElementType.Id, "l1Srce", "List#1");
            SeleniumSetMethods.EnterText(ElementType.Id, "l2Srce", "List#2 data");
            SeleniumSetMethods.EnterText(ElementType.Id, "l3Srce", "List#3 data");
            SeleniumSetMethods.EnterText(ElementType.Id, "s1Prox", "1");
            SeleniumSetMethods.EnterText(ElementType.Id, "s2Prox", "2");
            SeleniumSetMethods.EnterText(ElementType.Id, "s3Prox", "2");
            SeleniumSetMethods.EnterText(ElementType.Id, "l1Prox", "1");
            SeleniumSetMethods.EnterText(ElementType.Id, "l2Prox", "3");
            SeleniumSetMethods.EnterText(ElementType.Id, "l3Prox", "6");
            SeleniumSetMethods.EnterText(ElementType.Id, "sbOLDt", "07/11/2016");
            SeleniumSetMethods.EnterText(ElementType.Id, "s1OLDt", "07/01/2016");
            SeleniumSetMethods.EnterText(ElementType.Id, "s2OLDt", "07/02/2016");
            SeleniumSetMethods.EnterText(ElementType.Id, "s3OLDt", "07/03/2016");
            SeleniumSetMethods.EnterText(ElementType.Id, "l1OLDt", "07/04/2016");
            SeleniumSetMethods.EnterText(ElementType.Id, "l2OLDt", "07/05/2016");
            SeleniumSetMethods.EnterText(ElementType.Id, "l3OLDt", "07/06/2016");
            SeleniumSetMethods.EnterText(ElementType.Id, "sbOLp", "400,001");
            SeleniumSetMethods.EnterText(ElementType.Id, "sbLLP", "400,000");
            SeleniumSetMethods.EnterText(ElementType.Id, "s1OLp", "410,000");
            SeleniumSetMethods.EnterText(ElementType.Id, "s1LLP", "409,000");
            SeleniumSetMethods.EnterText(ElementType.Id, "s1SaleDt", "07/15/2016");
            SeleniumSetMethods.EnterText(ElementType.Id, "s2OLp", "411,000");
            SeleniumSetMethods.EnterText(ElementType.Id, "s2LLP", "411,000");
            SeleniumSetMethods.EnterText(ElementType.Id, "s2SaleDt", "07/16/2016");
            SeleniumSetMethods.EnterText(ElementType.Id, "s3OLp", "412,111");
            SeleniumSetMethods.EnterText(ElementType.Id, "s3LLP", "412,222");
            SeleniumSetMethods.EnterText(ElementType.Id, "s3SaleDt", "07/17/2016");
            SeleniumSetMethods.EnterText(ElementType.Id, "l1OLp", "395000");
            SeleniumSetMethods.EnterText(ElementType.Id, "l1LLP", "394000");
            SeleniumSetMethods.EnterText(ElementType.Id, "l2OLp", "380000");
            SeleniumSetMethods.EnterText(ElementType.Id, "l2LLP", "388,333");
            SeleniumSetMethods.EnterText(ElementType.Id, "l3OLp", "384,333");
            SeleniumSetMethods.EnterText(ElementType.Id, "l3LLP", "382,222");
            SeleniumSetMethods.EnterText(ElementType.Id, "s1SP", "408000");
            SeleniumSetMethods.EnterText(ElementType.Id, "s2SP", "410000");
            SeleniumSetMethods.EnterText(ElementType.Id, "s3SP", "412333");
            SeleniumSetMethods.EnterText(ElementType.Id, "sbDom", "32");
            SeleniumSetMethods.EnterText(ElementType.Id, "s1Dom", "33");
            SeleniumSetMethods.EnterText(ElementType.Id, "s2Dom", "34");
            SeleniumSetMethods.EnterText(ElementType.Id, "s3Dom", "35");
            SeleniumSetMethods.EnterText(ElementType.Id, "l1Dom", "36");
            SeleniumSetMethods.EnterText(ElementType.Id, "l2Dom", "37");
            SeleniumSetMethods.EnterText(ElementType.Id, "l3Dom", "38");
            SeleniumSetMethods.EnterText(ElementType.Id, "sbCumDom", "41");
            SeleniumSetMethods.EnterText(ElementType.Id, "s1CumDom", "42");
            SeleniumSetMethods.EnterText(ElementType.Id, "s2CumDom", "43");
            SeleniumSetMethods.EnterText(ElementType.Id, "s3CumDom", "44");
            SeleniumSetMethods.EnterText(ElementType.Id, "l1CumDom", "45");
            SeleniumSetMethods.EnterText(ElementType.Id, "l2CumDom", "46");
            SeleniumSetMethods.EnterText(ElementType.Id, "l3CumDom", "47");
            SeleniumSetMethods.EnterText(ElementType.Id, "sbSrceFunds", "sub FUND");
            SeleniumSetMethods.EnterText(ElementType.Id, "s1SrceFunds", "sal#1 Find");
            SeleniumSetMethods.EnterText(ElementType.Id, "s2SrceFunds", "Sale#Fund");
            SeleniumSetMethods.EnterText(ElementType.Id, "s3SrceFunds", "Sale#3 Fund");
            SeleniumSetMethods.EnterText(ElementType.Id, "l1SrceFunds", "List#1 Fund");
            SeleniumSetMethods.EnterText(ElementType.Id, "l2SrceFunds", "List#2 Fund");
            SeleniumSetMethods.EnterText(ElementType.Id, "l3SrceFunds", "List#3 Fund");
            SeleniumSetMethods.EnterText(ElementType.Id, "sbConcess", "Sub Con");
            SeleniumSetMethods.EnterText(ElementType.Id, "s1Concess", "Sale#1 Con");
            SeleniumSetMethods.EnterText(ElementType.Id, "s2Concess", "Sale#3 Con");
            SeleniumSetMethods.EnterText(ElementType.Id, "s3Concess", "Sale#3 con");
            SeleniumSetMethods.EnterText(ElementType.Id, "l1Concess", "List#1 Con");
            SeleniumSetMethods.EnterText(ElementType.Id, "l2Concess", "List#2 Con");
            SeleniumSetMethods.EnterText(ElementType.Id, "l3Concess", "List#3 Con");
            SeleniumSetMethods.SelectDropDown(ElementType.Id, "sbDistSale", "No");
            SeleniumSetMethods.SelectDropDown(ElementType.Id, "s1DistSale", "No");
            SeleniumSetMethods.SelectDropDown(ElementType.Id, "s2DistSale", "Yes");
            SeleniumSetMethods.SelectDropDown(ElementType.Id, "s3DistSale", "No");
            SeleniumSetMethods.SelectDropDown(ElementType.Id, "l1DistSale", "Yes");
            SeleniumSetMethods.SelectDropDown(ElementType.Id, "l2DistSale", "No");
            SeleniumSetMethods.SelectDropDown(ElementType.Id, "l3DistSale", "No");
            SeleniumSetMethods.EnterText(ElementType.Id, "sbLotSize", "2");
            SeleniumSetMethods.EnterText(ElementType.Id, "sbSiteSize", "3");
            SeleniumSetMethods.EnterText(ElementType.Id, "s1LotSize", "1");
            SeleniumSetMethods.EnterText(ElementType.Id, "s1SiteSize", "2");
            SeleniumSetMethods.EnterText(ElementType.Id, "s2LotSize", "2");
            SeleniumSetMethods.EnterText(ElementType.Id, "s2SiteSize", "3");
            SeleniumSetMethods.EnterText(ElementType.Id, "s3LotSize", "3");
            SeleniumSetMethods.EnterText(ElementType.Id, "s3SiteSize", "4");
            SeleniumSetMethods.EnterText(ElementType.Id, "l1LotSize", "0");
            SeleniumSetMethods.EnterText(ElementType.Id, "l1SiteSize", "1");
            SeleniumSetMethods.EnterText(ElementType.Id, "l2LotSize", "3");
            SeleniumSetMethods.EnterText(ElementType.Id, "l2SiteSize", "2");
            SeleniumSetMethods.EnterText(ElementType.Id, "l3LotSize", "4");
            SeleniumSetMethods.EnterText(ElementType.Id, "l3SiteSize", "4");
            SeleniumSetMethods.SelectDropDown(ElementType.Name, "sbView", "Neutral");
            SeleniumSetMethods.SelectDropDown(ElementType.Name, "s1View", "Beneficial");
            SeleniumSetMethods.SelectDropDown(ElementType.Name, "s2View", "Adverse");
            SeleniumSetMethods.SelectDropDown(ElementType.Name, "s3View", "Neutral");
            SeleniumSetMethods.SelectDropDown(ElementType.Name, "l1View", "Beneficial");
            SeleniumSetMethods.SelectDropDown(ElementType.Name, "l2View", "Adverse");
            SeleniumSetMethods.SelectDropDown(ElementType.Name, "l3View", "Adverse");
            SeleniumSetMethods.SelectDropDown(ElementType.Name, "s1Comparison", "Good");
            SeleniumSetMethods.SelectDropDown(ElementType.Name, "s2Comparison", "Satisfactory");
            SeleniumSetMethods.SelectDropDown(ElementType.Name, "s3Comparison", "Poor");
            SeleniumSetMethods.SelectDropDown(ElementType.Name, "l1Comparison", "Poor");
            SeleniumSetMethods.SelectDropDown(ElementType.Name, "l2Comparison", "Satisfactory");
            SeleniumSetMethods.SelectDropDown(ElementType.Name, "l3Comparison", "Good");
            SeleniumSetMethods.SelectDropDown(ElementType.Name, "sbPropType", "SFR");
            SeleniumSetMethods.SelectDropDown(ElementType.Name, "s1PropType", "CONDO");
            SeleniumSetMethods.SelectDropDown(ElementType.Name, "s2PropType", "Manufactured");
            SeleniumSetMethods.SelectDropDown(ElementType.Name, "s3PropType", "Other");
            SeleniumSetMethods.SelectDropDown(ElementType.Name, "l1PropType", "SFR");
            SeleniumSetMethods.SelectDropDown(ElementType.Name, "l2PropType", "COOP");
            SeleniumSetMethods.SelectDropDown(ElementType.Name, "l3PropType", "PUD");
            SeleniumSetMethods.EnterText(ElementType.Id, "sbUnits", "1");
            SeleniumSetMethods.EnterText(ElementType.Id, "s1Units", "2");
            SeleniumSetMethods.EnterText(ElementType.Id, "s2Units", "2");
            SeleniumSetMethods.EnterText(ElementType.Id, "s3Units", "1");
            SeleniumSetMethods.EnterText(ElementType.Id, "l1Units", "1");
            SeleniumSetMethods.EnterText(ElementType.Id, "l2Units", "2");
            SeleniumSetMethods.EnterText(ElementType.Id, "l3Units", "1");
            SeleniumSetMethods.SelectDropDown(ElementType.Name, "sbConstructType", "Aluminum");
            SeleniumSetMethods.SelectDropDown(ElementType.Name, "s1ConstructType", "Brick");
            SeleniumSetMethods.SelectDropDown(ElementType.Name, "s2ConstructType", "Stone");
            SeleniumSetMethods.SelectDropDown(ElementType.Name, "s3ConstructType", "Vinyl");
            SeleniumSetMethods.SelectDropDown(ElementType.Name, "l1ConstructType", "Wood");
            SeleniumSetMethods.SelectDropDown(ElementType.Name, "l2ConstructType", "Other");
            SeleniumSetMethods.SelectDropDown(ElementType.Name, "l3ConstructType", "Stone");
            SeleniumSetMethods.EnterText(ElementType.Id, "sbDesign", "sub Sedign");
            SeleniumSetMethods.EnterText(ElementType.Id, "s1Design", "sal#1 Design");
            SeleniumSetMethods.EnterText(ElementType.Id, "s2Design", "sale#2 desig");
            SeleniumSetMethods.EnterText(ElementType.Id, "s3Design", "Sale#3 desig");
            SeleniumSetMethods.EnterText(ElementType.Id, "l1Design", "List#1 desig");
            SeleniumSetMethods.EnterText(ElementType.Id, "l2Design", "List#2 desig");
            SeleniumSetMethods.EnterText(ElementType.Id, "l3Design", "list#3 desig");
            SeleniumSetMethods.EnterText(ElementType.Id, "sbAge", "12");
            SeleniumSetMethods.EnterText(ElementType.Id, "s1Age", "13");
            SeleniumSetMethods.EnterText(ElementType.Id, "s2Age", "14");
            SeleniumSetMethods.EnterText(ElementType.Id, "s3Age", "10");
            SeleniumSetMethods.EnterText(ElementType.Id, "l1Age", "3");
            SeleniumSetMethods.EnterText(ElementType.Id, "l2Age", "6");
            SeleniumSetMethods.EnterText(ElementType.Id, "l3Age", "11");
            SeleniumSetMethods.SelectDropDown(ElementType.Name, "sbCondition", "Good");
            SeleniumSetMethods.SelectDropDown(ElementType.Name, "s1Condition", "Average");
            SeleniumSetMethods.SelectDropDown(ElementType.Name, "s2Condition", "Poor");
            SeleniumSetMethods.SelectDropDown(ElementType.Name, "s3Condition", "Average");
            SeleniumSetMethods.SelectDropDown(ElementType.Name, "l1Condition", "Average");
            SeleniumSetMethods.SelectDropDown(ElementType.Name, "l2Condition", "Good");
            SeleniumSetMethods.SelectDropDown(ElementType.Name, "l3Condition", "Poor");
            SeleniumSetMethods.EnterText(ElementType.Id, "sbGla", "2500");
            SeleniumSetMethods.EnterText(ElementType.Id, "s1Gla", "1550");
            SeleniumSetMethods.EnterText(ElementType.Id, "s2Gla", "2650");
            SeleniumSetMethods.EnterText(ElementType.Id, "s3Gla", "1800");
            SeleniumSetMethods.EnterText(ElementType.Id, "l1Gla", "2750");
            SeleniumSetMethods.EnterText(ElementType.Id, "l2Gla", "1951");
            SeleniumSetMethods.EnterText(ElementType.Id, "l3Gla", "2550");
            SeleniumSetMethods.EnterText(ElementType.Id, "sbRooms", "6");
            SeleniumSetMethods.EnterText(ElementType.Id, "sbBeds", "4");
            SeleniumSetMethods.EnterText(ElementType.Id, "sbFull", "3");
            SeleniumSetMethods.EnterText(ElementType.Id, "sbPartial", "2");
            SeleniumSetMethods.EnterText(ElementType.Id, "s1Rooms", "7");
            SeleniumSetMethods.EnterText(ElementType.Id, "s1Beds", "6");
            SeleniumSetMethods.EnterText(ElementType.Id, "s1Full", "2");
            SeleniumSetMethods.EnterText(ElementType.Id, "s1Partial", "1");
            SeleniumSetMethods.EnterText(ElementType.Id, "s2Rooms", "5");
            SeleniumSetMethods.EnterText(ElementType.Id, "s2Beds", "3");
            SeleniumSetMethods.EnterText(ElementType.Id, "s2Full", "3");
            SeleniumSetMethods.EnterText(ElementType.Id, "s2Partial", "0");
            SeleniumSetMethods.EnterText(ElementType.Id, "s3Rooms", "8");
            SeleniumSetMethods.EnterText(ElementType.Id, "s3Beds", "6");
            SeleniumSetMethods.EnterText(ElementType.Id, "s3Full", "3");
            SeleniumSetMethods.EnterText(ElementType.Id, "s3Partial", "1");
            SeleniumSetMethods.EnterText(ElementType.Id, "l1Rooms", "6");
            SeleniumSetMethods.EnterText(ElementType.Id, "l1Beds", "5");
            SeleniumSetMethods.EnterText(ElementType.Id, "l1Full", "2");
            SeleniumSetMethods.EnterText(ElementType.Id, "l1Partial", "2");
            SeleniumSetMethods.EnterText(ElementType.Id, "l2Rooms", "8");
            SeleniumSetMethods.EnterText(ElementType.Id, "l2Beds", "4");
            SeleniumSetMethods.EnterText(ElementType.Id, "l2Full", "1");
            SeleniumSetMethods.EnterText(ElementType.Id, "l2Partial", "1");
            SeleniumSetMethods.EnterText(ElementType.Id, "l3Rooms", "6");
            SeleniumSetMethods.EnterText(ElementType.Id, "l3Beds", "2");
            SeleniumSetMethods.EnterText(ElementType.Id, "l3Beds", "3");
            SeleniumSetMethods.EnterText(ElementType.Id, "l3Full", "1");
            SeleniumSetMethods.EnterText(ElementType.Id, "l3Partial", "1");
            SeleniumSetMethods.EnterText(ElementType.Id, "sbBasement", "sub basement");
            SeleniumSetMethods.EnterText(ElementType.Id, "s1Basement", "Sale#1 basem");
            SeleniumSetMethods.EnterText(ElementType.Id, "s2Basement", "sale#2 Basem");
            SeleniumSetMethods.EnterText(ElementType.Id, "s3Basement", "sale#3 Basem");
            SeleniumSetMethods.EnterText(ElementType.Id, "l1Basement", "List#1 basem");
            SeleniumSetMethods.EnterText(ElementType.Id, "l2Basement", "L1st#2 Base");
            SeleniumSetMethods.EnterText(ElementType.Id, "l3Basement", "list#3 bas");
            SeleniumSetMethods.EnterText(ElementType.Id, "sbSF", "100");
            SeleniumSetMethods.EnterText(ElementType.Id, "sbPerc", "0");
            SeleniumSetMethods.EnterText(ElementType.Id, "s1SF", "1500");
            SeleniumSetMethods.EnterText(ElementType.Id, "s1Perc", "10");
            SeleniumSetMethods.EnterText(ElementType.Id, "s2SF", "250");
            SeleniumSetMethods.EnterText(ElementType.Id, "s2Perc", "100");
            SeleniumSetMethods.EnterText(ElementType.Id, "s3SF", "500");
            SeleniumSetMethods.EnterText(ElementType.Id, "s3Perc", "15");
            SeleniumSetMethods.EnterText(ElementType.Id, "l1SF", "250");
            SeleniumSetMethods.EnterText(ElementType.Id, "l1Perc", "10");
            SeleniumSetMethods.EnterText(ElementType.Id, "l2SF", "550");
            SeleniumSetMethods.EnterText(ElementType.Id, "l2Perc", "0");
            SeleniumSetMethods.EnterText(ElementType.Id, "l3SF", "250");
            SeleniumSetMethods.EnterText(ElementType.Id, "l3Perc", "0");
            SeleniumSetMethods.SelectDropDown(ElementType.Name, "sbParking", "driveway");
            SeleniumSetMethods.EnterText(ElementType.Id, "sbStalls", "2");
            SeleniumSetMethods.SelectDropDown(ElementType.Name, "s1Parking", "garage");
            SeleniumSetMethods.EnterText(ElementType.Id, "s1Stalls", "3");
            SeleniumSetMethods.SelectDropDown(ElementType.Name, "s2Parking", "none");
            SeleniumSetMethods.EnterText(ElementType.Id, "s2Stalls", "0");
            SeleniumSetMethods.SelectDropDown(ElementType.Name, "s3Parking", "driveway");
            SeleniumSetMethods.EnterText(ElementType.Id, "s3Stalls", "2");
            SeleniumSetMethods.SelectDropDown(ElementType.Name, "l1Parking", "garage");
            SeleniumSetMethods.EnterText(ElementType.Id, "l1Stalls", "1");
            SeleniumSetMethods.SelectDropDown(ElementType.Name, "l2Parking", "none");
            SeleniumSetMethods.SelectDropDown(ElementType.Name, "l2Parking", "driveway");
            SeleniumSetMethods.EnterText(ElementType.Id, "l2Stalls", "3");
            SeleniumSetMethods.SelectDropDown(ElementType.Name, "l3Parking", "none");
            SeleniumSetMethods.EnterText(ElementType.Id, "l3Stalls", "0");
            SeleniumSetMethods.EnterText(ElementType.Id, "sbPool", "sub pool");
            SeleniumSetMethods.EnterText(ElementType.Id, "s1Pool", "Sale#1 Pool");
            SeleniumSetMethods.EnterText(ElementType.Id, "s2Pool", "Sale#2 Pool");
            SeleniumSetMethods.EnterText(ElementType.Id, "s3Pool", "Sale#3 Pool");
            SeleniumSetMethods.EnterText(ElementType.Id, "l1Pool", "List#1 Pool");
            SeleniumSetMethods.EnterText(ElementType.Id, "l2Pool", "List#2 Pool");
            SeleniumSetMethods.EnterText(ElementType.Id, "l3Pool", "List#3 Pool");
            SeleniumSetMethods.EnterText(ElementType.Id, "sbOther", "Sub Other");
            SeleniumSetMethods.EnterText(ElementType.Id, "s1Other", "s1# Other");
            SeleniumSetMethods.EnterText(ElementType.Id, "s2Other", "Sale#2 Other");
            SeleniumSetMethods.EnterText(ElementType.Id, "s3Other", "sale#3 Other");
            SeleniumSetMethods.EnterText(ElementType.Id, "l1Other", "List#1 other");
            SeleniumSetMethods.EnterText(ElementType.Id, "l2Other", "List#2 Other");
            SeleniumSetMethods.EnterText(ElementType.Id, "l3Other", "List#3 Other");
            SeleniumSetMethods.EnterText(ElementType.Id, "sbHoa", "180");
            SeleniumSetMethods.EnterText(ElementType.Id, "s1Hoa", "175");
            SeleniumSetMethods.EnterText(ElementType.Id, "s2Hoa", "170");
            SeleniumSetMethods.EnterText(ElementType.Id, "s3Hoa", "0");
            SeleniumSetMethods.EnterText(ElementType.Id, "l1Hoa", "125");
            SeleniumSetMethods.EnterText(ElementType.Id, "l2Hoa", "250");
            SeleniumSetMethods.EnterText(ElementType.Id, "l3Hoa", "222");
            SeleniumSetMethods.SelectDropDown(ElementType.Name, "s1Overall", "Satisfactory");
            SeleniumSetMethods.SelectDropDown(ElementType.Name, "s2Overall", "Good");
            SeleniumSetMethods.SelectDropDown(ElementType.Name, "s3Overall", "Poor");
            SeleniumSetMethods.SelectDropDown(ElementType.Name, "l1Overall", "Satisfactory");
            SeleniumSetMethods.SelectDropDown(ElementType.Name, "l2Overall", "Good");
            SeleniumSetMethods.SelectDropDown(ElementType.Name, "l3Overall", "Poor");
            SeleniumSetMethods.EnterText(ElementType.Id, "txts1Notes", "sale# 1 comments: Test");
            SeleniumSetMethods.EnterText(ElementType.Id, "txts2Notes", "Sale#2 Comments : Test");
            SeleniumSetMethods.EnterText(ElementType.Id, "txts3Notes", "Sale#3 Comments: Test");
            SeleniumSetMethods.EnterText(ElementType.Id, "txtl1Notes", "List#1 Commenst : test");
            SeleniumSetMethods.EnterText(ElementType.Id, "txtl2Notes", "List #2 Comments: test");
            SeleniumSetMethods.EnterText(ElementType.Id, "txtl3Notes", "List#3 Comment s: Test");
            SeleniumSetMethods.EnterText(ElementType.Id, "poSugLp30", "511,111");
            SeleniumSetMethods.EnterText(ElementType.Id, "poProbSp30", "522,222");
            SeleniumSetMethods.EnterText(ElementType.Id, "poDomAsIs", "111");
            SeleniumSetMethods.EnterText(ElementType.Id, "poSugLpAsIs", "533,333");
            SeleniumSetMethods.EnterText(ElementType.Id, "poProbSpAsIs", "544,444");
            SeleniumSetMethods.EnterText(ElementType.Id, "poDomRep", "222");
            SeleniumSetMethods.EnterText(ElementType.Id, "poSugLpRep", "555,555");
            SeleniumSetMethods.EnterText(ElementType.Id, "poProbSpRep", "566,666");
            SeleniumSetMethods.EnterText(ElementType.Id, "txtpoNotes", "Comments : test");
            SeleniumSetMethods.EnterText(ElementType.Id, "certSign", "Test");
            SeleniumSetMethods.EnterText(ElementType.Id, "certBy", "Test");
            SeleniumSetMethods.EnterText(ElementType.Id, "certByDate", "07/25/2016");
            SeleniumSetMethods.EnterText(ElementType.Id, "certBkr", "Listing Agent test");
            SeleniumSetMethods.SelectDropDown(ElementType.Name, "certState", "California");
            SeleniumSetMethods.EnterText(ElementType.Id, "certCompany", "Testt company");
            SeleniumSetMethods.EnterText(ElementType.Id, "certComanyAddr", "123 main street, lake forest CA 92630");
            SeleniumSetMethods.EnterText(ElementType.Name, "certPhone", "label=7528529988");
            SeleniumSetMethods.Click(ElementType.Id, "btnSaveWorkPg2");

        }


        public static void REOBPO()
        {
            //REO BPO 
            SeleniumWindowMethods.Sleep(2);
            Global.ConsoleOut("Pause Me");
            SeleniumWindowMethods.Sleep(5);
            SeleniumSetMethods.EnterText(ElementType.Name, "abNdList", "4");
            SeleniumSetMethods.EnterText(ElementType.Name, "abNdHouses", "3");
            SeleniumSetMethods.EnterText(ElementType.Name, "abNdLow", "450000");
            SeleniumSetMethods.EnterText(ElementType.Name, "abNdHigh", "550000");
            SeleniumSetMethods.EnterText(ElementType.Name, "abNdClose", "45");
            SeleniumSetMethods.EnterText(ElementType.Name, "abNdMktTime", "5");
            SeleniumSetMethods.EnterText(ElementType.Name, "abNdSale", "15");
            SeleniumSetMethods.EnterText(ElementType.Name, "abNdConstr", "no");
            SeleniumSetMethods.EnterText(ElementType.Name, "abNdAssess", "no");
            SeleniumSetMethods.EnterText(ElementType.Name, "abNdNeg", "Industial Near by");
            SeleniumSetMethods.EnterText(ElementType.Name, "abNdMonthly", "12");
            SeleniumSetMethods.EnterText(ElementType.Name, "abStyle", "ranch");
            SeleniumSetMethods.EnterText(ElementType.Name, "abSqFt", "1850");
            SeleniumSetMethods.EnterText(ElementType.Name, "abRooms", "8");
            SeleniumSetMethods.EnterText(ElementType.Name, "abBed", "5");
            SeleniumSetMethods.EnterText(ElementType.Name, "abBath", "2.5");
            SeleniumSetMethods.EnterText(ElementType.Name, "abRent", "1500");
            SeleniumSetMethods.EnterText(ElementType.Name, "abBsmt", "250");
            SeleniumSetMethods.EnterText(ElementType.Name, "abGar", "3");
            SeleniumSetMethods.EnterText(ElementType.Name, "abLot", "4500");
            SeleniumSetMethods.EnterText(ElementType.Name, "abAge", "15");
            SeleniumSetMethods.EnterText(ElementType.Name, "abPrevDom", "45");
            SeleniumSetMethods.EnterText(ElementType.Name, "abPrevLP", "350000");
            SeleniumSetMethods.EnterText(ElementType.Name, "abCurrLP", "375000");
            SeleniumSetMethods.EnterText(ElementType.Name, "abCond", "good");
            SeleniumSetMethods.EnterText(ElementType.Name, "txtabMktComments", "PMarket Market plan : Start  TESTS is interested in receiving information about your company and services.  Due to the diversity of our customer base and their varying geographical regi
            SeleniumSetMethods.Click(ElementType.Name, "cbRI_roof");
            SeleniumSetMethods.Click(ElementType.Name, "cbRI_termite");
            SeleniumSetMethods.EnterText(ElementType.Name, "abRI_other", "test");
            SeleniumSetMethods.EnterText(ElementType.Name, "abRI_Ordered", "11/01/2016");
            SeleniumSetMethods.EnterText(ElementType.Name, "abRI_Haz", "hazardous");
            SeleniumSetMethods.EnterText(ElementType.Name, "abRI_Pers", "none");
            SeleniumSetMethods.EnterText(ElementType.Name, "abAddrS1", "1 test");
            SeleniumSetMethods.EnterText(ElementType.Name, "abSaleDtS1", "11/01/2016");
            SeleniumSetMethods.EnterText(ElementType.Name, "abSqFtS1", "1550");
            SeleniumSetMethods.EnterText(ElementType.Name, "abTotalS1", "3");
            SeleniumSetMethods.EnterText(ElementType.Name, "abBedS1", "3");
            SeleniumSetMethods.EnterText(ElementType.Name, "abTotalS1", "6");
            SeleniumSetMethods.EnterText(ElementType.Name, "abBathS1", "2.5");
            SeleniumSetMethods.EnterText(ElementType.Name, "abProxS1", "1");
            SeleniumSetMethods.EnterText(ElementType.Name, "abBsmtS1", "0");
            SeleniumSetMethods.EnterText(ElementType.Name, "abGarS1", "2");
            SeleniumSetMethods.EnterText(ElementType.Name, "abLotS1", "2550");
            SeleniumSetMethods.EnterText(ElementType.Name, "abAgeS1", "13");
            SeleniumSetMethods.EnterText(ElementType.Name, "abDomS1", "20");
            SeleniumSetMethods.EnterText(ElementType.Name, "abLpS1", "425000");
            SeleniumSetMethods.EnterText(ElementType.Name, "abSpS1", "450000");
            SeleniumSetMethods.EnterText(ElementType.Name, "abOwnerS1", "owner1");
            SeleniumSetMethods.EnterText(ElementType.Name, "abAddrS2", "2");
            SeleniumSetMethods.EnterText(ElementType.Name, "abSaleDtS2", "11/02/2016");
            SeleniumSetMethods.EnterText(ElementType.Name, "abSqFtS2", "1650");
            SeleniumSetMethods.EnterText(ElementType.Name, "abTotalS2", "7");
            SeleniumSetMethods.EnterText(ElementType.Name, "abBedS2", "4");
            SeleniumSetMethods.EnterText(ElementType.Name, "abBathS2", "3");
            SeleniumSetMethods.EnterText(ElementType.Name, "abProxS2", "1");
            SeleniumSetMethods.EnterText(ElementType.Name, "abBsmtS2", "150");
            SeleniumSetMethods.EnterText(ElementType.Name, "abGarS2", "3");
            SeleniumSetMethods.EnterText(ElementType.Name, "abLotS2", "3500");
            SeleniumSetMethods.EnterText(ElementType.Name, "abAgeS2", "14");
            SeleniumSetMethods.EnterText(ElementType.Name, "abDomS2", "25");
            SeleniumSetMethods.EnterText(ElementType.Name, "abLpS2", "430000");
            SeleniumSetMethods.EnterText(ElementType.Name, "abSpS2", "430000");
            SeleniumSetMethods.EnterText(ElementType.Name, "abOwnerS2", "owner2");
            SeleniumSetMethods.EnterText(ElementType.Name, "abAddrS3", "3");
            SeleniumSetMethods.EnterText(ElementType.Name, "abSaleDtS3", "11/03/2016");
            SeleniumSetMethods.EnterText(ElementType.Name, "abSqFtS3", "1600");
            SeleniumSetMethods.EnterText(ElementType.Name, "abTotalS3", "7");
            SeleniumSetMethods.EnterText(ElementType.Name, "abBedS3", "3");
            SeleniumSetMethods.EnterText(ElementType.Name, "abBathS3", "2.5");
            SeleniumSetMethods.EnterText(ElementType.Name, "abProxS3", "1");
            SeleniumSetMethods.EnterText(ElementType.Name, "abBsmtS3", "0");
            SeleniumSetMethods.EnterText(ElementType.Name, "abGarS3", "2");
            SeleniumSetMethods.EnterText(ElementType.Name, "abLotS3", "3000");
            SeleniumSetMethods.EnterText(ElementType.Name, "abAgeS3", "14");
            SeleniumSetMethods.EnterText(ElementType.Name, "abDomS3", "20");
            SeleniumSetMethods.EnterText(ElementType.Name, "abLpS3", "435000");
            SeleniumSetMethods.EnterText(ElementType.Name, "abSpS3", "430000");
            SeleniumSetMethods.EnterText(ElementType.Name, "abOwnerS3", "owner3");
            SeleniumSetMethods.EnterText(ElementType.Name, "abCondS1", "s1 condition");
            SeleniumSetMethods.EnterText(ElementType.Name, "abFinS1", "s1 finanacining");
            SeleniumSetMethods.EnterText(ElementType.Name, "abCommS1", "s1 comments");
            SeleniumSetMethods.EnterText(ElementType.Name, "abCondS2", "s2 commnets");
            SeleniumSetMethods.EnterText(ElementType.Name, "abFinS2", "s2 finanace");
            SeleniumSetMethods.EnterText(ElementType.Name, "abCommS2", "s2 comments");
            SeleniumSetMethods.EnterText(ElementType.Name, "abCondS3", "s3 comments");
            SeleniumSetMethods.EnterText(ElementType.Name, "abFinS3", "s2 finanace");
            SeleniumSetMethods.EnterText(ElementType.Name, "abCommS3", "s3 commnets");
            SeleniumSetMethods.Click(ElementType.Name, "cbInspS1");
            SeleniumSetMethods.Click(ElementType.Name, "cbInspS2");
            SeleniumSetMethods.Click(ElementType.Name, "cbInspS3");
            SeleniumSetMethods.EnterText(ElementType.Name, "abCommS", "SALES:Test comment limit & to max 60 character.Limit is END");
            SeleniumSetMethods.EnterText(ElementType.Name, "abAddrL1", "4");
            SeleniumSetMethods.EnterText(ElementType.Name, "abStyleL1", "ranch");
            SeleniumSetMethods.EnterText(ElementType.Name, "abSqFtL1", "1550");
            SeleniumSetMethods.EnterText(ElementType.Name, "abTotalL1", "8");
            SeleniumSetMethods.EnterText(ElementType.Name, "abBedL1", "4");
            SeleniumSetMethods.EnterText(ElementType.Name, "abBathL1", "2.5");
            SeleniumSetMethods.EnterText(ElementType.Name, "abProxL1", "1");
            SeleniumSetMethods.EnterText(ElementType.Name, "abBsmtL1", "0");
            SeleniumSetMethods.EnterText(ElementType.Name, "abGarL1", "3");
            SeleniumSetMethods.EnterText(ElementType.Name, "abLotL1", "3000");
            SeleniumSetMethods.EnterText(ElementType.Name, "abAgeL1", "12");
            SeleniumSetMethods.EnterText(ElementType.Name, "abDomL1", "30");
            SeleniumSetMethods.EnterText(ElementType.Name, "abOLpL1", "425000");
            SeleniumSetMethods.EnterText(ElementType.Name, "abLpL1", "435000");
            SeleniumSetMethods.EnterText(ElementType.Name, "abOwnerL1", "comp1");
            SeleniumSetMethods.EnterText(ElementType.Name, "abAddrL2", "5");
            SeleniumSetMethods.EnterText(ElementType.Name, "abStyleL2", "a-style");
            SeleniumSetMethods.EnterText(ElementType.Name, "abSqFtL2", "1756");
            SeleniumSetMethods.EnterText(ElementType.Name, "abTotalL2", "7");
            SeleniumSetMethods.EnterText(ElementType.Name, "abBedL2", "3");
            SeleniumSetMethods.EnterText(ElementType.Name, "abBathL2", "3");
            SeleniumSetMethods.EnterText(ElementType.Name, "abProxL2", "1");
            SeleniumSetMethods.EnterText(ElementType.Name, "abBsmtL2", "200");
            SeleniumSetMethods.EnterText(ElementType.Name, "abGarL2", "2");
            SeleniumSetMethods.EnterText(ElementType.Name, "abLotL2", "3500");
            SeleniumSetMethods.EnterText(ElementType.Name, "abAgeL2", "14");
            SeleniumSetMethods.EnterText(ElementType.Name, "abDomL2", "45");
            SeleniumSetMethods.EnterText(ElementType.Name, "abOLpL2", "475000");
            SeleniumSetMethods.EnterText(ElementType.Name, "abLpL2", "450000");
            SeleniumSetMethods.EnterText(ElementType.Name, "abOwnerL2", "comp2");
            SeleniumSetMethods.EnterText(ElementType.Name, "abAddrL3", "6");
            SeleniumSetMethods.EnterText(ElementType.Name, "abStyleL3", "mordern");
            SeleniumSetMethods.EnterText(ElementType.Name, "abSqFtL3", "1850");
            SeleniumSetMethods.EnterText(ElementType.Name, "abTotalL3", "6");
            SeleniumSetMethods.EnterText(ElementType.Name, "abBedL3", "3");
            SeleniumSetMethods.EnterText(ElementType.Name, "abBathL3", "1.5");
            SeleniumSetMethods.EnterText(ElementType.Name, "abProxL3", "1");
            SeleniumSetMethods.EnterText(ElementType.Name, "abBsmtL3", "0");
            SeleniumSetMethods.EnterText(ElementType.Name, "abGarL3", "4");
            SeleniumSetMethods.EnterText(ElementType.Name, "abLotL3", "3750");
            SeleniumSetMethods.EnterText(ElementType.Name, "abAgeL3", "16");
            SeleniumSetMethods.EnterText(ElementType.Name, "abDomL3", "40");
            SeleniumSetMethods.EnterText(ElementType.Name, "abOLpL3", "440000");
            SeleniumSetMethods.EnterText(ElementType.Name, "abLpL3", "440000");
            SeleniumSetMethods.EnterText(ElementType.Name, "abOwnerL3", "comp3");
            SeleniumSetMethods.EnterText(ElementType.Name, "abCondL1", "list1 condition");
            SeleniumSetMethods.EnterText(ElementType.Name, "abFinL1", "c1 finance");
            SeleniumSetMethods.EnterText(ElementType.Name, "abCommL1", "l1 commnets");
            SeleniumSetMethods.EnterText(ElementType.Name, "abCondL2", "l2 condition");
            SeleniumSetMethods.EnterText(ElementType.Name, "abFinL2", "c2 finance");
            SeleniumSetMethods.EnterText(ElementType.Name, "abCommL2", "l2 comments");
            SeleniumSetMethods.EnterText(ElementType.Name, "abCondL3", "l3 condition");
            SeleniumSetMethods.EnterText(ElementType.Name, "abFinL3", "c3 finance");
            SeleniumSetMethods.EnterText(ElementType.Name, "abCommL3", "l3 comments");
            SeleniumSetMethods.Click(ElementType.Name, "cbInspL1");
            SeleniumSetMethods.Click(ElementType.Name, "cbInspL2");
            SeleniumSetMethods.Click(ElementType.Name, "cbInspL3");
            SeleniumSetMethods.EnterText(ElementType.Name, "abCommL", "test comments limit to max < 60 characters. limit is 12 END.");
            SeleniumSetMethods.EnterText(ElementType.Name, "abObo", "Functional");
            SeleniumSetMethods.EnterText(ElementType.Name, "abInflu", "positive influence");
            SeleniumSetMethods.EnterText(ElementType.Name, "abResale", "resale problem");
            SeleniumSetMethods.EnterText(ElementType.Name, "abFinan", "all allowed");
            SeleniumSetMethods.Click(ElementType.Name, "cbFirst");
            SeleniumSetMethods.Click(ElementType.Name, "cbInvest");
            SeleniumSetMethods.Click(ElementType.Name, "cbOther");
            SeleniumSetMethods.EnterText(ElementType.Name, "abFinancier", "all");
            SeleniumSetMethods.EnterText(ElementType.Name, "abMktStrategy", "both will work");
            SeleniumSetMethods.Click(ElementType.Name, "abViewed");
            SeleniumSetMethods.Click(ElementType.Id, "btnSaveWork");
            SeleniumSetMethods.Click(ElementType.XPath, "//table[@id='tabBorder2']/tbody/tr[22]/td/table/tbody/tr/td[2]/a/img");
            SeleniumSetMethods.EnterText(ElementType.Name, "abmv90asis", "500000");
            SeleniumSetMethods.EnterText(ElementType.Name, "abmv90rep", "550000");
            SeleniumSetMethods.EnterText(ElementType.Name, "txtmvcomments", "as is comments");
            SeleniumSetMethods.EnterText(ElementType.Name, "abslp90asis", "400000");
            SeleniumSetMethods.EnterText(ElementType.Name, "abslp90rep", "450000");
            SeleniumSetMethods.EnterText(ElementType.Name, "txtslpcomments", "comments");
            SeleniumSetMethods.EnterText(ElementType.Name, "abEstLandValue", "250000");
            SeleniumSetMethods.EnterText(ElementType.Name, "abHoName", "test association");
            SeleniumSetMethods.EnterText(ElementType.Name, "abHoAcsz", "123 main street, lake forest , CA 92630");
            SeleniumSetMethods.EnterText(ElementType.Name, "abHoPhone", "7418529966");
            SeleniumSetMethods.EnterText(ElementType.Name, "abHoDues", "250");
            SeleniumSetMethods.EnterText(ElementType.Name, "abHoWhen", "12/01/2016");
            SeleniumSetMethods.EnterText(ElementType.Name, "abHoLast", "11/01/2016");
            SeleniumSetMethods.EnterText(ElementType.Name, "abHoDelinq", "none");
            SeleniumSetMethods.EnterText(ElementType.Name, "abHoMaint", "lawn, pool");
            SeleniumSetMethods.EnterText(ElementType.Name, "abRdesc1", "window");
            SeleniumSetMethods.EnterText(ElementType.Name, "abRcost1", "150");
            SeleniumSetMethods.EnterText(ElementType.Name, "abRdesc2", "paint");
            SeleniumSetMethods.EnterText(ElementType.Name, "abRcost2", "250");
            SeleniumSetMethods.Click(ElementType.Id, "btnSaveWorkPg2");

        }

        public static void REOChase()
        {
            //REO BPO 
            SeleniumWindowMethods.Sleep(2);
            Global.ConsoleOut("Pause Me");
            SeleniumWindowMethods.Sleep(5);
            SeleniumSetMethods.EnterText(ElementType.Name, "abMcPricePerc", "10");
            SeleniumSetMethods.EnterText(ElementType.Name, "abMcPriceMos", "12");
            SeleniumSetMethods.Click(ElementType.Name, "abMcSupply");
            SeleniumSetMethods.EnterText(ElementType.Name, "abMcOwnerPerc", "55");
            SeleniumSetMethods.EnterText(ElementType.Name, "abMcTenentPerc", "20");
            SeleniumSetMethods.EnterText(ElementType.Name, "abMcCompUnits", "6");
            SeleniumSetMethods.EnterText(ElementType.Name, "abMcBoards", "0");
            SeleniumSetMethods.EnterText(ElementType.Name, "abMkLow", "450000");
            SeleniumSetMethods.EnterText(ElementType.Name, "abMkHigh", "550000");
            SeleniumSetMethods.EnterText(ElementType.Name, "abMkTime", "35");
            SeleniumSetMethods.EnterText(ElementType.Name, "abMkOnDesc", "n/a test");
            SeleniumSetMethods.Click(ElementType.Name, "abMkUnit");
            SeleniumSetMethods.SelectDropDown(ElementType.Name, "abU1Rooms", "12");
            SeleniumSetMethods.SelectDropDown(ElementType.Name, "abU1Beds", "4");
            SeleniumSetMethods.SelectDropDown(ElementType.Name, "abU1Baths", "3.5");
            SeleniumSetMethods.SelectDropDown(ElementType.Name, "abU1Inspect", "Exterior");
            SeleniumSetMethods.EnterText(ElementType.Name, "abMkFee", "150");
            SeleniumSetMethods.Click(ElementType.Name, "abMkFeeType");
            SeleniumSetMethods.EnterText(ElementType.Name, "abMkFeeDel", "0.00");
            SeleniumSetMethods.Click(ElementType.Name, "abMkFeeIns");
            SeleniumSetMethods.EnterText(ElementType.Name, "abMkFeeOth", "test");
            SeleniumSetMethods.EnterText(ElementType.Name, "abMkAssoc", "Test HOA Association");
            SeleniumSetMethods.EnterText(ElementType.Name, "abMkAssocPh", "7418529966");
            SeleniumSetMethods.EnterText(ElementType.Name, "abAddrS1", "1");
            SeleniumSetMethods.EnterText(ElementType.Name, "abAddrS2", "2");
            SeleniumSetMethods.EnterText(ElementType.Name, "abAddrS3", "3");
            SeleniumSetMethods.SelectDropDown(ElementType.Name, "abProxS1", "1 Mile");
            SeleniumSetMethods.SelectDropDown(ElementType.Name, "abProxS2", "2 Blocks");
            SeleniumSetMethods.SelectDropDown(ElementType.Name, "abProxS3", "1 Mile");
            SeleniumSetMethods.EnterText(ElementType.Name, "abSpS1", "460000");
            SeleniumSetMethods.EnterText(ElementType.Name, "abSpS2", "470000");
            SeleniumSetMethods.EnterText(ElementType.Name, "abSpS3", "480000");
            SeleniumSetMethods.EnterText(ElementType.Name, "abSaleDtS1", "10/30/2016");
            SeleniumSetMethods.EnterText(ElementType.Name, "abSaleDtS2", "11/01/2016");
            SeleniumSetMethods.EnterText(ElementType.Name, "abSaleDtS3", "11/02/2016");
            SeleniumSetMethods.EnterText(ElementType.Name, "abDomS1", "13");
            SeleniumSetMethods.EnterText(ElementType.Name, "abDomS2", "14");
            SeleniumSetMethods.EnterText(ElementType.Name, "abDomS3", "15");
            SeleniumSetMethods.EnterText(ElementType.Name, "abConcS1", "S1 Con");
            SeleniumSetMethods.EnterText(ElementType.Name, "abConcS1a", "1");
            SeleniumSetMethods.EnterText(ElementType.Name, "abConcS2", "S#2 Con");
            SeleniumSetMethods.EnterText(ElementType.Name, "abConcS3", "S#3 Con");
            SeleniumSetMethods.EnterText(ElementType.Name, "abConcS3a", "1");
            SeleniumSetMethods.SelectDropDown(ElementType.Name, "abLoc", "Superior");
            SeleniumSetMethods.SelectDropDown(ElementType.Name, "abLocS1", "Superior");
            SeleniumSetMethods.SelectDropDown(ElementType.Name, "abLocS2", "Equal");
            SeleniumSetMethods.SelectDropDown(ElementType.Name, "abLocS3", "Inferior");
            SeleniumSetMethods.EnterText(ElementType.Name, "abRight", "Fee Simple");
            SeleniumSetMethods.EnterText(ElementType.Name, "abRightS1", "Fee Simple");
            SeleniumSetMethods.EnterText(ElementType.Name, "abRightS2", "Fee Simple");
            SeleniumSetMethods.EnterText(ElementType.Name, "abRightS3", "Fee Simple");
            SeleniumSetMethods.EnterText(ElementType.Name, "abRightS3a", "1");
            SeleniumSetMethods.EnterText(ElementType.Name, "abSite", "1");
            SeleniumSetMethods.EnterText(ElementType.Name, "abSiteS1", "1");
            SeleniumSetMethods.EnterText(ElementType.Name, "abSiteS1a", "1");
            SeleniumSetMethods.EnterText(ElementType.Name, "abSiteS2", "1");
            SeleniumSetMethods.EnterText(ElementType.Name, "abSiteS3", "1");
            SeleniumSetMethods.EnterText(ElementType.Name, "abView", "sub View");
            SeleniumSetMethods.EnterText(ElementType.Name, "abViewS1", "S#1 View");
            SeleniumSetMethods.EnterText(ElementType.Name, "abViewS2", "S#2 View");
            SeleniumSetMethods.EnterText(ElementType.Name, "abViewS3", "S#3");
            SeleniumSetMethods.EnterText(ElementType.Name, "abViewS3a", "2");
            SeleniumSetMethods.EnterText(ElementType.Name, "abDesign", "Sub Design");
            SeleniumSetMethods.EnterText(ElementType.Name, "abDesignS1", "S#1 Design");
            SeleniumSetMethods.EnterText(ElementType.Name, "abDesignS1a", "2");
            SeleniumSetMethods.EnterText(ElementType.Name, "abDesignS2", "S#2 Design");
            SeleniumSetMethods.EnterText(ElementType.Name, "abDesignS3", "S#3 Design");
            SeleniumSetMethods.EnterText(ElementType.Name, "abDesignS3a", "3");
            SeleniumSetMethods.EnterText(ElementType.Name, "abQual", "Sub Con");
            SeleniumSetMethods.EnterText(ElementType.Name, "abQualS1", "S#1 Con");
            SeleniumSetMethods.EnterText(ElementType.Name, "abQualS1a", "3");
            SeleniumSetMethods.EnterText(ElementType.Name, "abQualS2", "S#2 Con");
            SeleniumSetMethods.EnterText(ElementType.Name, "abQualS3", "S#3 Const");
            SeleniumSetMethods.EnterText(ElementType.Name, "abQualS3a", "4");
            SeleniumSetMethods.EnterText(ElementType.Name, "abAge", "10");
            SeleniumSetMethods.EnterText(ElementType.Name, "abAgeS1", "11");
            SeleniumSetMethods.EnterText(ElementType.Name, "abAgeS1a", "4");
            SeleniumSetMethods.EnterText(ElementType.Name, "abAgeS2", "12");
            SeleniumSetMethods.EnterText(ElementType.Name, "abAgeS3", "14");
            SeleniumSetMethods.EnterText(ElementType.Name, "abAgeS3a", "5");
            SeleniumSetMethods.SelectDropDown(ElementType.Name, "abCond", "Good");
            SeleniumSetMethods.SelectDropDown(ElementType.Name, "abCondS1", "Fair");
            SeleniumSetMethods.EnterText(ElementType.Name, "abCondS1a", "5");
            SeleniumSetMethods.SelectDropDown(ElementType.Name, "abCondS2", "Average");
            SeleniumSetMethods.SelectDropDown(ElementType.Name, "abCondS3", "Fair");
            SeleniumSetMethods.EnterText(ElementType.Name, "abRooms", "10");
            SeleniumSetMethods.EnterText(ElementType.Name, "abRoomsS1", "12");
            SeleniumSetMethods.EnterText(ElementType.Name, "abRoomsS2", "13");
            SeleniumSetMethods.EnterText(ElementType.Name, "abRoomsS3", "14");
            SeleniumSetMethods.EnterText(ElementType.Name, "abBeds", "5");
            SeleniumSetMethods.EnterText(ElementType.Name, "abBedsS1", "6");
            SeleniumSetMethods.EnterText(ElementType.Name, "abBedsS2", "7");
            SeleniumSetMethods.EnterText(ElementType.Name, "abBedsS3", "8");
            SeleniumSetMethods.EnterText(ElementType.Name, "abBaths", "2");
            SeleniumSetMethods.EnterText(ElementType.Name, "abBathsS2", "2.5");
            SeleniumSetMethods.EnterText(ElementType.Name, "abBathsS3", "3");
            SeleniumSetMethods.EnterText(ElementType.Name, "abGla", "1350");
            SeleniumSetMethods.EnterText(ElementType.Name, "abGlaS1", "1450");
            SeleniumSetMethods.EnterText(ElementType.Name, "abGlaS2", "1375");
            SeleniumSetMethods.EnterText(ElementType.Name, "abGlaS3", "1475");
            SeleniumSetMethods.EnterText(ElementType.Name, "abBsmt", "Sub Basement");
            SeleniumSetMethods.EnterText(ElementType.Name, "abBsmtS1", "S#1Basement");
            SeleniumSetMethods.EnterText(ElementType.Name, "abBsmtS1a", "6");
            SeleniumSetMethods.EnterText(ElementType.Name, "abBsmtS2", "S#2 Basement");
            SeleniumSetMethods.EnterText(ElementType.Name, "abBsmtS3", "S#3 Basement");
            SeleniumSetMethods.EnterText(ElementType.Name, "abBsmtS3a", "-2");
            SeleniumSetMethods.SelectDropDown(ElementType.Name, "abUtil", "Yes");
            SeleniumSetMethods.SelectDropDown(ElementType.Name, "abUtilS1", "Yes");
            SeleniumSetMethods.SelectDropDown(ElementType.Name, "abUtilS2", "Yes");
            SeleniumSetMethods.SelectDropDown(ElementType.Name, "abUtilS3", "Yes");
            SeleniumSetMethods.EnterText(ElementType.Name, "abHeat", "Sub Heat");
            SeleniumSetMethods.EnterText(ElementType.Name, "abHeatS1", "S#1 Heat");
            SeleniumSetMethods.EnterText(ElementType.Name, "abHeatS1a", "7");
            SeleniumSetMethods.EnterText(ElementType.Name, "abHeatS2", "S#2 Heat");
            SeleniumSetMethods.EnterText(ElementType.Name, "abHeatS3", "S#3 Heat");
            SeleniumSetMethods.EnterText(ElementType.Name, "abEnergy", "Sub Energy");
            SeleniumSetMethods.EnterText(ElementType.Name, "abEnergyS1", "S#1 Energy");
            SeleniumSetMethods.EnterText(ElementType.Name, "abEnergyS2", "S#2 Energy");
            SeleniumSetMethods.EnterText(ElementType.Name, "abEnergyS3", "S#3 Energy");
            SeleniumSetMethods.SelectDropDown(ElementType.Name, "abGarage", "None");
            SeleniumSetMethods.SelectDropDown(ElementType.Name, "abGarageS1", "None");
            SeleniumSetMethods.SelectDropDown(ElementType.Name, "abGarageS1", "CarPort");
            SeleniumSetMethods.EnterText(ElementType.Name, "abGarageS1a", "2");
            SeleniumSetMethods.SelectDropDown(ElementType.Name, "abGarageS2", "None");
            SeleniumSetMethods.SelectDropDown(ElementType.Name, "abGarageS2", "CarPort");
            SeleniumSetMethods.SelectDropDown(ElementType.Name, "abGarageS2", "1CarAtt");
            SeleniumSetMethods.SelectDropDown(ElementType.Name, "abGarageS3", "None");
            SeleniumSetMethods.SelectDropDown(ElementType.Name, "abGarageS3", "CarPort");
            SeleniumSetMethods.SelectDropDown(ElementType.Name, "abGarageS3", "1CarAtt");
            SeleniumSetMethods.SelectDropDown(ElementType.Name, "abGarageS3", "2CarAtt");
            SeleniumSetMethods.EnterText(ElementType.Name, "abPorch", "Sub Porch");
            SeleniumSetMethods.EnterText(ElementType.Name, "abPorchS1", "S#1 porch");
            SeleniumSetMethods.EnterText(ElementType.Name, "abPorchS2", "s#2 Porch");
            SeleniumSetMethods.EnterText(ElementType.Name, "abPorchS3", "S#3 Porch");
            SeleniumSetMethods.EnterText(ElementType.Name, "abPool", "Sub Fence");
            SeleniumSetMethods.EnterText(ElementType.Name, "abPoolS1", "S#1 Fence");
            SeleniumSetMethods.EnterText(ElementType.Name, "abPoolS2", "S#3 Fence");
            SeleniumSetMethods.EnterText(ElementType.Name, "abPoolS3", "s#3 Fence");
            SeleniumSetMethods.EnterText(ElementType.Name, "abOther", "Sub other");
            SeleniumSetMethods.EnterText(ElementType.Name, "abOtherS1", "s1 other");
            SeleniumSetMethods.EnterText(ElementType.Name, "abOtherS2", "s2 other");
            SeleniumSetMethods.EnterText(ElementType.Name, "abOtherS2a", "3");
            SeleniumSetMethods.EnterText(ElementType.Name, "abOtherS3", "s3 other");
            SeleniumSetMethods.Click(ElementType.Id, "btnSaveWork");
            SeleniumSetMethods.Click(ElementType.XPath, "//table[@id='tabBorder2']/tbody/tr[9]/td/table/tbody/tr/td[2]/a/img");
            SeleniumSetMethods.Click(ElementType.Name, "aboccupancy_status");
            SeleniumSetMethods.Click(ElementType.Name, "abMkStrat");
            SeleniumSetMethods.Click(ElementType.Name, "abMkBuyer");
            SeleniumSetMethods.EnterText(ElementType.Name, "abRpDesc1", "Paint");
            SeleniumSetMethods.EnterText(ElementType.Name, "abRpAmt1", "25");
            SeleniumSetMethods.EnterText(ElementType.Name, "abRpDesc3", "Cleaning");
            SeleniumSetMethods.EnterText(ElementType.Name, "abRpAmt3", "50");
            SeleniumSetMethods.EnterText(ElementType.Name, "abAddrL1", "4");
            SeleniumSetMethods.EnterText(ElementType.Name, "abAddrL2", "5");
            SeleniumSetMethods.EnterText(ElementType.Name, "abAddrL3", "6");
            SeleniumSetMethods.SelectDropDown(ElementType.Name, "abProxL1", "1 Block");
            SeleniumSetMethods.SelectDropDown(ElementType.Name, "abProxL2", "1 Block");
            SeleniumSetMethods.SelectDropDown(ElementType.Name, "abProxL2", "2 Blocks");
            SeleniumSetMethods.SelectDropDown(ElementType.Name, "abProxL3", "2 Miles");
            SeleniumSetMethods.EnterText(ElementType.Name, "abSpL1", "425000");
            SeleniumSetMethods.EnterText(ElementType.Name, "abSpL2", "435000");
            SeleniumSetMethods.EnterText(ElementType.Name, "abSpL3", "445000");
            SeleniumSetMethods.SelectDropDown(ElementType.Name, "abSrce", "MLS");
            SeleniumSetMethods.SelectDropDown(ElementType.Name, "abSrceL1", "TaxRecords");
            SeleniumSetMethods.SelectDropDown(ElementType.Name, "abSrceL2", "MLS");
            SeleniumSetMethods.SelectDropDown(ElementType.Name, "abSrceL3", "MLS");
            SeleniumSetMethods.EnterText(ElementType.Name, "abConcL1", "c1 finance");
            SeleniumSetMethods.EnterText(ElementType.Name, "abConcL2", "c2 finanace");
            SeleniumSetMethods.EnterText(ElementType.Name, "abConcL3", "c3 finance");
            SeleniumSetMethods.EnterText(ElementType.Name, "abDomDt", "30");
            SeleniumSetMethods.EnterText(ElementType.Name, "abDomL1", "35");
            SeleniumSetMethods.EnterText(ElementType.Name, "abDomL2", "40");
            SeleniumSetMethods.EnterText(ElementType.Name, "abDomL3", "45");
            SeleniumSetMethods.SelectDropDown(ElementType.Name, "abLocL1", "Equal");
            SeleniumSetMethods.SelectDropDown(ElementType.Name, "abLocL2", "Inferior");
            SeleniumSetMethods.SelectDropDown(ElementType.Name, "abLocL3", "Superior");
            SeleniumSetMethods.EnterText(ElementType.Name, "abRightL1", "Fee Simple");
            SeleniumSetMethods.EnterText(ElementType.Name, "abRightL2", "Fee Simple");
            SeleniumSetMethods.EnterText(ElementType.Name, "abRightL3", "Fee Simple");
            SeleniumSetMethods.EnterText(ElementType.Name, "abSiteL1", "2");
            SeleniumSetMethods.EnterText(ElementType.Name, "abSiteL1a", "10");
            SeleniumSetMethods.EnterText(ElementType.Name, "abSiteL2", "1");
            SeleniumSetMethods.EnterText(ElementType.Name, "abSiteL3", "1");
            SeleniumSetMethods.EnterText(ElementType.Name, "abSiteL3a", "-10");
            SeleniumSetMethods.EnterText(ElementType.Name, "abViewL1", "c1 view");
            SeleniumSetMethods.EnterText(ElementType.Name, "abViewL2", "c2 view");
            SeleniumSetMethods.EnterText(ElementType.Name, "abViewL3", "c3 view");
            SeleniumSetMethods.EnterText(ElementType.Name, "abDesign", "SUB Design");
            SeleniumSetMethods.EnterText(ElementType.Name, "abDesignL1", "C1 Design");
            SeleniumSetMethods.EnterText(ElementType.Name, "abDesignL2", "C2 Design");
            SeleniumSetMethods.EnterText(ElementType.Name, "abDesignL3", "C3 design");
            SeleniumSetMethods.EnterText(ElementType.Name, "abQual", "Sub Const");
            SeleniumSetMethods.EnterText(ElementType.Name, "abQualL1", "c1 Const");
            SeleniumSetMethods.EnterText(ElementType.Name, "abQualL2", "C2 Const");
            SeleniumSetMethods.EnterText(ElementType.Name, "abQualL3", "C3 const");
            SeleniumSetMethods.EnterText(ElementType.Name, "abAgeL1", "15");
            SeleniumSetMethods.EnterText(ElementType.Name, "abAgeL1a", "-10");
            SeleniumSetMethods.EnterText(ElementType.Name, "abAgeL2", "10");
            SeleniumSetMethods.EnterText(ElementType.Name, "abAgeL3", "10");
            SeleniumSetMethods.EnterText(ElementType.Name, "abAgeL3a", "10");
            SeleniumSetMethods.SelectDropDown(ElementType.Name, "abCondL1", "Average");
            SeleniumSetMethods.SelectDropDown(ElementType.Name, "abCondL2", "Average");
            SeleniumSetMethods.SelectDropDown(ElementType.Name, "abCondL3", "Fair");
            SeleniumSetMethods.EnterText(ElementType.Name, "abRoomsL1", "11");
            SeleniumSetMethods.EnterText(ElementType.Name, "abRoomsL2", "12");
            SeleniumSetMethods.EnterText(ElementType.Name, "abRoomsL3", "12");
            SeleniumSetMethods.EnterText(ElementType.Name, "abBedsL1", "6");
            SeleniumSetMethods.EnterText(ElementType.Name, "abBedsL2", "7");
            SeleniumSetMethods.EnterText(ElementType.Name, "abBedsL3", "6");
            SeleniumSetMethods.EnterText(ElementType.Name, "abBathsL1", "3");
            SeleniumSetMethods.EnterText(ElementType.Name, "abBathsL2", "2.5");
            SeleniumSetMethods.EnterText(ElementType.Name, "abBathsL3", "3");
            SeleniumSetMethods.EnterText(ElementType.Name, "abGlaL1", "1450");
            SeleniumSetMethods.EnterText(ElementType.Name, "abGlaL2", "1550");
            SeleniumSetMethods.EnterText(ElementType.Name, "abGlaL3", "1650");
            SeleniumSetMethods.EnterText(ElementType.Name, "abBsmtL1", "C1 Basement");
            SeleniumSetMethods.EnterText(ElementType.Name, "abBsmtL2", "c2 basement");
            SeleniumSetMethods.EnterText(ElementType.Name, "abBsmtL3", "c3 basement");
            SeleniumSetMethods.SelectDropDown(ElementType.Name, "abUtilL1", "No");
            SeleniumSetMethods.SelectDropDown(ElementType.Name, "abUtilL2", "Yes");
            SeleniumSetMethods.SelectDropDown(ElementType.Name, "abUtilL3", "Yes");
            SeleniumSetMethods.EnterText(ElementType.Name, "abHeatL1", "c1 heat");
            SeleniumSetMethods.EnterText(ElementType.Name, "abHeatL2", "C2 heat");
            SeleniumSetMethods.EnterText(ElementType.Name, "abHeatL3", "c3 heat");
            SeleniumSetMethods.EnterText(ElementType.Name, "abEnergyL1", "c1 Energy");
            SeleniumSetMethods.EnterText(ElementType.Name, "abEnergyL2", "c2 Energy");
            SeleniumSetMethods.EnterText(ElementType.Name, "abEnergyL3", "c3 energy");
            SeleniumSetMethods.SelectDropDown(ElementType.Name, "abGarageL1", "CarPort");
            SeleniumSetMethods.SelectDropDown(ElementType.Name, "abGarageL2", "2CarAtt");
            SeleniumSetMethods.SelectDropDown(ElementType.Name, "abGarageL3", "4CarAtt");
            SeleniumSetMethods.EnterText(ElementType.Name, "abPorchL1", "C1 Porch");
            SeleniumSetMethods.EnterText(ElementType.Name, "abPorchL2", "c2 porch");
            SeleniumSetMethods.EnterText(ElementType.Name, "abPorchL3", "c3 porch");
            SeleniumSetMethods.EnterText(ElementType.Name, "abPoolL1", "c1 fence");
            SeleniumSetMethods.EnterText(ElementType.Name, "abPoolL2", "c2 fence");
            SeleniumSetMethods.EnterText(ElementType.Name, "abPoolL3", "c3 fence");
            SeleniumSetMethods.EnterText(ElementType.Name, "abOtherL1", "c1 other");
            SeleniumSetMethods.EnterText(ElementType.Name, "abOtherL2", "c2 other");
            SeleniumSetMethods.EnterText(ElementType.Name, "abOtherL3", "c3 other");
            SeleniumSetMethods.EnterText(ElementType.Name, "abMvAsIs", "550000");
            SeleniumSetMethods.EnterText(ElementType.Name, "abMvAsIsSlp", "511111");
            SeleniumSetMethods.EnterText(ElementType.Name, "abMvAsIs30Day", "522222");
            SeleniumSetMethods.EnterText(ElementType.Name, "abMvRep", "575000");
            SeleniumSetMethods.EnterText(ElementType.Name, "abMvRepSlp", "575111");
            SeleniumSetMethods.EnterText(ElementType.Name, "abMvRep30Day", "575222");
            SeleniumSetMethods.EnterText(ElementType.Name, "abLastSaleAmt", "450000");
            SeleniumSetMethods.EnterText(ElementType.Name, "abLastSaleDate", "11/10/2006");
            SeleniumSetMethods.EnterText(ElementType.Id, "txtosAgentNote", "test");
            SeleniumSetMethods.Click(ElementType.Id, "btnSaveWorkPg2");
        }

    }

}