using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Selenium3
{
    class FMBBPO
    {
        public static void FMB()
        {
            SeleniumSetMethods.Click(ElementType.Id, "Subject_InspectionDate");
            SeleniumSetMethods.Click(ElementType.XPath, "(//button[@type='button'])[2]");
            SeleniumSetMethods.EnterText(ElementType.Id, "Subject_AssetContact", "Asset Contact");
            SeleniumSetMethods.EnterText(ElementType.Id, "Subject_ParcelNumber", "123");
            SeleniumSetMethods.EnterText(ElementType.Id, "BpoBrokerDistance", "1");
            SeleniumSetMethods.EnterText(ElementType.Id, "BpoBrokerLicenseNumber", "65465422");
            SeleniumSetMethods.EnterText(ElementType.Id, "BpoBrokerYearsExperience", "12");
            SeleniumSetMethods.Click(ElementType.Id, "Marketing_MarketConditions_1");
            SeleniumSetMethods.Click(ElementType.Id, "Marketing_EmploymentConditions_1");
            SeleniumSetMethods.Click(ElementType.Id, "Marketing_MarketPriceStability_2");
            SeleniumSetMethods.Wait(ElementType.Id, "SubjectMarketing_RecomendedStrategy_0");
            SeleniumSetMethods.Click(ElementType.Id, "SubjectMarketing_RecomendedStrategy_0");
            SeleniumSetMethods.Click(ElementType.Id, "SubjectMarketing_MostLikelyBuyerType_0");
            SeleniumSetMethods.Click(ElementType.Id, "SubjectMarketing_OccupancyStrategy_0");
            SeleniumSetMethods.Click(ElementType.Id, "SubjectMarketing_IsSubjectListed_0");
            SeleniumSetMethods.Click(ElementType.Id, "Marketing_HasEnvironmentalConcerns_1");
            SeleniumSetMethods.EnterText(ElementType.Id, "Marketing_MarketPriceStabilityPercent", "10");
            SeleniumSetMethods.EnterText(ElementType.Id, "Marketing_MarketPriceStabilityMonths", "10");
            SeleniumSetMethods.Click(ElementType.Id, "Marketing_ComparableSupply_1");
            SeleniumSetMethods.EnterText(ElementType.Id, "Marketing_OwnerPercentage", "10");
            SeleniumSetMethods.EnterText(ElementType.Id, "Marketing_TenantPercentage", "20");
            SeleniumSetMethods.EnterText(ElementType.Id, "Marketing_ComparableListingsCount", "3");
            SeleniumSetMethods.EnterText(ElementType.Id, "Marketing_ReoListingsCount", "3");
            SeleniumSetMethods.EnterText(ElementType.Id, "Marketing_BoardHomesCount", "3");
            SeleniumSetMethods.EnterText(ElementType.Id, "Marketing_NeighborhoodBoundary", "qa test");
            SeleniumSetMethods.EnterText(ElementType.Id, "Marketing_SalesLow", "375000");
            SeleniumSetMethods.EnterText(ElementType.Id, "Marketing_SalesHigh", "425000");
            SeleniumSetMethods.EnterText(ElementType.Id, "Marketing_TotalSales", "3");
            SeleniumSetMethods.EnterText(ElementType.Id, "Marketing_ListingsLow", "360000");
            SeleniumSetMethods.EnterText(ElementType.Id, "Marketing_ListingsHigh", "430000");
            SeleniumSetMethods.EnterText(ElementType.Id, "Marketing_TotalListings", "3");
            SeleniumSetMethods.Click(ElementType.Id, "SubjectMarketing_SubjectImprovementRating_1");
            SeleniumSetMethods.EnterText(ElementType.Id, "Marketing_MarketingDays", "8");
            SeleniumSetMethods.Click(ElementType.XPath, "//section[@id='subjectMarketability']/div[5]");
            SeleniumSetMethods.EnterText(ElementType.Id, "Marketing_EnvironmentalConcerns", "qa test");
            SeleniumSetMethods.Click(ElementType.Id, "SubjectMarketing_HasAllFinancingAvailable_0");
            SeleniumSetMethods.EnterText(ElementType.Id, "SubjectMarketing_HasAllFinancingAvailableDesc", "qa test");
            SeleniumSetMethods.Click(ElementType.Id, "SubjectMarketing_IsSubjectListedPast12Mo_1");
            SeleniumSetMethods.EnterText(ElementType.Id, "SubjectMarketing_SubjectPast12MoListPrice", "475000");
            SeleniumSetMethods.EnterText(ElementType.Id, "SubjectMarketing_SubjectListPrice", "460000");
            SeleniumSetMethods.Click(ElementType.Id, "SubjectMarketing_SubjectListDate");
            SeleniumSetMethods.Click(ElementType.LinkText, "1");
            SeleniumSetMethods.EnterText(ElementType.Id, "SubjectMarketing_SubjectListDate", "07/03/2015");
            SeleniumSetMethods.EnterText(ElementType.Id, "SubjectMarketing_ListingBrokerName", "qa test");
            SeleniumSetMethods.EnterText(ElementType.Id, "SubjectMarketing_ListingFirmName", "qa test");
            SeleniumSetMethods.EnterText(ElementType.Id, "SubjectMarketing_ListingBrokerPhone", "1234567891");
            SeleniumSetMethods.EnterText(ElementType.Id, "SubjectMarketing_SubjectDom", "10");
            SeleniumSetMethods.EnterText(ElementType.Id, "SubjectMarketing_SubjectStartingListPrice", "415000");
            SeleniumSetMethods.EnterText(ElementType.Id, "SubjectMarketing_SubjectListPriceReduction1Dom", "1");
            SeleniumSetMethods.EnterText(ElementType.Id, "SubjectMarketing_SubjectListPriceReduction2Dom", "1");
            SeleniumSetMethods.EnterText(ElementType.Id, "SubjectMarketing_SubjectListPriceReduction3Dom", "1");
            SeleniumSetMethods.EnterText(ElementType.Id, "SubjectMarketing_SubjectReduction1ListPrice", "410000");
            SeleniumSetMethods.EnterText(ElementType.Id, "SubjectMarketing_SubjectReduction2ListPrice", "411111");
            SeleniumSetMethods.EnterText(ElementType.Id, "SubjectMarketing_SubjectReduction3ListPrice", "412222");
            SeleniumSetMethods.EnterText(ElementType.Id, "SubjectMarketing_SubjectWhyNotSell", "qa test");
            SeleniumSetMethods.Click(ElementType.Id, "SubjectMarketing_SubjectPropertyType_2");
            SeleniumSetMethods.EnterText(ElementType.Id, "SubjectMarketing_SubjectLastSalePrice", "350000");
            SeleniumSetMethods.Click(ElementType.Id, "SubjectMarketing_SubjectLastSaleDate");
            SeleniumSetMethods.Click(ElementType.LinkText, "1");
            SeleniumSetMethods.EnterText(ElementType.Id, "SubjectMarketing_SubjectLastSalePrice2", "11111");
            SeleniumSetMethods.Click(ElementType.Id, "SubjectMarketing_SubjectLastSaleDate2");
            SeleniumSetMethods.Click(ElementType.LinkText, "1");
            SeleniumSetMethods.EnterText(ElementType.Id, "SubjectMarketing_LegalProjectName", "qa test");
            SeleniumSetMethods.EnterText(ElementType.Id, "SubjectMarketing_LegalProjectUnits", "1");
            SeleniumSetMethods.Click(ElementType.Id, "SubjectMarketing_LegalAction_1");
            SeleniumSetMethods.SelectDropDown(ElementType.Id, "SubjectMarketing_MandatoryAssociation", "Yes");
            SeleniumSetMethods.EnterText(ElementType.Id, "SubjectMarketing_HoaFee", "123");
            SeleniumSetMethods.SelectDropDown(ElementType.Id, "SubjectMarketing_HoaBillingCycle", "Monthly");
            SeleniumSetMethods.SelectDropDown(ElementType.Id, "SubjectMarketing_IsHoaFeesCurrent", "Yes");
            SeleniumSetMethods.EnterText(ElementType.Id, "SubjectMarketing_HoaFeeDelinquentAmount", "123");
            SeleniumSetMethods.Click(ElementType.Id, "SubjectMarketing_HoaFeeInsurance");
            SeleniumSetMethods.Click(ElementType.Id, "SubjectMarketing_HoaFeeLandscape");
            SeleniumSetMethods.Click(ElementType.Id, "SubjectMarketing_HoaFeePool");
            SeleniumSetMethods.Click(ElementType.Id, "SubjectMarketing_HoaFeeTennis");
            SeleniumSetMethods.EnterText(ElementType.Id, "SubjectMarketing_HoaFeeOther", "qa test");
            SeleniumSetMethods.EnterText(ElementType.Id, "SubjectMarketing_HoaCompany", "qa test");
            SeleniumSetMethods.EnterText(ElementType.Id, "SubjectMarketing_HoaContactName", "Contact Name");
            SeleniumSetMethods.EnterText(ElementType.Id, "SubjectMarketing_HoaPhone", "1234567891");
            SeleniumSetMethods.Click(ElementType.Id, "SubjectMarketing_SubjectOccupancyStatus_0");
            SeleniumSetMethods.Click(ElementType.Id, "SubjectMarketing_OwnershipStatus_0");
            SeleniumSetMethods.EnterText(ElementType.Id, "SaleComps_0__StreetAddress", "1");
            SeleniumSetMethods.EnterText(ElementType.Id, "SaleComps_1__StreetAddress", "2");
            SeleniumSetMethods.EnterText(ElementType.Id, "SaleComps_2__StreetAddress", "3");
            SeleniumSetMethods.EnterText(ElementType.Id, "SaleComps_0__City", "Irvine");
            SeleniumSetMethods.EnterText(ElementType.Id, "SaleComps_1__City", "Irvine");
            SeleniumSetMethods.EnterText(ElementType.Id, "SaleComps_2__City", "Irvine");
            SeleniumSetMethods.SelectDropDown(ElementType.Id, "SaleComps_0__State", "Colorado");
            SeleniumSetMethods.SelectDropDown(ElementType.Id, "SaleComps_0__State", "California");
            SeleniumSetMethods.SelectDropDown(ElementType.Id, "SaleComps_1__State", "California");
            SeleniumSetMethods.SelectDropDown(ElementType.Id, "SaleComps_2__State", "California");
            SeleniumSetMethods.EnterText(ElementType.Id, "SaleComps_0__PostalCode", "92620");
            SeleniumSetMethods.EnterText(ElementType.Id, "SaleComps_1__PostalCode", "92620");
            SeleniumSetMethods.EnterText(ElementType.Id, "SaleComps_2__PostalCode", "92620");
            SeleniumSetMethods.EnterText(ElementType.Id, "SaleComps_0__ProximityDistance", "1");
            SeleniumSetMethods.EnterText(ElementType.Id, "SaleComps_1__ProximityDistance", "1");
            SeleniumSetMethods.EnterText(ElementType.Id, "SaleComps_2__ProximityDistance", "1");
            SeleniumSetMethods.EnterText(ElementType.Id, "SaleComps_0__SalePrice", "415000");
            SeleniumSetMethods.EnterText(ElementType.Id, "SaleComps_1__SalePrice", "420000");
            SeleniumSetMethods.EnterText(ElementType.Id, "SaleComps_2__SalePrice", "425000");
            SeleniumSetMethods.SelectDropDown(ElementType.Id, "SaleComps_0__SaleType", "Traditional");
            SeleniumSetMethods.SelectDropDown(ElementType.Id, "SaleComps_1__SaleType", "Traditional");
            SeleniumSetMethods.SelectDropDown(ElementType.Id, "SaleComps_2__SaleType", "Traditional");
            SeleniumSetMethods.EnterText(ElementType.Id, "SaleComps_0__ListPriceAtSale", "410000");
            SeleniumSetMethods.EnterText(ElementType.Id, "SaleComps_1__ListPriceAtSale", "41000");
            SeleniumSetMethods.EnterText(ElementType.Id, "SaleComps_2__ListPriceAtSale", "410000");
            SeleniumSetMethods.EnterText(ElementType.Id, "SaleComps_0__PriceReductionCount", "0");
            SeleniumSetMethods.EnterText(ElementType.Id, "SaleComps_1__PriceReductionCount", "0");
            SeleniumSetMethods.EnterText(ElementType.Id, "SaleComps_2__PriceReductionCount", "0");
            SeleniumSetMethods.SelectDropDown(ElementType.Id, "Subject_DataSource", "MLS");
            SeleniumSetMethods.SelectDropDown(ElementType.Id, "SaleComps_0__DataSource", "MLS");
            SeleniumSetMethods.SelectDropDown(ElementType.Id, "SaleComps_1__DataSource", "MLS");
            SeleniumSetMethods.SelectDropDown(ElementType.Id, "SaleComps_2__DataSource", "MLS");
            SeleniumSetMethods.Click(ElementType.Id, "SaleComps_0__SaleDate");
            SeleniumSetMethods.Click(ElementType.XPath, "(//button[@type='button'])[2]");
            SeleniumSetMethods.Click(ElementType.Id, "SaleComps_1__SaleDate");
            SeleniumSetMethods.Click(ElementType.XPath, "(//button[@type='button'])[2]");
            SeleniumSetMethods.Click(ElementType.Id, "SaleComps_2__SaleDate");
            SeleniumSetMethods.Click(ElementType.XPath, "(//button[@type='button'])[2]");
            SeleniumSetMethods.EnterText(ElementType.Id, "SaleComps_0__Dom", "10");
            SeleniumSetMethods.EnterText(ElementType.Id, "SaleComps_1__Dom", "10");
            SeleniumSetMethods.EnterText(ElementType.Id, "SaleComps_2__Dom", "10");
            SeleniumSetMethods.EnterText(ElementType.Id, "SaleComps_0__Concessions", "0");
            SeleniumSetMethods.EnterText(ElementType.Id, "SaleComps_0__ConcessionsAdj", "0");
            SeleniumSetMethods.EnterText(ElementType.Id, "SaleComps_1__Concessions", "0");
            SeleniumSetMethods.EnterText(ElementType.Id, "SaleComps_1__ConcessionsAdj", "0");
            SeleniumSetMethods.EnterText(ElementType.Id, "SaleComps_2__Concessions", "0");
            SeleniumSetMethods.EnterText(ElementType.Id, "SaleComps_2__ConcessionsAdj", "0");
            SeleniumSetMethods.EnterText(ElementType.Id, "SaleComps_0__ConcessionsAdj", "1");
            SeleniumSetMethods.EnterText(ElementType.Id, "SaleComps_0__LocationTypeAdj", "2");
            SeleniumSetMethods.EnterText(ElementType.Id, "SaleComps_0__FeeSimpleAdj", "3");
            SeleniumSetMethods.EnterText(ElementType.Id, "SaleComps_0__LotSizeAdj", "4");
            SeleniumSetMethods.EnterText(ElementType.Id, "SaleComps_0__UnitsAdj", "5");
            SeleniumSetMethods.EnterText(ElementType.Id, "SaleComps_0__ViewAdj", "6");
            SeleniumSetMethods.EnterText(ElementType.Id, "SaleComps_0__AppealAdj", "7");
            SeleniumSetMethods.EnterText(ElementType.Id, "SaleComps_0__YearBuiltAdj", "8");
            SeleniumSetMethods.EnterText(ElementType.Id, "SaleComps_0__ConditionAdj", "9");
            SeleniumSetMethods.EnterText(ElementType.Id, "SaleComps_0__RoomsAdj", "10");
            SeleniumSetMethods.EnterText(ElementType.Id, "SaleComps_0__GrossLivingAreaAdj", "11");
            SeleniumSetMethods.EnterText(ElementType.Id, "SaleComps_0__BsmtAdj", "12");
            SeleniumSetMethods.EnterText(ElementType.Id, "SaleComps_0__HeatingCoolingAdj", "13");
            SeleniumSetMethods.EnterText(ElementType.Id, "SaleComps_0__GarageAdj", "14");
            SeleniumSetMethods.EnterText(ElementType.Id, "SaleComps_0__ExtrasAdj", "15");
            SeleniumSetMethods.EnterText(ElementType.Id, "SaleComps_0__FunctionalUtilityAdj", "16");
            SeleniumSetMethods.SelectDropDown(ElementType.Id, "Subject_LocationType", "Urban");
            SeleniumSetMethods.SelectDropDown(ElementType.Id, "SaleComps_0__LocationType", "Urban");
            SeleniumSetMethods.EnterText(ElementType.Id, "SaleComps_0__LocationTypeAdj", "0");
            SeleniumSetMethods.SelectDropDown(ElementType.Id, "SaleComps_1__LocationType", "Urban");
            SeleniumSetMethods.EnterText(ElementType.Id, "SaleComps_1__LocationTypeAdj", "0");
            SeleniumSetMethods.SelectDropDown(ElementType.Id, "SaleComps_2__LocationType", "Urban");
            SeleniumSetMethods.EnterText(ElementType.Id, "SaleComps_2__LocationTypeAdj", "0");
            SeleniumSetMethods.SelectDropDown(ElementType.Id, "Subject_FeeSimple", "Lease Hold");
            SeleniumSetMethods.SelectDropDown(ElementType.Id, "SaleComps_0__FeeSimple", "Lease Hold");
            SeleniumSetMethods.EnterText(ElementType.Id, "SaleComps_0__FeeSimpleAdj", "0");
            SeleniumSetMethods.SelectDropDown(ElementType.Id, "SaleComps_1__FeeSimple", "Lease Hold");
            SeleniumSetMethods.EnterText(ElementType.Id, "SaleComps_1__FeeSimpleAdj", "0");
            SeleniumSetMethods.SelectDropDown(ElementType.Id, "SaleComps_2__FeeSimple", "Lease Hold");
            SeleniumSetMethods.EnterText(ElementType.Id, "SaleComps_2__FeeSimpleAdj", "0");
            SeleniumSetMethods.SelectDropDown(ElementType.Id, "LotSizeUnitType", "Sq. Ft.");
            SeleniumSetMethods.EnterText(ElementType.Id, "Subject_LotSize", "1000");
            SeleniumSetMethods.EnterText(ElementType.Id, "SaleComps_0__LotSize", "1000");
            SeleniumSetMethods.EnterText(ElementType.Id, "SaleComps_0__LotSizeAdj", "0");
            SeleniumSetMethods.EnterText(ElementType.Id, "SaleComps_1__LotSize", "1000");
            SeleniumSetMethods.EnterText(ElementType.Id, "SaleComps_1__LotSizeAdj", "0");
            SeleniumSetMethods.EnterText(ElementType.Id, "SaleComps_2__LotSize", "1000");
            SeleniumSetMethods.EnterText(ElementType.Id, "SaleComps_2__LotSizeAdj", "0");
            SeleniumSetMethods.EnterText(ElementType.Id, "Subject_Units", "1");
            SeleniumSetMethods.EnterText(ElementType.Id, "SaleComps_0__Units", "1");
            SeleniumSetMethods.EnterText(ElementType.Id, "SaleComps_0__UnitsAdj", "0");
            SeleniumSetMethods.EnterText(ElementType.Id, "SaleComps_1__Units", "1");
            SeleniumSetMethods.EnterText(ElementType.Id, "SaleComps_1__UnitsAdj", "0");
            SeleniumSetMethods.EnterText(ElementType.Id, "SaleComps_2__Units", "1");
            SeleniumSetMethods.EnterText(ElementType.Id, "SaleComps_2__UnitsAdj", "0");
            SeleniumSetMethods.EnterText(ElementType.Id, "Subject_ViewDescription", "1");
            SeleniumSetMethods.EnterText(ElementType.Id, "SaleComps_0__ViewDescription", "1");
            SeleniumSetMethods.EnterText(ElementType.Id, "SaleComps_0__ViewAdj", "0");
            SeleniumSetMethods.EnterText(ElementType.Id, "SaleComps_1__ViewDescription", "1");
            SeleniumSetMethods.EnterText(ElementType.Id, "SaleComps_1__ViewAdj", "0");
            SeleniumSetMethods.EnterText(ElementType.Id, "SaleComps_2__ViewDescription", "1");
            SeleniumSetMethods.EnterText(ElementType.Id, "SaleComps_2__ViewAdj", "0");
            SeleniumSetMethods.SelectDropDown(ElementType.Id, "Subject_Appeal", "Poor");
            SeleniumSetMethods.SelectDropDown(ElementType.Id, "SaleComps_0__Appeal", "Poor");
            SeleniumSetMethods.EnterText(ElementType.Id, "SaleComps_0__AppealAdj", "0");
            SeleniumSetMethods.SelectDropDown(ElementType.Id, "SaleComps_1__Appeal", "Poor");
            SeleniumSetMethods.EnterText(ElementType.Id, "SaleComps_1__AppealAdj", "0");
            SeleniumSetMethods.SelectDropDown(ElementType.Id, "SaleComps_2__Appeal", "Poor");
            SeleniumSetMethods.EnterText(ElementType.Id, "SaleComps_2__AppealAdj", "0");
            SeleniumSetMethods.EnterText(ElementType.Id, "Subject_YearBuilt", "2000");
            SeleniumSetMethods.EnterText(ElementType.Id, "SaleComps_0__YearBuilt", "2000");
            SeleniumSetMethods.EnterText(ElementType.Id, "SaleComps_0__YearBuiltAdj", "0");
            SeleniumSetMethods.EnterText(ElementType.Id, "SaleComps_1__YearBuilt", "2000");
            SeleniumSetMethods.EnterText(ElementType.Id, "SaleComps_1__YearBuiltAdj", "0");
            SeleniumSetMethods.EnterText(ElementType.Id, "SaleComps_2__YearBuilt", "2000");
            SeleniumSetMethods.EnterText(ElementType.Id, "SaleComps_2__YearBuiltAdj", "0");
            SeleniumSetMethods.SelectDropDown(ElementType.Id, "Subject_Condition", "Poor");
            SeleniumSetMethods.SelectDropDown(ElementType.Id, "SaleComps_0__Condition", "Poor");
            SeleniumSetMethods.EnterText(ElementType.Id, "SaleComps_0__ConditionAdj", "0");
            SeleniumSetMethods.SelectDropDown(ElementType.Id, "SaleComps_1__Condition", "Poor");
            SeleniumSetMethods.EnterText(ElementType.Id, "SaleComps_1__ConditionAdj", "0");
            SeleniumSetMethods.SelectDropDown(ElementType.Id, "SaleComps_2__Condition", "Poor");
            SeleniumSetMethods.EnterText(ElementType.Id, "SaleComps_2__ConditionAdj", "0");
            SeleniumSetMethods.EnterText(ElementType.Id, "Subject_Rooms", "1");
            SeleniumSetMethods.EnterText(ElementType.Id, "SaleComps_0__Rooms", "1");
            SeleniumSetMethods.EnterText(ElementType.Id, "SaleComps_0__RoomsAdj", "0");
            SeleniumSetMethods.EnterText(ElementType.Id, "SaleComps_1__Rooms", "1");
            SeleniumSetMethods.EnterText(ElementType.Id, "SaleComps_1__RoomsAdj", "0");
            SeleniumSetMethods.EnterText(ElementType.Id, "SaleComps_2__Rooms", "1");
            SeleniumSetMethods.EnterText(ElementType.Id, "SaleComps_2__RoomsAdj", "0");
            SeleniumSetMethods.EnterText(ElementType.Id, "Subject_Beds", "4");
            SeleniumSetMethods.EnterText(ElementType.Id, "SaleComps_0__Beds", "4");
            SeleniumSetMethods.EnterText(ElementType.Id, "SaleComps_1__Beds", "4");
            SeleniumSetMethods.EnterText(ElementType.Id, "SaleComps_2__Beds", "4");
            SeleniumSetMethods.EnterText(ElementType.Id, "Subject_Baths", "3");
            SeleniumSetMethods.EnterText(ElementType.Id, "SaleComps_0__Baths", "3");
            SeleniumSetMethods.EnterText(ElementType.Id, "SaleComps_1__Baths", "3");
            SeleniumSetMethods.EnterText(ElementType.Id, "SaleComps_2__Baths", "3");
            SeleniumSetMethods.EnterText(ElementType.Id, "Subject_GrossLivingArea", "3000");
            SeleniumSetMethods.EnterText(ElementType.Id, "SaleComps_0__GrossLivingArea", "3000");
            SeleniumSetMethods.EnterText(ElementType.Id, "SaleComps_0__GrossLivingAreaAdj", "0");
            SeleniumSetMethods.EnterText(ElementType.Id, "SaleComps_1__GrossLivingArea", "3000");
            SeleniumSetMethods.EnterText(ElementType.Id, "SaleComps_1__GrossLivingAreaAdj", "0");
            SeleniumSetMethods.EnterText(ElementType.Id, "SaleComps_2__GrossLivingArea", "3000");
            SeleniumSetMethods.EnterText(ElementType.Id, "SaleComps_2__GrossLivingAreaAdj", "0");
            SeleniumSetMethods.EnterText(ElementType.Id, "Subject_Bsmt", "1");
            SeleniumSetMethods.EnterText(ElementType.Id, "SaleComps_0__Bsmt", "1");
            SeleniumSetMethods.EnterText(ElementType.Id, "SaleComps_0__BsmtAdj", "0");
            SeleniumSetMethods.EnterText(ElementType.Id, "SaleComps_1__Bsmt", "10");
            SeleniumSetMethods.EnterText(ElementType.Id, "SaleComps_1__Bsmt", "1");
            SeleniumSetMethods.EnterText(ElementType.Id, "SaleComps_1__BsmtAdj", "0");
            SeleniumSetMethods.EnterText(ElementType.Id, "SaleComps_2__Bsmt", "1");
            SeleniumSetMethods.EnterText(ElementType.Id, "SaleComps_2__BsmtAdj", "0");
            SeleniumSetMethods.EnterText(ElementType.Id, "Subject_HeatingCooling", "1");
            SeleniumSetMethods.EnterText(ElementType.Id, "SaleComps_0__HeatingCooling", "1");
            SeleniumSetMethods.EnterText(ElementType.Id, "SaleComps_0__HeatingCoolingAdj", "0");
            SeleniumSetMethods.EnterText(ElementType.Id, "SaleComps_1__HeatingCooling", "1");
            SeleniumSetMethods.EnterText(ElementType.Id, "SaleComps_1__HeatingCoolingAdj", "0");
            SeleniumSetMethods.EnterText(ElementType.Id, "SaleComps_2__HeatingCooling", "1");
            SeleniumSetMethods.EnterText(ElementType.Id, "SaleComps_2__HeatingCoolingAdj", "0");
            SeleniumSetMethods.SelectDropDown(ElementType.Id, "Subject_GarageType", "Carport");
            SeleniumSetMethods.EnterText(ElementType.Id, "Subject_GarageCount", "1");
            SeleniumSetMethods.SelectDropDown(ElementType.Id, "SaleComps_0__GarageType", "Carport");
            SeleniumSetMethods.EnterText(ElementType.Id, "SaleComps_0__GarageCount", "1");
            SeleniumSetMethods.EnterText(ElementType.Id, "SaleComps_0__GarageAdj", "0");
            SeleniumSetMethods.SelectDropDown(ElementType.Id, "SaleComps_1__GarageType", "Carport");
            SeleniumSetMethods.EnterText(ElementType.Id, "SaleComps_1__GarageCount", "1");
            SeleniumSetMethods.EnterText(ElementType.Id, "SaleComps_1__GarageAdj", "0");
            SeleniumSetMethods.SelectDropDown(ElementType.Id, "SaleComps_2__GarageType", "Carport");
            SeleniumSetMethods.EnterText(ElementType.Id, "SaleComps_2__GarageCount", "1");
            SeleniumSetMethods.EnterText(ElementType.Id, "SaleComps_2__GarageAdj", "0");
            SeleniumSetMethods.EnterText(ElementType.Id, "Subject_Extras", "1");
            SeleniumSetMethods.EnterText(ElementType.Id, "SaleComps_0__Extras", "1");
            SeleniumSetMethods.EnterText(ElementType.Id, "SaleComps_0__ExtrasAdj", "0");
            SeleniumSetMethods.EnterText(ElementType.Id, "SaleComps_1__Extras", "1");
            SeleniumSetMethods.EnterText(ElementType.Id, "SaleComps_1__ExtrasAdj", "0");
            SeleniumSetMethods.EnterText(ElementType.Id, "SaleComps_2__Extras", "1");
            SeleniumSetMethods.EnterText(ElementType.Id, "SaleComps_2__ExtrasAdj", "0");
            SeleniumSetMethods.EnterText(ElementType.Id, "SubjectMarketing_EstimatedRent", "12345");
            SeleniumSetMethods.EnterText(ElementType.Id, "ListComps_0__StreetAddress", "4");
            SeleniumSetMethods.EnterText(ElementType.Id, "ListComps_1__StreetAddress", "5");
            SeleniumSetMethods.EnterText(ElementType.Id, "ListComps_2__StreetAddress", "6");
            SeleniumSetMethods.EnterText(ElementType.Id, "ListComps_0__City", "Irvine");
            SeleniumSetMethods.EnterText(ElementType.Id, "ListComps_1__City", "Irvine");
            SeleniumSetMethods.EnterText(ElementType.Id, "ListComps_2__City", "Irvine");
            SeleniumSetMethods.SelectDropDown(ElementType.Id, "ListComps_0__State", "California");
            SeleniumSetMethods.SelectDropDown(ElementType.Id, "ListComps_1__State", "California");
            SeleniumSetMethods.SelectDropDown(ElementType.Id, "ListComps_2__State", "California");
            SeleniumSetMethods.EnterText(ElementType.Id, "ListComps_0__PostalCode", "92620");
            SeleniumSetMethods.EnterText(ElementType.Id, "ListComps_1__PostalCode", "92620");
            SeleniumSetMethods.EnterText(ElementType.Id, "ListComps_2__PostalCode", "92620");
            SeleniumSetMethods.EnterText(ElementType.Id, "ListComps_0__ProximityDistance", "1");
            SeleniumSetMethods.EnterText(ElementType.Id, "ListComps_1__ProximityDistance", "1");
            SeleniumSetMethods.EnterText(ElementType.Id, "ListComps_2__ProximityDistance", "1");
            SeleniumSetMethods.EnterText(ElementType.Id, "ListComps_0__ListPrice", "420000");
            SeleniumSetMethods.EnterText(ElementType.Id, "ListComps_1__ListPrice", "422000");
            SeleniumSetMethods.EnterText(ElementType.Id, "ListComps_2__ListPrice", "419000");
            SeleniumSetMethods.EnterText(ElementType.Id, "ListComps_0__OriginalListPrice", "420000");
            SeleniumSetMethods.EnterText(ElementType.Id, "ListComps_1__OriginalListPrice", "422000");
            SeleniumSetMethods.EnterText(ElementType.Id, "ListComps_2__OriginalListPrice", "419000");
            SeleniumSetMethods.EnterText(ElementType.Id, "ListComps_0__PriceReductionCount", "0");
            SeleniumSetMethods.EnterText(ElementType.Id, "ListComps_1__PriceReductionCount", "0");
            SeleniumSetMethods.EnterText(ElementType.Id, "ListComps_2__PriceReductionCount", "0");
            SeleniumSetMethods.SelectDropDown(ElementType.Id, "ListComps_0__DataSource", "MLS");
            SeleniumSetMethods.SelectDropDown(ElementType.Id, "ListComps_1__DataSource", "MLS");
            SeleniumSetMethods.SelectDropDown(ElementType.Id, "ListComps_2__DataSource", "MLS");
            SeleniumSetMethods.EnterText(ElementType.Id, "ListComps_0__Concessions", "0");
            SeleniumSetMethods.EnterText(ElementType.Id, "ListComps_0__ConcessionsAdj", "0");
            SeleniumSetMethods.EnterText(ElementType.Id, "ListComps_1__Concessions", "0");
            SeleniumSetMethods.EnterText(ElementType.Id, "ListComps_1__ConcessionsAdj", "0");
            SeleniumSetMethods.EnterText(ElementType.Id, "ListComps_2__Concessions", "0");
            SeleniumSetMethods.EnterText(ElementType.Id, "ListComps_2__ConcessionsAdj", "0");
            SeleniumSetMethods.EnterText(ElementType.Id, "ListComps_0__Dom", "10");
            SeleniumSetMethods.EnterText(ElementType.Id, "ListComps_1__Dom", "10");
            SeleniumSetMethods.EnterText(ElementType.Id, "ListComps_2__Dom", "10");
            SeleniumSetMethods.SelectDropDown(ElementType.Id, "ListComps_0__LocationType", "Urban");
            SeleniumSetMethods.EnterText(ElementType.Id, "ListComps_0__LocationTypeAdj", "0");
            SeleniumSetMethods.SelectDropDown(ElementType.Id, "ListComps_1__LocationType", "Urban");
            SeleniumSetMethods.EnterText(ElementType.Id, "ListComps_1__LocationTypeAdj", "0");
            SeleniumSetMethods.SelectDropDown(ElementType.Id, "ListComps_2__LocationType", "Urban");
            SeleniumSetMethods.EnterText(ElementType.Id, "ListComps_2__LocationTypeAdj", "0");
            SeleniumSetMethods.SelectDropDown(ElementType.Id, "ListComps_0__FeeSimple", "Lease Hold");
            SeleniumSetMethods.EnterText(ElementType.Id, "ListComps_0__FeeSimpleAdj", "0");
            SeleniumSetMethods.SelectDropDown(ElementType.Id, "ListComps_1__FeeSimple", "Lease Hold");
            SeleniumSetMethods.EnterText(ElementType.Id, "ListComps_1__FeeSimpleAdj", "0");
            SeleniumSetMethods.SelectDropDown(ElementType.Id, "ListComps_2__FeeSimple", "Lease Hold");
            SeleniumSetMethods.EnterText(ElementType.Id, "ListComps_2__FeeSimpleAdj", "0");
            SeleniumSetMethods.EnterText(ElementType.Id, "ListComps_0__LotSize", "1000");
            SeleniumSetMethods.EnterText(ElementType.Id, "ListComps_0__LotSizeAdj", "0");
            SeleniumSetMethods.EnterText(ElementType.Id, "ListComps_1__LotSize", "1000");
            SeleniumSetMethods.EnterText(ElementType.Id, "ListComps_1__LotSizeAdj", "0");
            SeleniumSetMethods.EnterText(ElementType.Id, "ListComps_2__LotSize", "1000");
            SeleniumSetMethods.EnterText(ElementType.Id, "ListComps_2__LotSizeAdj", "0");
            SeleniumSetMethods.EnterText(ElementType.Id, "ListComps_0__Units", "1");
            SeleniumSetMethods.EnterText(ElementType.Id, "ListComps_0__UnitsAdj", "0");
            SeleniumSetMethods.EnterText(ElementType.Id, "ListComps_1__Units", "1");
            SeleniumSetMethods.EnterText(ElementType.Id, "ListComps_1__UnitsAdj", "0");
            SeleniumSetMethods.EnterText(ElementType.Id, "ListComps_2__Units", "1");
            SeleniumSetMethods.EnterText(ElementType.Id, "ListComps_2__UnitsAdj", "0");
            SeleniumSetMethods.EnterText(ElementType.Id, "ListComps_0__ViewDescription", "1");
            SeleniumSetMethods.EnterText(ElementType.Id, "ListComps_0__ViewAdj", "0");
            SeleniumSetMethods.EnterText(ElementType.Id, "ListComps_1__ViewDescription", "1");
            SeleniumSetMethods.EnterText(ElementType.Id, "ListComps_1__ViewAdj", "0");
            SeleniumSetMethods.EnterText(ElementType.Id, "ListComps_2__ViewDescription", "1");
            SeleniumSetMethods.EnterText(ElementType.Id, "ListComps_2__ViewAdj", "0");
            SeleniumSetMethods.SelectDropDown(ElementType.Id, "ListComps_0__Appeal", "Poor");
            SeleniumSetMethods.EnterText(ElementType.Id, "ListComps_0__AppealAdj", "0");
            SeleniumSetMethods.SelectDropDown(ElementType.Id, "ListComps_1__Appeal", "Poor");
            SeleniumSetMethods.EnterText(ElementType.Id, "ListComps_1__AppealAdj", "0");
            SeleniumSetMethods.SelectDropDown(ElementType.Id, "ListComps_2__Appeal", "Poor");
            SeleniumSetMethods.EnterText(ElementType.Id, "ListComps_2__AppealAdj", "0");
            SeleniumSetMethods.EnterText(ElementType.Id, "ListComps_0__YearBuilt", "2000");
            SeleniumSetMethods.EnterText(ElementType.Id, "ListComps_0__YearBuiltAdj", "0");
            SeleniumSetMethods.EnterText(ElementType.Id, "ListComps_1__YearBuilt", "2000");
            SeleniumSetMethods.EnterText(ElementType.Id, "ListComps_1__YearBuiltAdj", "0");
            SeleniumSetMethods.EnterText(ElementType.Id, "ListComps_2__YearBuilt", "2000");
            SeleniumSetMethods.EnterText(ElementType.Id, "ListComps_2__YearBuiltAdj", "0");
            SeleniumSetMethods.SelectDropDown(ElementType.Id, "ListComps_0__Condition", "Poor");
            SeleniumSetMethods.EnterText(ElementType.Id, "ListComps_0__ConditionAdj", "0");
            SeleniumSetMethods.SelectDropDown(ElementType.Id, "ListComps_1__Condition", "Poor");
            SeleniumSetMethods.EnterText(ElementType.Id, "ListComps_1__ConditionAdj", "0");
            SeleniumSetMethods.SelectDropDown(ElementType.Id, "ListComps_2__Condition", "Poor");
            SeleniumSetMethods.EnterText(ElementType.Id, "ListComps_2__ConditionAdj", "0");
            SeleniumSetMethods.EnterText(ElementType.Id, "ListComps_0__Rooms", "1");
            SeleniumSetMethods.EnterText(ElementType.Id, "ListComps_0__RoomsAdj", "0");
            SeleniumSetMethods.EnterText(ElementType.Id, "ListComps_1__Rooms", "1");
            SeleniumSetMethods.EnterText(ElementType.Id, "ListComps_1__RoomsAdj", "0");
            SeleniumSetMethods.EnterText(ElementType.Id, "ListComps_2__Rooms", "1");
            SeleniumSetMethods.EnterText(ElementType.Id, "ListComps_2__RoomsAdj", "0");
            SeleniumSetMethods.EnterText(ElementType.Id, "ListComps_0__Beds", "4");
            SeleniumSetMethods.EnterText(ElementType.Id, "ListComps_1__Beds", "4");
            SeleniumSetMethods.EnterText(ElementType.Id, "ListComps_2__Beds", "4");
            SeleniumSetMethods.EnterText(ElementType.Id, "ListComps_0__Baths", "3");
            SeleniumSetMethods.EnterText(ElementType.Id, "ListComps_1__Baths", "3");
            SeleniumSetMethods.EnterText(ElementType.Id, "ListComps_2__Baths", "3");
            SeleniumSetMethods.EnterText(ElementType.Id, "ListComps_0__GrossLivingArea", "3000");
            SeleniumSetMethods.EnterText(ElementType.Id, "ListComps_0__GrossLivingAreaAdj", "0");
            SeleniumSetMethods.EnterText(ElementType.Id, "ListComps_1__GrossLivingArea", "3000");
            SeleniumSetMethods.EnterText(ElementType.Id, "ListComps_1__GrossLivingAreaAdj", "0");
            SeleniumSetMethods.EnterText(ElementType.Id, "ListComps_2__GrossLivingArea", "3000");
            SeleniumSetMethods.EnterText(ElementType.Id, "ListComps_2__GrossLivingAreaAdj", "0");
            SeleniumSetMethods.EnterText(ElementType.Id, "ListComps_0__Bsmt", "1");
            SeleniumSetMethods.EnterText(ElementType.Id, "ListComps_0__BsmtAdj", "0");
            SeleniumSetMethods.EnterText(ElementType.Id, "ListComps_1__Bsmt", "1");
            SeleniumSetMethods.EnterText(ElementType.Id, "ListComps_1__BsmtAdj", "0");
            SeleniumSetMethods.EnterText(ElementType.Id, "ListComps_2__Bsmt", "1");
            SeleniumSetMethods.EnterText(ElementType.Id, "ListComps_2__BsmtAdj", "0");
            SeleniumSetMethods.EnterText(ElementType.Id, "ListComps_0__HeatingCooling", "1");
            SeleniumSetMethods.EnterText(ElementType.Id, "ListComps_0__HeatingCoolingAdj", "0");
            SeleniumSetMethods.EnterText(ElementType.Id, "ListComps_1__HeatingCooling", "1");
            SeleniumSetMethods.EnterText(ElementType.Id, "ListComps_1__HeatingCoolingAdj", "0");
            SeleniumSetMethods.EnterText(ElementType.Id, "ListComps_2__HeatingCooling", "1");
            SeleniumSetMethods.EnterText(ElementType.Id, "ListComps_2__HeatingCoolingAdj", "0");
            SeleniumSetMethods.SelectDropDown(ElementType.Id, "ListComps_0__GarageType", "Carport");
            SeleniumSetMethods.EnterText(ElementType.Id, "ListComps_0__GarageCount", "1");
            SeleniumSetMethods.EnterText(ElementType.Id, "ListComps_0__GarageAdj", "0");
            SeleniumSetMethods.SelectDropDown(ElementType.Id, "ListComps_1__GarageType", "Carport");
            SeleniumSetMethods.EnterText(ElementType.Id, "ListComps_1__GarageCount", "1");
            SeleniumSetMethods.EnterText(ElementType.Id, "ListComps_1__GarageAdj", "0");
            SeleniumSetMethods.SelectDropDown(ElementType.Id, "ListComps_2__GarageType", "Carport");
            SeleniumSetMethods.EnterText(ElementType.Id, "ListComps_2__GarageCount", "1");
            SeleniumSetMethods.EnterText(ElementType.Id, "ListComps_2__GarageAdj", "0");
            SeleniumSetMethods.EnterText(ElementType.Id, "ListComps_0__Extras", "1");
            SeleniumSetMethods.EnterText(ElementType.Id, "ListComps_0__ExtrasAdj", "0");
            SeleniumSetMethods.EnterText(ElementType.Id, "ListComps_1__Extras", "1");
            SeleniumSetMethods.EnterText(ElementType.Id, "ListComps_1__ExtrasAdj", "0");
            SeleniumSetMethods.EnterText(ElementType.Id, "ListComps_2__Extras", "1");
            SeleniumSetMethods.EnterText(ElementType.Id, "ListComps_2__ExtrasAdj", "0");
            SeleniumSetMethods.EnterText(ElementType.Id, "AsIsValue", "411111");
            SeleniumSetMethods.EnterText(ElementType.Id, "AsisListPrice", "422222");
            SeleniumSetMethods.EnterText(ElementType.Id, "RepairedValue", "433333");
            SeleniumSetMethods.EnterText(ElementType.Id, "RepairedListPrice", "444444");
            SeleniumSetMethods.EnterText(ElementType.Id, "QuickSaleValue", "455555");
            SeleniumSetMethods.EnterText(ElementType.Id, "QuickSaleListPrice", "466666");
            SeleniumSetMethods.EnterText(ElementType.Id, "LandValue", "477777");
            SeleniumSetMethods.EnterText(ElementType.Id, "LandListPrice", "488888");
            SeleniumSetMethods.EnterText(ElementType.Id, "ProviderComments", "The subject is a conforming home within a neighborhood that has declining values of 3% over the prior twelve months. Demand remains strong in this area while short sales and");
            SeleniumSetMethods.EnterText(ElementType.Name, "Addendum", "testing");
            SeleniumSetMethods.Clear(ElementType.Id, "1_1_fileupload");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(ElementType.Id, "1_1_fileupload", "\\\\hqfs1\\Public\\IT\\QA\\Pictures\\C1.jpg");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.Clear(ElementType.Id, "2_1_fileupload");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(ElementType.Id, "2_1_fileupload", "\\\\hqfs1\\Public\\IT\\QA\\Pictures\\C2.jpg");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.Clear(ElementType.Id, "3_1_fileupload");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(ElementType.Id, "3_1_fileupload", "\\\\hqfs1\\Public\\IT\\QA\\Pictures\\C3.jpg");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.Clear(ElementType.Id, "6_1_fileupload");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(ElementType.Id, "6_1_fileupload", "\\\\hqfs1\\Public\\IT\\QA\\Pictures\\C4.jpg");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.Clear(ElementType.Id, "7_1_fileupload");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(ElementType.Id, "7_1_fileupload", "\\\\hqfs1\\Public\\IT\\QA\\Pictures\\C5.jpg");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.Clear(ElementType.Id, "8_1_fileupload");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(ElementType.Id, "8_1_fileupload", "\\\\hqfs1\\Public\\IT\\QA\\Pictures\\C6.jpg");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.Clear(ElementType.Id, "10_1_fileupload");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(ElementType.Id, "10_1_fileupload", "\\\\hqfs1\\Public\\IT\\QA\\Pictures\\B1.jpg");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.Clear(ElementType.Id, "11_1_fileupload");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(ElementType.Id, "11_1_fileupload", "\\\\hqfs1\\Public\\IT\\QA\\Pictures\\B2.jpg");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.Clear(ElementType.Id, "12_1_fileupload");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(ElementType.Id, "12_1_fileupload", "\\\\hqfs1\\Public\\IT\\QA\\Pictures\\B3.jpg");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.Clear(ElementType.Id, "16_fileupload");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(ElementType.Id, "16_fileupload", "\\\\hqfs1\\Public\\IT\\QA\\Pictures\\AUpload.pdf");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.Clear(ElementType.Id, "27_fileupload");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(ElementType.Id, "27_fileupload", "\\\\hqfs1\\Public\\IT\\QA\\Pictures\\AUpload.pdf");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumWindowMethods.Sleep(30);
            SeleniumSetMethods.Wait(ElementType.Id, "btnBpoSave");
            SeleniumSetMethods.Click(ElementType.Id, "btnBpoSave");
            SeleniumSetMethods.AlertWait();
            SeleniumWindowMethods.Assertion(Alert.Accept);
            SeleniumWindowMethods.Sleep(5);
            SeleniumSetMethods.Wait(ElementType.Id, "BrokenRuleComments_QuickSaleValueComment");
            SeleniumSetMethods.EnterText(ElementType.Id, "BrokenRuleComments_QuickSaleValueComment", "Comment here 1");
            SeleniumSetMethods.EnterText(ElementType.Id, "BrokenRuleComments_AsIsValueComment", "Comment here 2");
            SeleniumSetMethods.Wait(ElementType.Id, "btnBpoSubmit");
            SeleniumSetMethods.Click(ElementType.Id, "btnBpoSubmit");
            SeleniumSetMethods.AlertWait();
            SeleniumWindowMethods.Assertion(Alert.Accept);
            SeleniumWindowMethods.Sleep(5);

        }

        public static void FMBClear()
        {
            SeleniumSetMethods.Clear(ElementType.Id, "Subject_ParcelNumber");
            SeleniumSetMethods.Clear(ElementType.Id, "BpoBrokerDistance");
            SeleniumSetMethods.Clear(ElementType.Id, "BpoBrokerLicenseNumber");
            SeleniumSetMethods.Clear(ElementType.Id, "BpoBrokerYearsExperience");
            SeleniumSetMethods.Clear(ElementType.Id, "Marketing_MarketPriceStabilityPercent");
            SeleniumSetMethods.Clear(ElementType.Id, "Marketing_MarketPriceStabilityMonths");
            SeleniumSetMethods.Clear(ElementType.Id, "Marketing_OwnerPercentage");
            SeleniumSetMethods.Clear(ElementType.Id, "Marketing_TenantPercentage");
            SeleniumSetMethods.Clear(ElementType.Id, "Marketing_ComparableListingsCount");
            SeleniumSetMethods.Clear(ElementType.Id, "Marketing_ReoListingsCount");
            SeleniumSetMethods.Clear(ElementType.Id, "Marketing_BoardHomesCount");
            SeleniumSetMethods.Clear(ElementType.Id, "Marketing_NeighborhoodBoundary");
            SeleniumSetMethods.Clear(ElementType.Id, "Marketing_SalesLow");
            SeleniumSetMethods.Clear(ElementType.Id, "Marketing_SalesHigh");
            SeleniumSetMethods.Clear(ElementType.Id, "Marketing_TotalSales");
            SeleniumSetMethods.Clear(ElementType.Id, "Marketing_ListingsLow");
            SeleniumSetMethods.Clear(ElementType.Id, "Marketing_ListingsHigh");
            SeleniumSetMethods.Clear(ElementType.Id, "Marketing_TotalListings");
            SeleniumSetMethods.Clear(ElementType.Id, "Marketing_MarketingDays");
            SeleniumSetMethods.Clear(ElementType.Id, "Marketing_EnvironmentalConcerns");
            SeleniumSetMethods.Clear(ElementType.Id, "SubjectMarketing_HasAllFinancingAvailableDesc");
            SeleniumSetMethods.Clear(ElementType.Id, "SubjectMarketing_SubjectPast12MoListPrice");
            SeleniumSetMethods.Clear(ElementType.Id, "SubjectMarketing_SubjectListPrice");
            SeleniumSetMethods.Clear(ElementType.Id, "SubjectMarketing_SubjectListDate");
            SeleniumSetMethods.Clear(ElementType.Id, "SubjectMarketing_ListingBrokerName");
            SeleniumSetMethods.Clear(ElementType.Id, "SubjectMarketing_ListingFirmName");
            SeleniumSetMethods.Clear(ElementType.Id, "SubjectMarketing_ListingBrokerPhone");
            SeleniumSetMethods.Clear(ElementType.Id, "SubjectMarketing_SubjectDom");
            SeleniumSetMethods.Clear(ElementType.Id, "SubjectMarketing_SubjectStartingListPrice");
            SeleniumSetMethods.Clear(ElementType.Id, "SubjectMarketing_SubjectListPriceReduction1Dom");
            SeleniumSetMethods.Clear(ElementType.Id, "SubjectMarketing_SubjectListPriceReduction2Dom");
            SeleniumSetMethods.Clear(ElementType.Id, "SubjectMarketing_SubjectListPriceReduction3Dom");
            SeleniumSetMethods.Clear(ElementType.Id, "SubjectMarketing_SubjectReduction1ListPrice");
            SeleniumSetMethods.Clear(ElementType.Id, "SubjectMarketing_SubjectReduction2ListPrice");
            SeleniumSetMethods.Clear(ElementType.Id, "SubjectMarketing_SubjectReduction3ListPrice");
            SeleniumSetMethods.Clear(ElementType.Id, "SubjectMarketing_SubjectWhyNotSell");
            SeleniumSetMethods.Clear(ElementType.Id, "SubjectMarketing_SubjectLastSalePrice");
            SeleniumSetMethods.Clear(ElementType.Id, "SubjectMarketing_SubjectLastSalePrice2");
            SeleniumSetMethods.Clear(ElementType.Id, "SubjectMarketing_LegalProjectName");
            SeleniumSetMethods.Clear(ElementType.Id, "SubjectMarketing_LegalProjectUnits");
            SeleniumSetMethods.Clear(ElementType.Id, "SubjectMarketing_HoaFee");
            SeleniumSetMethods.Clear(ElementType.Id, "SubjectMarketing_HoaFeeDelinquentAmount");
            SeleniumSetMethods.Clear(ElementType.Id, "SubjectMarketing_HoaFeeOther");
            SeleniumSetMethods.Clear(ElementType.Id, "SubjectMarketing_HoaCompany");
            SeleniumSetMethods.Clear(ElementType.Id, "SubjectMarketing_HoaContactName");
            SeleniumSetMethods.Clear(ElementType.Id, "SubjectMarketing_HoaPhone");
            SeleniumSetMethods.Clear(ElementType.Id, "SaleComps_0__StreetAddress");
            SeleniumSetMethods.Clear(ElementType.Id, "SaleComps_1__StreetAddress");
            SeleniumSetMethods.Clear(ElementType.Id, "SaleComps_2__StreetAddress");
            SeleniumSetMethods.Clear(ElementType.Id, "SaleComps_0__City");
            SeleniumSetMethods.Clear(ElementType.Id, "SaleComps_1__City");
            SeleniumSetMethods.Clear(ElementType.Id, "SaleComps_2__City");
            SeleniumSetMethods.Clear(ElementType.Id, "SaleComps_0__PostalCode");
            SeleniumSetMethods.Clear(ElementType.Id, "SaleComps_1__PostalCode");
            SeleniumSetMethods.Clear(ElementType.Id, "SaleComps_2__PostalCode");
            SeleniumSetMethods.Clear(ElementType.Id, "SaleComps_0__ProximityDistance");
            SeleniumSetMethods.Clear(ElementType.Id, "SaleComps_1__ProximityDistance");
            SeleniumSetMethods.Clear(ElementType.Id, "SaleComps_2__ProximityDistance");
            SeleniumSetMethods.Clear(ElementType.Id, "SaleComps_0__SalePrice");
            SeleniumSetMethods.Clear(ElementType.Id, "SaleComps_1__SalePrice");
            SeleniumSetMethods.Clear(ElementType.Id, "SaleComps_2__SalePrice");
            SeleniumSetMethods.Clear(ElementType.Id, "SaleComps_0__ListPriceAtSale");
            SeleniumSetMethods.Clear(ElementType.Id, "SaleComps_1__ListPriceAtSale");
            SeleniumSetMethods.Clear(ElementType.Id, "SaleComps_2__ListPriceAtSale");
            SeleniumSetMethods.Clear(ElementType.Id, "SaleComps_0__PriceReductionCount");
            SeleniumSetMethods.Clear(ElementType.Id, "SaleComps_1__PriceReductionCount");
            SeleniumSetMethods.Clear(ElementType.Id, "SaleComps_2__PriceReductionCount");
            SeleniumSetMethods.Clear(ElementType.Id, "SaleComps_0__Dom");
            SeleniumSetMethods.Clear(ElementType.Id, "SaleComps_1__Dom");
            SeleniumSetMethods.Clear(ElementType.Id, "SaleComps_2__Dom");
            SeleniumSetMethods.Clear(ElementType.Id, "SaleComps_0__Concessions");
            SeleniumSetMethods.Clear(ElementType.Id, "SaleComps_0__ConcessionsAdj");
            SeleniumSetMethods.Clear(ElementType.Id, "SaleComps_1__Concessions");
            SeleniumSetMethods.Clear(ElementType.Id, "SaleComps_1__ConcessionsAdj");
            SeleniumSetMethods.Clear(ElementType.Id, "SaleComps_2__Concessions");
            SeleniumSetMethods.Clear(ElementType.Id, "SaleComps_2__ConcessionsAdj");
            SeleniumSetMethods.Clear(ElementType.Id, "SaleComps_0__ConcessionsAdj");
            SeleniumSetMethods.Clear(ElementType.Id, "SaleComps_0__LocationTypeAdj");
            SeleniumSetMethods.Clear(ElementType.Id, "SaleComps_0__FeeSimpleAdj");
            SeleniumSetMethods.Clear(ElementType.Id, "SaleComps_0__LotSizeAdj");
            SeleniumSetMethods.Clear(ElementType.Id, "SaleComps_0__UnitsAdj");
            SeleniumSetMethods.Clear(ElementType.Id, "SaleComps_0__ViewAdj");
            SeleniumSetMethods.Clear(ElementType.Id, "SaleComps_0__AppealAdj");
            SeleniumSetMethods.Clear(ElementType.Id, "SaleComps_0__YearBuiltAdj");
            SeleniumSetMethods.Clear(ElementType.Id, "SaleComps_0__ConditionAdj");
            SeleniumSetMethods.Clear(ElementType.Id, "SaleComps_0__RoomsAdj");
            SeleniumSetMethods.Clear(ElementType.Id, "SaleComps_0__GrossLivingAreaAdj");
            SeleniumSetMethods.Clear(ElementType.Id, "SaleComps_0__BsmtAdj");
            SeleniumSetMethods.Clear(ElementType.Id, "SaleComps_0__HeatingCoolingAdj");
            SeleniumSetMethods.Clear(ElementType.Id, "SaleComps_0__GarageAdj");
            SeleniumSetMethods.Clear(ElementType.Id, "SaleComps_0__ExtrasAdj");
            SeleniumSetMethods.Clear(ElementType.Id, "SaleComps_0__FunctionalUtilityAdj");
            SeleniumSetMethods.Clear(ElementType.Id, "SaleComps_0__LocationTypeAdj");
            SeleniumSetMethods.Clear(ElementType.Id, "SaleComps_1__LocationTypeAdj");
            SeleniumSetMethods.Clear(ElementType.Id, "SaleComps_2__LocationTypeAdj");
            SeleniumSetMethods.Clear(ElementType.Id, "SaleComps_0__FeeSimpleAdj");
            SeleniumSetMethods.Clear(ElementType.Id, "SaleComps_1__FeeSimpleAdj");
            SeleniumSetMethods.Clear(ElementType.Id, "SaleComps_2__FeeSimpleAdj");
            SeleniumSetMethods.Clear(ElementType.Id, "Subject_LotSize");
            SeleniumSetMethods.Clear(ElementType.Id, "SaleComps_0__LotSize");
            SeleniumSetMethods.Clear(ElementType.Id, "SaleComps_0__LotSizeAdj");
            SeleniumSetMethods.Clear(ElementType.Id, "SaleComps_1__LotSize");
            SeleniumSetMethods.Clear(ElementType.Id, "SaleComps_1__LotSizeAdj");
            SeleniumSetMethods.Clear(ElementType.Id, "SaleComps_2__LotSize");
            SeleniumSetMethods.Clear(ElementType.Id, "SaleComps_2__LotSizeAdj");
            SeleniumSetMethods.Clear(ElementType.Id, "Subject_Units");
            SeleniumSetMethods.Clear(ElementType.Id, "SaleComps_0__Units");
            SeleniumSetMethods.Clear(ElementType.Id, "SaleComps_0__UnitsAdj");
            SeleniumSetMethods.Clear(ElementType.Id, "SaleComps_1__Units");
            SeleniumSetMethods.Clear(ElementType.Id, "SaleComps_1__UnitsAdj");
            SeleniumSetMethods.Clear(ElementType.Id, "SaleComps_2__Units");
            SeleniumSetMethods.Clear(ElementType.Id, "SaleComps_2__UnitsAdj");
            SeleniumSetMethods.Clear(ElementType.Id, "Subject_ViewDescription");
            SeleniumSetMethods.Clear(ElementType.Id, "SaleComps_0__ViewDescription");
            SeleniumSetMethods.Clear(ElementType.Id, "SaleComps_0__ViewAdj");
            SeleniumSetMethods.Clear(ElementType.Id, "SaleComps_1__ViewDescription");
            SeleniumSetMethods.Clear(ElementType.Id, "SaleComps_1__ViewAdj");
            SeleniumSetMethods.Clear(ElementType.Id, "SaleComps_2__ViewDescription");
            SeleniumSetMethods.Clear(ElementType.Id, "SaleComps_2__ViewAdj");
            SeleniumSetMethods.Clear(ElementType.Id, "SaleComps_0__AppealAdj");
            SeleniumSetMethods.Clear(ElementType.Id, "SaleComps_1__AppealAdj");
            SeleniumSetMethods.Clear(ElementType.Id, "SaleComps_2__AppealAdj");
            SeleniumSetMethods.Clear(ElementType.Id, "Subject_YearBuilt");
            SeleniumSetMethods.Clear(ElementType.Id, "SaleComps_0__YearBuilt");
            SeleniumSetMethods.Clear(ElementType.Id, "SaleComps_0__YearBuiltAdj");
            SeleniumSetMethods.Clear(ElementType.Id, "SaleComps_1__YearBuilt");
            SeleniumSetMethods.Clear(ElementType.Id, "SaleComps_1__YearBuiltAdj");
            SeleniumSetMethods.Clear(ElementType.Id, "SaleComps_2__YearBuilt");
            SeleniumSetMethods.Clear(ElementType.Id, "SaleComps_2__YearBuiltAdj");
            SeleniumSetMethods.Clear(ElementType.Id, "SaleComps_0__ConditionAdj");
            SeleniumSetMethods.Clear(ElementType.Id, "SaleComps_1__ConditionAdj");
            SeleniumSetMethods.Clear(ElementType.Id, "SaleComps_2__ConditionAdj");
            SeleniumSetMethods.Clear(ElementType.Id, "Subject_Rooms");
            SeleniumSetMethods.Clear(ElementType.Id, "SaleComps_0__Rooms");
            SeleniumSetMethods.Clear(ElementType.Id, "SaleComps_0__RoomsAdj");
            SeleniumSetMethods.Clear(ElementType.Id, "SaleComps_1__Rooms");
            SeleniumSetMethods.Clear(ElementType.Id, "SaleComps_1__RoomsAdj");
            SeleniumSetMethods.Clear(ElementType.Id, "SaleComps_2__Rooms");
            SeleniumSetMethods.Clear(ElementType.Id, "SaleComps_2__RoomsAdj");
            SeleniumSetMethods.Clear(ElementType.Id, "Subject_Beds");
            SeleniumSetMethods.Clear(ElementType.Id, "SaleComps_0__Beds");
            SeleniumSetMethods.Clear(ElementType.Id, "SaleComps_1__Beds");
            SeleniumSetMethods.Clear(ElementType.Id, "SaleComps_2__Beds");
            SeleniumSetMethods.Clear(ElementType.Id, "Subject_Baths");
            SeleniumSetMethods.Clear(ElementType.Id, "SaleComps_0__Baths");
            SeleniumSetMethods.Clear(ElementType.Id, "SaleComps_1__Baths");
            SeleniumSetMethods.Clear(ElementType.Id, "SaleComps_2__Baths");
            SeleniumSetMethods.Clear(ElementType.Id, "Subject_GrossLivingArea");
            SeleniumSetMethods.Clear(ElementType.Id, "SaleComps_0__GrossLivingArea");
            SeleniumSetMethods.Clear(ElementType.Id, "SaleComps_0__GrossLivingAreaAdj");
            SeleniumSetMethods.Clear(ElementType.Id, "SaleComps_1__GrossLivingArea");
            SeleniumSetMethods.Clear(ElementType.Id, "SaleComps_1__GrossLivingAreaAdj");
            SeleniumSetMethods.Clear(ElementType.Id, "SaleComps_2__GrossLivingArea");
            SeleniumSetMethods.Clear(ElementType.Id, "SaleComps_2__GrossLivingAreaAdj");
            SeleniumSetMethods.Clear(ElementType.Id, "Subject_Bsmt");
            SeleniumSetMethods.Clear(ElementType.Id, "SaleComps_0__Bsmt");
            SeleniumSetMethods.Clear(ElementType.Id, "SaleComps_0__BsmtAdj");
            SeleniumSetMethods.Clear(ElementType.Id, "SaleComps_1__Bsmt");
            SeleniumSetMethods.Clear(ElementType.Id, "SaleComps_1__Bsmt");
            SeleniumSetMethods.Clear(ElementType.Id, "SaleComps_1__BsmtAdj");
            SeleniumSetMethods.Clear(ElementType.Id, "SaleComps_2__Bsmt");
            SeleniumSetMethods.Clear(ElementType.Id, "SaleComps_2__BsmtAdj");
            SeleniumSetMethods.Clear(ElementType.Id, "Subject_HeatingCooling");
            SeleniumSetMethods.Clear(ElementType.Id, "SaleComps_0__HeatingCooling");
            SeleniumSetMethods.Clear(ElementType.Id, "SaleComps_0__HeatingCoolingAdj");
            SeleniumSetMethods.Clear(ElementType.Id, "SaleComps_1__HeatingCooling");
            SeleniumSetMethods.Clear(ElementType.Id, "SaleComps_1__HeatingCoolingAdj");
            SeleniumSetMethods.Clear(ElementType.Id, "SaleComps_2__HeatingCooling");
            SeleniumSetMethods.Clear(ElementType.Id, "SaleComps_2__HeatingCoolingAdj");
            SeleniumSetMethods.Clear(ElementType.Id, "Subject_GarageCount");
            SeleniumSetMethods.Clear(ElementType.Id, "SaleComps_0__GarageCount");
            SeleniumSetMethods.Clear(ElementType.Id, "SaleComps_0__GarageAdj");
            SeleniumSetMethods.Clear(ElementType.Id, "SaleComps_1__GarageCount");
            SeleniumSetMethods.Clear(ElementType.Id, "SaleComps_1__GarageAdj");
            SeleniumSetMethods.Clear(ElementType.Id, "SaleComps_2__GarageCount");
            SeleniumSetMethods.Clear(ElementType.Id, "SaleComps_2__GarageAdj");
            SeleniumSetMethods.Clear(ElementType.Id, "Subject_Extras");
            SeleniumSetMethods.Clear(ElementType.Id, "SaleComps_0__Extras");
            SeleniumSetMethods.Clear(ElementType.Id, "SaleComps_0__ExtrasAdj");
            SeleniumSetMethods.Clear(ElementType.Id, "SaleComps_1__Extras");
            SeleniumSetMethods.Clear(ElementType.Id, "SaleComps_1__ExtrasAdj");
            SeleniumSetMethods.Clear(ElementType.Id, "SaleComps_2__Extras");
            SeleniumSetMethods.Clear(ElementType.Id, "SaleComps_2__ExtrasAdj");
            SeleniumSetMethods.Clear(ElementType.Id, "SubjectMarketing_EstimatedRent");
            SeleniumSetMethods.Clear(ElementType.Id, "ListComps_0__StreetAddress");
            SeleniumSetMethods.Clear(ElementType.Id, "ListComps_1__StreetAddress");
            SeleniumSetMethods.Clear(ElementType.Id, "ListComps_2__StreetAddress");
            SeleniumSetMethods.Clear(ElementType.Id, "ListComps_0__City");
            SeleniumSetMethods.Clear(ElementType.Id, "ListComps_1__City");
            SeleniumSetMethods.Clear(ElementType.Id, "ListComps_2__City");
            SeleniumSetMethods.Clear(ElementType.Id, "ListComps_0__PostalCode");
            SeleniumSetMethods.Clear(ElementType.Id, "ListComps_1__PostalCode");
            SeleniumSetMethods.Clear(ElementType.Id, "ListComps_2__PostalCode");
            SeleniumSetMethods.Clear(ElementType.Id, "ListComps_0__ProximityDistance");
            SeleniumSetMethods.Clear(ElementType.Id, "ListComps_1__ProximityDistance");
            SeleniumSetMethods.Clear(ElementType.Id, "ListComps_2__ProximityDistance");
            SeleniumSetMethods.Clear(ElementType.Id, "ListComps_0__ListPrice");
            SeleniumSetMethods.Clear(ElementType.Id, "ListComps_1__ListPrice");
            SeleniumSetMethods.Clear(ElementType.Id, "ListComps_2__ListPrice");
            SeleniumSetMethods.Clear(ElementType.Id, "ListComps_0__OriginalListPrice");
            SeleniumSetMethods.Clear(ElementType.Id, "ListComps_1__OriginalListPrice");
            SeleniumSetMethods.Clear(ElementType.Id, "ListComps_2__OriginalListPrice");
            SeleniumSetMethods.Clear(ElementType.Id, "ListComps_0__PriceReductionCount");
            SeleniumSetMethods.Clear(ElementType.Id, "ListComps_1__PriceReductionCount");
            SeleniumSetMethods.Clear(ElementType.Id, "ListComps_2__PriceReductionCount");
            SeleniumSetMethods.Clear(ElementType.Id, "ListComps_0__Concessions");
            SeleniumSetMethods.Clear(ElementType.Id, "ListComps_0__ConcessionsAdj");
            SeleniumSetMethods.Clear(ElementType.Id, "ListComps_1__Concessions");
            SeleniumSetMethods.Clear(ElementType.Id, "ListComps_1__ConcessionsAdj");
            SeleniumSetMethods.Clear(ElementType.Id, "ListComps_2__Concessions");
            SeleniumSetMethods.Clear(ElementType.Id, "ListComps_2__ConcessionsAdj");
            SeleniumSetMethods.Clear(ElementType.Id, "ListComps_0__Dom");
            SeleniumSetMethods.Clear(ElementType.Id, "ListComps_1__Dom");
            SeleniumSetMethods.Clear(ElementType.Id, "ListComps_2__Dom");
            SeleniumSetMethods.Clear(ElementType.Id, "ListComps_0__LocationTypeAdj");
            SeleniumSetMethods.Clear(ElementType.Id, "ListComps_1__LocationTypeAdj");
            SeleniumSetMethods.Clear(ElementType.Id, "ListComps_2__LocationTypeAdj");
            SeleniumSetMethods.Clear(ElementType.Id, "ListComps_0__FeeSimpleAdj");
            SeleniumSetMethods.Clear(ElementType.Id, "ListComps_1__FeeSimpleAdj");
            SeleniumSetMethods.Clear(ElementType.Id, "ListComps_2__FeeSimpleAdj");
            SeleniumSetMethods.Clear(ElementType.Id, "ListComps_0__LotSize");
            SeleniumSetMethods.Clear(ElementType.Id, "ListComps_0__LotSizeAdj");
            SeleniumSetMethods.Clear(ElementType.Id, "ListComps_1__LotSize");
            SeleniumSetMethods.Clear(ElementType.Id, "ListComps_1__LotSizeAdj");
            SeleniumSetMethods.Clear(ElementType.Id, "ListComps_2__LotSize");
            SeleniumSetMethods.Clear(ElementType.Id, "ListComps_2__LotSizeAdj");
            SeleniumSetMethods.Clear(ElementType.Id, "ListComps_0__Units");
            SeleniumSetMethods.Clear(ElementType.Id, "ListComps_0__UnitsAdj");
            SeleniumSetMethods.Clear(ElementType.Id, "ListComps_1__Units");
            SeleniumSetMethods.Clear(ElementType.Id, "ListComps_1__UnitsAdj");
            SeleniumSetMethods.Clear(ElementType.Id, "ListComps_2__Units");
            SeleniumSetMethods.Clear(ElementType.Id, "ListComps_2__UnitsAdj");
            SeleniumSetMethods.Clear(ElementType.Id, "ListComps_0__ViewDescription");
            SeleniumSetMethods.Clear(ElementType.Id, "ListComps_0__ViewAdj");
            SeleniumSetMethods.Clear(ElementType.Id, "ListComps_1__ViewDescription");
            SeleniumSetMethods.Clear(ElementType.Id, "ListComps_1__ViewAdj");
            SeleniumSetMethods.Clear(ElementType.Id, "ListComps_2__ViewDescription");
            SeleniumSetMethods.Clear(ElementType.Id, "ListComps_2__ViewAdj");
            SeleniumSetMethods.Clear(ElementType.Id, "ListComps_0__AppealAdj");
            SeleniumSetMethods.Clear(ElementType.Id, "ListComps_1__AppealAdj");
            SeleniumSetMethods.Clear(ElementType.Id, "ListComps_2__AppealAdj");
            SeleniumSetMethods.Clear(ElementType.Id, "ListComps_0__YearBuilt");
            SeleniumSetMethods.Clear(ElementType.Id, "ListComps_0__YearBuiltAdj");
            SeleniumSetMethods.Clear(ElementType.Id, "ListComps_1__YearBuilt");
            SeleniumSetMethods.Clear(ElementType.Id, "ListComps_1__YearBuiltAdj");
            SeleniumSetMethods.Clear(ElementType.Id, "ListComps_2__YearBuilt");
            SeleniumSetMethods.Clear(ElementType.Id, "ListComps_2__YearBuiltAdj");
            SeleniumSetMethods.Clear(ElementType.Id, "ListComps_0__ConditionAdj");
            SeleniumSetMethods.Clear(ElementType.Id, "ListComps_1__ConditionAdj");
            SeleniumSetMethods.Clear(ElementType.Id, "ListComps_2__ConditionAdj");
            SeleniumSetMethods.Clear(ElementType.Id, "ListComps_0__Rooms");
            SeleniumSetMethods.Clear(ElementType.Id, "ListComps_0__RoomsAdj");
            SeleniumSetMethods.Clear(ElementType.Id, "ListComps_1__Rooms");
            SeleniumSetMethods.Clear(ElementType.Id, "ListComps_1__RoomsAdj");
            SeleniumSetMethods.Clear(ElementType.Id, "ListComps_2__Rooms");
            SeleniumSetMethods.Clear(ElementType.Id, "ListComps_2__RoomsAdj");
            SeleniumSetMethods.Clear(ElementType.Id, "ListComps_0__Beds");
            SeleniumSetMethods.Clear(ElementType.Id, "ListComps_1__Beds");
            SeleniumSetMethods.Clear(ElementType.Id, "ListComps_2__Beds");
            SeleniumSetMethods.Clear(ElementType.Id, "ListComps_0__Baths");
            SeleniumSetMethods.Clear(ElementType.Id, "ListComps_1__Baths");
            SeleniumSetMethods.Clear(ElementType.Id, "ListComps_2__Baths");
            SeleniumSetMethods.Clear(ElementType.Id, "ListComps_0__GrossLivingArea");
            SeleniumSetMethods.Clear(ElementType.Id, "ListComps_0__GrossLivingAreaAdj");
            SeleniumSetMethods.Clear(ElementType.Id, "ListComps_1__GrossLivingArea");
            SeleniumSetMethods.Clear(ElementType.Id, "ListComps_1__GrossLivingAreaAdj");
            SeleniumSetMethods.Clear(ElementType.Id, "ListComps_2__GrossLivingArea");
            SeleniumSetMethods.Clear(ElementType.Id, "ListComps_2__GrossLivingAreaAdj");
            SeleniumSetMethods.Clear(ElementType.Id, "ListComps_0__Bsmt");
            SeleniumSetMethods.Clear(ElementType.Id, "ListComps_0__BsmtAdj");
            SeleniumSetMethods.Clear(ElementType.Id, "ListComps_1__Bsmt");
            SeleniumSetMethods.Clear(ElementType.Id, "ListComps_1__BsmtAdj");
            SeleniumSetMethods.Clear(ElementType.Id, "ListComps_2__Bsmt");
            SeleniumSetMethods.Clear(ElementType.Id, "ListComps_2__BsmtAdj");
            SeleniumSetMethods.Clear(ElementType.Id, "ListComps_0__HeatingCooling");
            SeleniumSetMethods.Clear(ElementType.Id, "ListComps_0__HeatingCoolingAdj");
            SeleniumSetMethods.Clear(ElementType.Id, "ListComps_1__HeatingCooling");
            SeleniumSetMethods.Clear(ElementType.Id, "ListComps_1__HeatingCoolingAdj");
            SeleniumSetMethods.Clear(ElementType.Id, "ListComps_2__HeatingCooling");
            SeleniumSetMethods.Clear(ElementType.Id, "ListComps_2__HeatingCoolingAdj");
            SeleniumSetMethods.Clear(ElementType.Id, "ListComps_0__GarageCount");
            SeleniumSetMethods.Clear(ElementType.Id, "ListComps_0__GarageAdj");
            SeleniumSetMethods.Clear(ElementType.Id, "ListComps_1__GarageCount");
            SeleniumSetMethods.Clear(ElementType.Id, "ListComps_1__GarageAdj");
            SeleniumSetMethods.Clear(ElementType.Id, "ListComps_2__GarageCount");
            SeleniumSetMethods.Clear(ElementType.Id, "ListComps_2__GarageAdj");
            SeleniumSetMethods.Clear(ElementType.Id, "ListComps_0__Extras");
            SeleniumSetMethods.Clear(ElementType.Id, "ListComps_0__ExtrasAdj");
            SeleniumSetMethods.Clear(ElementType.Id, "ListComps_1__Extras");
            SeleniumSetMethods.Clear(ElementType.Id, "ListComps_1__ExtrasAdj");
            SeleniumSetMethods.Clear(ElementType.Id, "ListComps_2__Extras");
            SeleniumSetMethods.Clear(ElementType.Id, "ListComps_2__ExtrasAdj");
            SeleniumSetMethods.Clear(ElementType.Id, "AsIsValue");
            SeleniumSetMethods.Clear(ElementType.Id, "AsisListPrice");
            SeleniumSetMethods.Clear(ElementType.Id, "RepairedValue");
            SeleniumSetMethods.Clear(ElementType.Id, "RepairedListPrice");
            SeleniumSetMethods.Clear(ElementType.Id, "QuickSaleValue");
            SeleniumSetMethods.Clear(ElementType.Id, "QuickSaleListPrice");
            SeleniumSetMethods.Clear(ElementType.Id, "LandValue");
            SeleniumSetMethods.Clear(ElementType.Id, "LandListPrice");
            SeleniumSetMethods.Clear(ElementType.Id, "ProviderComments");
            SeleniumSetMethods.Clear(ElementType.Name, "Addendum");

        }

    }
}
