using OpenQA.Selenium;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Selenium3
{
    class Form_Val_Unified53BPO
    {
        public static void ClearBPO(Driver driver)
        {
            SeleniumSetMethods.Clear(driver, ElementType.Id, "ParcelNumber");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "BpoBrokerLicenseNumber");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "SalesLow");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "SalesHigh");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "MarketingDays");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "SubjectListPrice");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "SubjectDom");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "ListingBrokerName");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "SubjectListPast12MoOriginalListPrice");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "TotalDOM");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "HoaFee");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "HoaCompany");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "HoaPhone");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "MarketPriceStabilityPercent");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "Taxes");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "PropertyComments");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "ListingComments");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "LocationFactors");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "HighTensionWires");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "Boardups");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "CommercialUses");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "FreewayHighway");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "RRTracks");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "AirPortFlightpath");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "WaisteFacilities");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "FloodPlain");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "NeighDetailsAddnlComments");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "RepairCostComments");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "ReviewersComment");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "SaleComparableData_0__StreetAddress");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "SaleComparableData_1__StreetAddress");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "SaleComparableData_2__StreetAddress");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "SaleComparableData_0__City");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "SaleComparableData_1__City");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "SaleComparableData_2__City");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "SaleComparableData_0__PostalCode");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "SaleComparableData_1__PostalCode");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "SaleComparableData_2__PostalCode");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "SaleComparableData_0__ProximityDistance");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "SaleComparableData_1__ProximityDistance");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "SaleComparableData_2__ProximityDistance");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "SaleComparableData_0__ListPriceAtSale");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "SaleComparableData_1__ListPriceAtSale");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "SaleComparableData_2__ListPriceAtSale");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "SaleComparableData_0__SalePrice");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "SaleComparableData_1__SalePrice");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "SaleComparableData_2__SalePrice");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "SaleComparableData_0__PropertySoldDom");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "SaleComparableData_1__PropertySoldDom");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "SaleComparableData_2__PropertySoldDom");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "LotSize");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "SaleComparableData_0__LotSize");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "SaleComparableData_1__LotSize");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "SaleComparableData_2__LotSize");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "SubjectPropertyUnits");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "SaleComparableData_0__Units");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "SaleComparableData_1__Units");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "SaleComparableData_2__Units");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "YearBuilt");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "SaleComparableData_0__YearBuilt");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "SaleComparableData_1__YearBuilt");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "SaleComparableData_2__YearBuilt");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "Rooms");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "SaleComparableData_0__Rooms");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "SaleComparableData_1__Rooms");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "SaleComparableData_2__Rooms");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "Beds");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "SaleComparableData_0__Beds");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "SaleComparableData_1__Beds");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "SaleComparableData_2__Beds");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "Baths");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "SaleComparableData_0__Baths");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "SaleComparableData_1__Baths");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "SaleComparableData_2__Baths");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "GrossLivingArea");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "SaleComparableData_0__GrossLivingArea");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "SaleComparableData_1__GrossLivingArea");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "SaleComparableData_2__GrossLivingArea");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "Bsmt");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "SaleComparableData_0__Bsmt");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "SaleComparableData_1__Bsmt");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "SaleComparableData_2__Bsmt");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "GarageCount");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "SaleComparableData_0__GarageCount");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "SaleComparableData_1__GarageCount");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "SaleComparableData_2__GarageCount");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "PoolSpa");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "SaleComparableData_0__PoolSpa");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "SaleComparableData_1__PoolSpa");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "SaleComparableData_2__PoolSpa");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "FunctionalUtility");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "SaleComparableData_0__FunctionalUtility");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "SaleComparableData_1__FunctionalUtility");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "SaleComparableData_2__FunctionalUtility");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "CheckListSales1Comments");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "CheckListSales2Comments");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "CheckListSales3Comments");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "ListComparableData_0__StreetAddress");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "ListComparableData_1__StreetAddress");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "ListComparableData_2__StreetAddress");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "ListComparableData_0__City");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "ListComparableData_1__City");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "ListComparableData_2__City");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "ListComparableData_0__PostalCode");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "ListComparableData_1__PostalCode");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "ListComparableData_2__PostalCode");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "ListComparableData_0__ProximityDistance");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "ListComparableData_1__ProximityDistance");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "ListComparableData_2__ProximityDistance");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "ListComparableData_0__ListPrice");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "ListComparableData_1__ListPrice");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "ListComparableData_2__ListPrice");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "ListComparableData_0__OriginalListPrice");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "ListComparableData_1__OriginalListPrice");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "ListComparableData_2__OriginalListPrice");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "ListComparableData_0__Dom");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "ListComparableData_1__Dom");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "ListComparableData_2__Dom");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "ListComparableData_0__CurrentListPriceDom");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "ListComparableData_1__CurrentListPriceDom");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "ListComparableData_2__CurrentListPriceDom");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "ListComparableData_0__LotSize");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "ListComparableData_1__LotSize");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "ListComparableData_2__LotSize");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "ListComparableData_0__Units");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "ListComparableData_1__Units");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "ListComparableData_2__Units");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "ListComparableData_0__YearBuilt");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "ListComparableData_1__YearBuilt");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "ListComparableData_2__YearBuilt");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "ListComparableData_0__Rooms");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "ListComparableData_1__Rooms");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "ListComparableData_2__Rooms");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "ListComparableData_0__Beds");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "ListComparableData_1__Beds");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "ListComparableData_2__Beds");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "ListComparableData_0__Baths");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "ListComparableData_1__Baths");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "ListComparableData_2__Baths");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "ListComparableData_0__GrossLivingArea");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "ListComparableData_1__GrossLivingArea");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "ListComparableData_2__GrossLivingArea");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "ListComparableData_0__Bsmt");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "ListComparableData_1__Bsmt");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "ListComparableData_2__Bsmt");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "ListComparableData_0__GarageCount");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "ListComparableData_1__GarageCount");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "ListComparableData_2__GarageCount");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "ListComparableData_0__PoolSpa");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "ListComparableData_1__PoolSpa");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "ListComparableData_2__PoolSpa");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "ListComparableData_0__FunctionalUtility");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "ListComparableData_1__FunctionalUtility");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "ListComparableData_2__FunctionalUtility");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "CheckListSubjectComments");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "CheckListListing1Comments");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "CheckListListing2Comments");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "CheckListListing3Comments");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "AsIsValue");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "RepairedValue");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "AsisListPrice");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "RepairedListPrice");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "CheckListComments");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "ProviderComments");
        }

        public static void CompleteBPO(Driver driver)
        {
            // Open 5th 3rd BPO Task and Enter Data
            SeleniumWindowMethods.Sleep(2);
            Global.ConsoleOutTab("Begin input @ " + DateTime.Now);
            SeleniumSetMethods.Wait(driver, ElementType.CssSelector, "button.r-button.r-button-collapse-all");
            SeleniumSetMethods.Click(driver, ElementType.CssSelector, "button.r-button.r-button-collapse-all");
            SeleniumSetMethods.Click(driver, ElementType.CssSelector, "button.r-button.r-button-expand-all");
            // Kill maskMoney
            Global.ConsoleOutTab("Kill Money Mask");
            IJavaScriptExecutor js = PropertiesCollection.driver1 as IJavaScriptExecutor;
            string killmoneymask1 = (string)js.ExecuteScript("$(':input.maskMoney').maskMoney('destroy').attr('type', 'number').val('0')");
            string killmoneymask2 = (string)js.ExecuteScript("$(':input').maskMoney('destroy')");
            string killmoneymask3 = (string)js.ExecuteScript("$(':input.maskMoney').maskMoney('destroy').attr('type', 'number')");
            // Clear maskMoney
            SeleniumSetMethods.Clear(driver, ElementType.Id, "SalesLow");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.Clear(driver, ElementType.Id, "SalesHigh");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.Clear(driver, ElementType.Id, "SubjectListPrice");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.Clear(driver, ElementType.Id, "SubjectListPast12MoOriginalListPrice");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.Clear(driver, ElementType.Id, "HoaFee");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.Clear(driver, ElementType.Id, "Taxes");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.Clear(driver, ElementType.Id, "SaleComparableData_0__ListPriceAtSale");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.Clear(driver, ElementType.Id, "SaleComparableData_1__ListPriceAtSale");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.Clear(driver, ElementType.Id, "SaleComparableData_2__ListPriceAtSale");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.Clear(driver, ElementType.Id, "SaleComparableData_0__OriginalListPrice");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.Clear(driver, ElementType.Id, "SaleComparableData_1__OriginalListPrice");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.Clear(driver, ElementType.Id, "SaleComparableData_2__OriginalListPrice");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.Clear(driver, ElementType.Id, "SaleComparableData_0__SalePrice");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.Clear(driver, ElementType.Id, "SaleComparableData_1__SalePrice");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.Clear(driver, ElementType.Id, "SaleComparableData_2__SalePrice");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.Clear(driver, ElementType.Id, "ListComparableData_0__ListPrice");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.Clear(driver, ElementType.Id, "ListComparableData_1__ListPrice");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.Clear(driver, ElementType.Id, "ListComparableData_2__ListPrice");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.Clear(driver, ElementType.Id, "ListComparableData_0__OriginalListPrice");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.Clear(driver, ElementType.Id, "ListComparableData_1__OriginalListPrice");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.Clear(driver, ElementType.Id, "ListComparableData_2__OriginalListPrice");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.Clear(driver, ElementType.Id, "AsIsValue");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.Clear(driver, ElementType.Id, "AsisListPrice");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.Clear(driver, ElementType.Id, "RepairedValue");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.Clear(driver, ElementType.Id, "RepairedListPrice");
            SeleniumWindowMethods.ThrottlingSleep();
            // Entering input
            SeleniumSetMethods.Click(driver, ElementType.Id, "InspectedDate");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.Click(driver, ElementType.XPath, "(//button[@type='button'])[9]");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.SelectDropDown(driver, ElementType.Id, "PropertyType", "Single Family");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "ParcelNumber", "5565112");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "BpoBrokerLicenseNumber", "64655513");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.Click(driver, ElementType.Id, "MarketConditions");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.SelectDropDown(driver, ElementType.Id, "MarketConditions", "Increasing");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.Click(driver, ElementType.CssSelector, "option[value=\"Increasing\"]");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.SelectDropDown(driver, ElementType.Id, "EmploymentConditions", "Improving");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "SalesLow", "450000");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.Click(driver, ElementType.Id, "SalesLow");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "SalesHigh", "675000");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.Click(driver, ElementType.Id, "SalesHigh");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "MarketingDays", "15");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.Click(driver, ElementType.Id, "IsSubjectListed");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.SelectDropDown(driver, ElementType.Id, "IsSubjectListed", "Yes");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.Click(driver, ElementType.CssSelector, "option[value=\"True\"]");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "SubjectListPrice", "500500");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.Click(driver, ElementType.Id, "SubjectListPrice");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.Click(driver, ElementType.Id, "SubjectListDate");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.Click(driver, ElementType.LinkText, "1");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "SubjectDom", "20");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "ListingBrokerName", "Agent");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.SelectDropDown(driver, ElementType.Id, "IsSubjectListedPast12Mo", "Yes");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "SubjectListPast12MoOriginalListPrice", "500011");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.Click(driver, ElementType.Id, "SubjectListPast12MoOriginalListDate");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.Click(driver, ElementType.LinkText, "1");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "TotalDOM", "10");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.Click(driver, ElementType.Id, "MandatoryAssociation");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.SelectDropDown(driver, ElementType.Id, "MandatoryAssociation", "Yes");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.Click(driver, ElementType.CssSelector, "#MandatoryAssociation > option[value=\"True\"]");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "HoaFee", "350");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.Click(driver, ElementType.Id, "HoaBillingCycle");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.SelectDropDown(driver, ElementType.Id, "HoaBillingCycle", "Monthly");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.Click(driver, ElementType.CssSelector, "option[value=\"monthly\"]");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "HoaCompany", "Irvine Company");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "HoaPhone", "(949) 555-3456");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.SelectDropDown(driver, ElementType.Id, "SubjectOccupancyStatus", "Occupied");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.SelectDropDown(driver, ElementType.Id, "Condition", "Excellent");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.SelectDropDown(driver, ElementType.Id, "LocationType", "Suburban");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.SelectDropDown(driver, ElementType.Id, "MarketPriceStability", "Increased");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "MarketPriceStabilityPercent", "10");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "Taxes", "10000");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "PropertyComments", "I really like this property.  It's so beautiful");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "ListingComments", "Listing Comments about listing things");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "LocationFactors", "Good For Solar");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "HighTensionWires", "I would try to walk them");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "Boardups", "none here");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "CommercialUses", "probably not ideal");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "FreewayHighway", "Near by");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "RRTracks", "can not hear the train");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "AirPortFlightpath", "can not see or hear airplanes");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "WaisteFacilities", "near by");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "FloodPlain", "does not apply");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "NeighDetailsAddnlComments", "would buy in a heart beat");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.Click(driver, ElementType.Id, "AsIsOrRepaired");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.SelectDropDown(driver, ElementType.Id, "AsIsOrRepaired", "As Is");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.Click(driver, ElementType.CssSelector, "#AsIsOrRepaired > option[value=\"True\"]");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "ReviewersComment", "Turn Key, Move in Ready");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "SaleComparableData_0__StreetAddress", Global.sc1street);
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "SaleComparableData_1__StreetAddress", Global.sc2street);
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "SaleComparableData_2__StreetAddress", Global.sc3street);
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "SaleComparableData_0__City", Global.sc1city);
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "SaleComparableData_1__City", Global.sc2city);
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "SaleComparableData_2__City", Global.sc3city);
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.SelectDropDown(driver, ElementType.Id, "SaleComparableData_0__State", Global.sc1state);
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.SelectDropDown(driver, ElementType.Id, "SaleComparableData_1__State", Global.sc2state);
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.SelectDropDown(driver, ElementType.Id, "SaleComparableData_2__State", Global.sc3state);
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "SaleComparableData_0__PostalCode", Global.sc1zipcode);
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "SaleComparableData_1__PostalCode", Global.sc2zipcode);
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "SaleComparableData_2__PostalCode", Global.sc3zipcode);
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "SaleComparableData_0__ProximityDistance", "1");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "SaleComparableData_1__ProximityDistance", "1");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "SaleComparableData_2__ProximityDistance", "1");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.SelectDropDown(driver, ElementType.Id, "SaleComparableData_0__SaleType", "Fair Market Value");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.SelectDropDown(driver, ElementType.Id, "SaleComparableData_1__SaleType", "Fair Market Value");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.SelectDropDown(driver, ElementType.Id, "SaleComparableData_2__SaleType", "Fair Market Value");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "SaleComparableData_0__ListPriceAtSale", "500000");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.Click(driver, ElementType.Id, "SaleComparableData_0__ListPriceAtSale");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "SaleComparableData_1__ListPriceAtSale", "500001");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.Click(driver, ElementType.Id, "SaleComparableData_1__ListPriceAtSale");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "SaleComparableData_2__ListPriceAtSale", "500002");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.Click(driver, ElementType.Id, "SaleComparableData_2__ListPriceAtSale");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "SaleComparableData_0__OriginalListPrice", "500100");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.Click(driver, ElementType.Id, "SaleComparableData_0__OriginalListPrice");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "SaleComparableData_1__OriginalListPrice", "500101");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.Click(driver, ElementType.Id, "SaleComparableData_1__OriginalListPrice");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "SaleComparableData_2__OriginalListPrice", "500102");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.Click(driver, ElementType.Id, "SaleComparableData_2__OriginalListPrice");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "SaleComparableData_0__Dom", "31");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "SaleComparableData_1__Dom", "32");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "SaleComparableData_2__Dom", "33");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.SelectDropDown(driver, ElementType.Id, "DataSource", "MLS");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.SelectDropDown(driver, ElementType.Id, "SaleComparableData_0__DataSource", "MLS");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.SelectDropDown(driver, ElementType.Id, "SaleComparableData_1__DataSource", "MLS");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.SelectDropDown(driver, ElementType.Id, "SaleComparableData_2__DataSource", "MLS");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "SaleComparableData_0__SalePrice", "500006");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.Click(driver, ElementType.Id, "SaleComparableData_0__SalePrice");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "SaleComparableData_1__SalePrice", "500007");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.Click(driver, ElementType.Id, "SaleComparableData_1__SalePrice");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "SaleComparableData_2__SalePrice", "500010");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.Click(driver, ElementType.Id, "SaleComparableData_2__SalePrice");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.Click(driver, ElementType.Id, "SaleComparableData_0__SaleDate");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.Click(driver, ElementType.LinkText, "1");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.Click(driver, ElementType.Id, "SaleComparableData_1__SaleDate");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.Click(driver, ElementType.LinkText, "1");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.Click(driver, ElementType.Id, "SaleComparableData_2__SaleDate");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.Click(driver, ElementType.LinkText, "1");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "SaleComparableData_0__PropertySoldDom", "30");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "SaleComparableData_1__PropertySoldDom", "30");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "SaleComparableData_2__PropertySoldDom", "30");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.SelectDropDown(driver, ElementType.Id, "SaleComparableData_0__PropertyType", "Single Family");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.SelectDropDown(driver, ElementType.Id, "SaleComparableData_1__PropertyType", "Single Family");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.SelectDropDown(driver, ElementType.Id, "SaleComparableData_2__PropertyType", "Single Family");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.SelectDropDown(driver, ElementType.Id, "Style", "2 Story");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.SelectDropDown(driver, ElementType.Id, "SaleComparableData_0__Style", "2 Story");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.SelectDropDown(driver, ElementType.Id, "SaleComparableData_1__Style", "2 Story");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.SelectDropDown(driver, ElementType.Id, "SaleComparableData_2__Style", "2 Story");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.SelectDropDown(driver, ElementType.Id, "SaleComparableData_0__LocationType", "Suburban");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.SelectDropDown(driver, ElementType.Id, "SaleComparableData_1__LocationType", "Suburban");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.SelectDropDown(driver, ElementType.Id, "SaleComparableData_2__LocationType", "Suburban");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.SelectDropDown(driver, ElementType.Id, "LotSizeUnitType", "Sq. Ft.");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "LotSize", "4000");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "SaleComparableData_0__LotSize", "4250");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "SaleComparableData_1__LotSize", "4000");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "SaleComparableData_2__LotSize", "4500");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "SubjectPropertyUnits", "1");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "SaleComparableData_0__Units", "1");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "SaleComparableData_1__Units", "1");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "SaleComparableData_2__Units", "1");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "YearBuilt", "2014");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "SaleComparableData_0__YearBuilt", "2014");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "SaleComparableData_1__YearBuilt", "2014");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "SaleComparableData_2__YearBuilt", "2014");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.SelectDropDown(driver, ElementType.Id, "SaleComparableData_0__Condition", "Good");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.SelectDropDown(driver, ElementType.Id, "SaleComparableData_1__Condition", "Good");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.SelectDropDown(driver, ElementType.Id, "SaleComparableData_2__Condition", "Good");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.Clear(driver, ElementType.Id, "Rooms");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "Rooms", "3");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "SaleComparableData_0__Rooms", "3");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "SaleComparableData_1__Rooms", "3");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "SaleComparableData_2__Rooms", "3");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.Clear(driver, ElementType.Id, "Beds");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "Beds", "3");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "SaleComparableData_0__Beds", "3");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "SaleComparableData_1__Beds", "3");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "SaleComparableData_2__Beds", "3");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.Clear(driver, ElementType.Id, "Baths");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "Baths", "3");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "SaleComparableData_0__Baths", "3");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "SaleComparableData_1__Baths", "3");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "SaleComparableData_2__Baths", "3");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.Clear(driver, ElementType.Id, "GrossLivingArea");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "GrossLivingArea", "2000");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "SaleComparableData_0__GrossLivingArea", "2000");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "SaleComparableData_1__GrossLivingArea", "2000");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "SaleComparableData_2__GrossLivingArea", "2000");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.Clear(driver, ElementType.Id, "Bsmt");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "Bsmt", "0");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "SaleComparableData_0__Bsmt", "0");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "SaleComparableData_1__Bsmt", "0");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "SaleComparableData_2__Bsmt", "0");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.SelectDropDown(driver, ElementType.Id, "ConstructionType", "Brick");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.SelectDropDown(driver, ElementType.Id, "SaleComparableData_0__ConstructionType", "Brick");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.SelectDropDown(driver, ElementType.Id, "SaleComparableData_1__ConstructionType", "Brick");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.SelectDropDown(driver, ElementType.Id, "SaleComparableData_2__ConstructionType", "Brick");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.SelectDropDown(driver, ElementType.Id, "GarageType", "Attached");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.Click(driver, ElementType.Id, "SaleComparableData_0__GarageType");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.SelectDropDown(driver, ElementType.Id, "SaleComparableData_0__GarageType", "Attached");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.SelectDropDown(driver, ElementType.Id, "SaleComparableData_1__GarageType", "Attached");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.SelectDropDown(driver, ElementType.Id, "SaleComparableData_2__GarageType", "Attached");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.Clear(driver, ElementType.Id, "GarageCount");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "GarageCount", "2");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "SaleComparableData_0__GarageCount", "2");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "SaleComparableData_1__GarageCount", "2");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "SaleComparableData_2__GarageCount", "2");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.Clear(driver, ElementType.Id, "PoolSpa");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "PoolSpa", "1");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "SaleComparableData_0__PoolSpa", "1");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "SaleComparableData_1__PoolSpa", "1");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "SaleComparableData_2__PoolSpa", "1");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.Clear(driver, ElementType.Id, "FunctionalUtility");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "FunctionalUtility", "1");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "SaleComparableData_0__FunctionalUtility", "1");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "SaleComparableData_1__FunctionalUtility", "1");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "SaleComparableData_2__FunctionalUtility", "1");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.SelectDropDown(driver, ElementType.Id, "SaleComparableData_0__Comparability", "Equal");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.SelectDropDown(driver, ElementType.Id, "SaleComparableData_1__Comparability", "Equal");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.SelectDropDown(driver, ElementType.Id, "SaleComparableData_2__Comparability", "Equal");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "CheckListSales1Comments", "Testing 12345");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "CheckListSales2Comments", "Testing 67890");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "CheckListSales3Comments", "Testing 101112");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "ListComparableData_0__StreetAddress", Global.lc1street);
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "ListComparableData_1__StreetAddress", Global.lc2street);
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "ListComparableData_2__StreetAddress", Global.lc3street);
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "ListComparableData_0__City", Global.lc1city);
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "ListComparableData_1__City", Global.lc2city);
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "ListComparableData_2__City", Global.lc3city);
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.SelectDropDown(driver, ElementType.Id, "ListComparableData_0__State", Global.lc1state);
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.SelectDropDown(driver, ElementType.Id, "ListComparableData_1__State", Global.lc2state);
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.SelectDropDown(driver, ElementType.Id, "ListComparableData_2__State", Global.lc3state);
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "ListComparableData_0__PostalCode", Global.lc1zipcode);
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "ListComparableData_1__PostalCode", Global.lc2zipcode);
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "ListComparableData_2__PostalCode", Global.lc3zipcode);
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "ListComparableData_0__ProximityDistance", "1");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "ListComparableData_1__ProximityDistance", "1");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "ListComparableData_2__ProximityDistance", "1");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.SelectDropDown(driver, ElementType.Id, "L1SaleType_LookupId", "Fair Market Value");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.SelectDropDown(driver, ElementType.Id, "L2SaleType_LookupId", "Fair Market Value");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.SelectDropDown(driver, ElementType.Id, "L3SaleType_LookupId", "Fair Market Value");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "ListComparableData_0__ListPrice", "510001");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.Click(driver, ElementType.Id, "ListComparableData_0__ListPrice");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "ListComparableData_1__ListPrice", "510002");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.Click(driver, ElementType.Id, "ListComparableData_1__ListPrice");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "ListComparableData_2__ListPrice", "510003");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.Click(driver, ElementType.Id, "ListComparableData_2__ListPrice");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "ListComparableData_0__OriginalListPrice", "510004");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.Click(driver, ElementType.Id, "ListComparableData_0__OriginalListPrice");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "ListComparableData_1__OriginalListPrice", "510005");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.Click(driver, ElementType.Id, "ListComparableData_1__OriginalListPrice");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "ListComparableData_2__OriginalListPrice", "510006");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.Click(driver, ElementType.Id, "ListComparableData_2__OriginalListPrice");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "ListComparableData_0__Dom", "30");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "ListComparableData_1__Dom", "45");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "ListComparableData_2__Dom", "30");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.SelectDropDown(driver, ElementType.XPath, "(//select[@id='DataSource'])[2]", "MLS");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.SelectDropDown(driver, ElementType.Id, "ListComparableData_0__DataSource", "MLS");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.SelectDropDown(driver, ElementType.Id, "ListComparableData_1__DataSource", "MLS");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.SelectDropDown(driver, ElementType.Id, "ListComparableData_2__DataSource", "MLS");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "ListComparableData_0__CurrentListPriceDom", "30");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "ListComparableData_1__CurrentListPriceDom", "31");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "ListComparableData_2__CurrentListPriceDom", "32");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.SelectDropDown(driver, ElementType.Id, "ListComparableData_0__PropertyType", "Single Family");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.SelectDropDown(driver, ElementType.Id, "ListComparableData_1__PropertyType", "Single Family");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.SelectDropDown(driver, ElementType.Id, "ListComparableData_2__PropertyType", "Single Family");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.SelectDropDown(driver, ElementType.Id, "ListComparableData_0__Style", "2 Story");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.SelectDropDown(driver, ElementType.Id, "ListComparableData_1__Style", "2 Story");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.SelectDropDown(driver, ElementType.Id, "ListComparableData_2__Style", "2 Story");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.SelectDropDown(driver, ElementType.Id, "ListComparableData_0__LocationType", "Suburban");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.SelectDropDown(driver, ElementType.Id, "ListComparableData_1__LocationType", "Suburban");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.SelectDropDown(driver, ElementType.Id, "ListComparableData_2__LocationType", "Suburban");
            SeleniumWindowMethods.ThrottlingSleep();           
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "ListComparableData_0__LotSize", "4000");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "ListComparableData_1__LotSize", "4250");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "ListComparableData_2__LotSize", "4000");
            SeleniumWindowMethods.ThrottlingSleep();            
            SeleniumSetMethods.Click(driver, ElementType.Id, "ListComparableData_0__Units");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "ListComparableData_0__Units", "1");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.Click(driver, ElementType.Id, "ListComparableData_1__Units");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "ListComparableData_1__Units", "1");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.Click(driver, ElementType.Id, "ListComparableData_2__Units");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "ListComparableData_2__Units", "1");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.Click(driver, ElementType.Id, "ListComparableData_0__YearBuilt");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "ListComparableData_0__YearBuilt", "2014");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.Click(driver, ElementType.Id, "ListComparableData_1__YearBuilt");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "ListComparableData_1__YearBuilt", "2014");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.Click(driver, ElementType.Id, "ListComparableData_2__YearBuilt");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "ListComparableData_2__YearBuilt", "2014");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.SelectDropDown(driver, ElementType.Id, "ListComparableData_0__Condition", "Good");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.SelectDropDown(driver, ElementType.Id, "ListComparableData_1__Condition", "Good");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.SelectDropDown(driver, ElementType.Id, "ListComparableData_2__Condition", "Good");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "ListComparableData_0__Rooms", "3");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "ListComparableData_1__Rooms", "3");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "ListComparableData_2__Rooms", "3");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "ListComparableData_0__Beds", "3");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "ListComparableData_1__Beds", "3");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "ListComparableData_2__Beds", "3");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "ListComparableData_0__Baths", "3");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "ListComparableData_1__Baths", "3");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "ListComparableData_2__Baths", "3");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "ListComparableData_0__GrossLivingArea", "2000");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "ListComparableData_1__GrossLivingArea", "2000");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "ListComparableData_2__GrossLivingArea", "2000");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "ListComparableData_0__Bsmt", "0");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "ListComparableData_1__Bsmt", "0");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "ListComparableData_2__Bsmt", "0");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.SelectDropDown(driver, ElementType.XPath, "(//select[@id='ConstructionType'])[2]", "Brick");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.SelectDropDown(driver, ElementType.Id, "ListComparableData_0__ConstructionType", "Brick");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.SelectDropDown(driver, ElementType.Id, "ListComparableData_1__ConstructionType", "Brick");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.SelectDropDown(driver, ElementType.Id, "ListComparableData_2__ConstructionType", "Brick");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.SelectDropDown(driver, ElementType.XPath, "(//select[@id='GarageType'])[2]", "Attached");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.SelectDropDown(driver, ElementType.Id, "ListComparableData_0__GarageType", "Attached");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.SelectDropDown(driver, ElementType.Id, "ListComparableData_1__GarageType", "Attached");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.SelectDropDown(driver, ElementType.Id, "ListComparableData_2__GarageType", "Attached");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "ListComparableData_0__GarageCount", "2");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "ListComparableData_1__GarageCount", "2");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "ListComparableData_2__GarageCount", "2");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "ListComparableData_0__PoolSpa", "1");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "ListComparableData_1__PoolSpa", "1");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "ListComparableData_2__PoolSpa", "1");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "ListComparableData_0__FunctionalUtility", "1");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "ListComparableData_1__FunctionalUtility", "1");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "ListComparableData_2__FunctionalUtility", "1");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.SelectDropDown(driver, ElementType.Id, "ListComparableData_0__Comparability", "Superior");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.SelectDropDown(driver, ElementType.Id, "ListComparableData_1__Comparability", "Superior");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.SelectDropDown(driver, ElementType.Id, "ListComparableData_2__Comparability", "Superior");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "CheckListSubjectComments", "Testing again 123");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "CheckListListing1Comments", "Testing again 234");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "CheckListListing2Comments", "Testing again 567");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "CheckListListing3Comments", "Testing again 789");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "AsIsValue", "500007");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.Click(driver, ElementType.Id, "AsIsValue");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "RepairedValue", "550000");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.Click(driver, ElementType.Id, "RepairedValue");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "AsisListPrice", "500001");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.Click(driver, ElementType.Id, "AsisListPrice");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "RepairedListPrice", "500002");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.Click(driver, ElementType.Id, "RepairedListPrice");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.SelectDropDown(driver, ElementType.Id, "CheckList01", "Yes");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.SelectDropDown(driver, ElementType.Id, "CheckList02", "No");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.SelectDropDown(driver, ElementType.Id, "CheckList03", "No");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.SelectDropDown(driver, ElementType.Id, "CheckList04", "No");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.SelectDropDown(driver, ElementType.Id, "CheckList05", "No");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.SelectDropDown(driver, ElementType.Id, "DecliningValues", "No");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "CheckListComments", "Check List Comments 132456");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "ProviderComments", "hello it's me");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.Wait(driver, ElementType.CssSelector, "button.r-button.r-button-collapse-all");
            SeleniumSetMethods.Click(driver, ElementType.CssSelector, "button.r-button.r-button-collapse-all");
            Global.ConsoleOut("Coffee Break Started at for 60 seconds " + DateTime.Now);
            SeleniumWindowMethods.Sleep(60);
        }

        public static void Attachments(Driver driver, ENV environment)
        {
            SeleniumSetMethods.Wait(driver, ElementType.CssSelector, "button.r-button.r-button-expand-all");
            SeleniumSetMethods.Click(driver, ElementType.CssSelector, "button.r-button.r-button-expand-all");
            // Add Exterior Attachments to U53 Order
            Global.ConsoleOutTab("Begin adding Attachments at " + DateTime.Now);
            if (environment == ENV.QA)
            {
                SeleniumSetMethods.FileUpload(driver, ElementType.Id, "63_1_fileupload", "C1.jpg");
                SeleniumSetMethods.FileUpload(driver, ElementType.Id, "65_1_fileupload", "C2.jpg");
                SeleniumSetMethods.FileUpload(driver, ElementType.Id, "66_1_fileupload", "C3.jpg");
                SeleniumSetMethods.FileUpload(driver, ElementType.Id, "70_1_fileupload", "C4.jpg");
                SeleniumSetMethods.FileUpload(driver, ElementType.Id, "71_1_fileupload", "C5.jpg");
                SeleniumSetMethods.FileUpload(driver, ElementType.Id, "72_1_fileupload", "C6.jpg");
                SeleniumSetMethods.FileUpload(driver, ElementType.Id, "73_1_fileupload", "C7.jpg");
                SeleniumSetMethods.FileUpload(driver, ElementType.Id, "74_1_fileupload", "C8.jpg");
                SeleniumSetMethods.FileUpload(driver, ElementType.Id, "75_1_fileupload", "C9.jpg");
            }
            else if (environment == ENV.UAT)
            {
                SeleniumSetMethods.FileUpload(driver, ElementType.Id, "97_1_fileupload", "C1.jpg");
                SeleniumSetMethods.FileUpload(driver, ElementType.Id, "99_1_fileupload", "C2.jpg");
                SeleniumSetMethods.FileUpload(driver, ElementType.Id, "100_1_fileupload", "C3.jpg");
                SeleniumSetMethods.FileUpload(driver, ElementType.Id, "69_1_fileupload", "C4.jpg");
                SeleniumSetMethods.FileUpload(driver, ElementType.Id, "70_1_fileupload", "C5.jpg");
                SeleniumSetMethods.FileUpload(driver, ElementType.Id, "71_1_fileupload", "C6.jpg");
                SeleniumSetMethods.FileUpload(driver, ElementType.Id, "72_1_fileupload", "C7.jpg");
                SeleniumSetMethods.FileUpload(driver, ElementType.Id, "73_1_fileupload", "C8.jpg");
                SeleniumSetMethods.FileUpload(driver, ElementType.Id, "74_1_fileupload", "C9.jpg");
            }
            else if (environment == ENV.STG)
            {
                SeleniumSetMethods.FileUpload(driver, ElementType.Id, "61_1_fileupload", "C1.jpg");
                SeleniumSetMethods.FileUpload(driver, ElementType.Id, "63_1_fileupload", "C2.jpg");
                SeleniumSetMethods.FileUpload(driver, ElementType.Id, "64_1_fileupload", "C3.jpg");
                SeleniumSetMethods.FileUpload(driver, ElementType.Id, "68_1_fileupload", "C4.jpg");
                SeleniumSetMethods.FileUpload(driver, ElementType.Id, "69_1_fileupload", "C5.jpg");
                SeleniumSetMethods.FileUpload(driver, ElementType.Id, "70_1_fileupload", "C6.jpg");
                SeleniumSetMethods.FileUpload(driver, ElementType.Id, "71_1_fileupload", "C7.jpg");
                SeleniumSetMethods.FileUpload(driver, ElementType.Id, "72_1_fileupload", "C8.jpg");
                SeleniumSetMethods.FileUpload(driver, ElementType.Id, "73_1_fileupload", "C9.jpg");              
            }
            else if (environment == ENV.PROD)
            {
                SeleniumSetMethods.FileUpload(driver, ElementType.Id, "61_1_fileupload", "C1.jpg");
                SeleniumSetMethods.FileUpload(driver, ElementType.Id, "63_1_fileupload", "C2.jpg");
                SeleniumSetMethods.FileUpload(driver, ElementType.Id, "64_1_fileupload", "C3.jpg");
                SeleniumSetMethods.FileUpload(driver, ElementType.Id, "68_1_fileupload", "C4.jpg");
                SeleniumSetMethods.FileUpload(driver, ElementType.Id, "69_1_fileupload", "C5.jpg");
                SeleniumSetMethods.FileUpload(driver, ElementType.Id, "70_1_fileupload", "C6.jpg");
                SeleniumSetMethods.FileUpload(driver, ElementType.Id, "71_1_fileupload", "C7.jpg");
                SeleniumSetMethods.FileUpload(driver, ElementType.Id, "72_1_fileupload", "C8.jpg");
                SeleniumSetMethods.FileUpload(driver, ElementType.Id, "73_1_fileupload", "C9.jpg");
            }
            // Complete Attachment Section
            SeleniumSetMethods.FileUpload(driver, ElementType.Id, "16_fileupload", "AUpload.pdf");
            SeleniumSetMethods.FileUpload(driver, ElementType.Id, "27_fileupload", "AUpload.pdf");
            SeleniumSetMethods.FileUpload(driver, ElementType.Id, "28_fileupload", "AUpload.pdf");
            SeleniumSetMethods.FileUpload(driver, ElementType.Id, "244_fileupload", "AUpload.pdf");
            SeleniumSetMethods.FileUpload(driver, ElementType.Id, "productUpload_117_fileupload", "AUpload.pdf");
            SeleniumSetMethods.FileUpload(driver, ElementType.Id, "productUpload_124_fileupload", "AUpload.pdf");
            SeleniumSetMethods.FileUpload(driver, ElementType.Id, "productUpload_230_fileupload", "AUpload.pdf");
            SeleniumSetMethods.FileUpload(driver, ElementType.Id, "productUpload_1554_fileupload", "AUpload.pdf");
            Global.ConsoleOutTab("Start praying for the next 25 seconds, beginning at  " + DateTime.Now);
            SeleniumWindowMethods.Sleep(25);
            SeleniumSetMethods.Click(driver, ElementType.CssSelector, ".r-footer > div:nth-child(1) > div:nth-child(1) > button:nth-child(3)");
            Global.ConsoleOutTab("Submit button Clicked " + DateTime.Now);
            SeleniumWindowMethods.Sleep(3);
            SeleniumWindowMethods.WindowType(driver, WinType.Popup);
            SeleniumSetMethods.Click(driver, ElementType.XPath, "(//button[@type='button'])[10]");
            SeleniumWindowMethods.WindowType(driver, WinType.Main);
            if (Global.subjectstate == "California")
            {
                SeleniumWindowMethods.Sleep(1);
                SeleniumSetMethods.Wait(driver, ElementType.CssSelector, "button.r-button.r-button-expand-all");
                SeleniumSetMethods.Click(driver, ElementType.CssSelector, "button.r-button.r-button-expand-all");
                SeleniumSetMethods.Wait(driver, ElementType.Id, "BrokenRuleComments_SaleCompLivingAreaComment");
                SeleniumSetMethods.EnterText(driver, ElementType.Id, "BrokenRuleComments_SaleCompLivingAreaComment", "Test QC Sales Comment");
                SeleniumSetMethods.EnterText(driver, ElementType.Id, "BrokenRuleComments_ListCompLivingAreaComment", "Test QC List Comment");
                SeleniumSetMethods.Click(driver, ElementType.CssSelector, ".r-footer > div:nth-child(1) > div:nth-child(1) > button:nth-child(3)");
                Global.ConsoleOutTab("Submit button Clicked " + DateTime.Now);
                SeleniumWindowMethods.Sleep(10);
                SeleniumWindowMethods.WindowType(driver, WinType.Popup);
                SeleniumSetMethods.Click(driver, ElementType.XPath, "(//button[@type='button'])[10]");
                SeleniumWindowMethods.WindowType(driver, WinType.Main);
            }       
        }
    }
}
