using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.IE;
using OpenQA.Selenium.Firefox;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;

namespace Selenium3
{
    class Form_Val_PNMACBPO
    {
        public static void ClearBPO(Driver driver)
        {
            SeleniumSetMethods.Clear(driver, ElementType.Id, "PennyMac_Subject_OwnerName");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "PennyMac_VendorOrderId");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "Subject_ParcelNumber");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "BpoBrokerDistance");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "BpoBrokerYearsExperience");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "PennyMac_SubjectMarketing_CurrentDisasterDate");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "PennyMac_Subject_ZoningDescription");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "PennyMac_Subject_ZoningDataSource");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "PennyMac_Subject_CurrentUse");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "PennyMac_Subject_ProjectedUse");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "PennyMac_Subject_PropertyComments");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "Marketing_MarketingDays");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "PennyMac_Marketing_NeighborhoodDisasterDate");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "Marketing_SalesLow");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "Marketing_SalesHigh");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "Marketing_TotalSales");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "Marketing_ListingsLow");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "Marketing_ListingsHigh");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "Marketing_TotalListings");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "PennyMac_Marketing_NeighborhoodDescription");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "PennyMac_Marketing_MarketConditionsComment");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "PennyMac_Subject_RedFlagComments");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "Marketing_MarketPriceStabilityPercent");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "Marketing_MarketPriceStabilityMonths");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "Marketing_OwnerPercentage");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "Marketing_TenantPercentage");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "Marketing_ComparableListingsCount");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "Marketing_ReoListingsCount");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "SubjectMarketing_SubjectDom");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "PennyMac_SubjectMarketing_SubjectListPast12MoOriginalListPrice");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "PennyMac_SubjectMarketing_SubjectListPast12MoOriginalListDate");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "PennyMac_SubjectMarketing_SubjectListPast12MoLastListPrice");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "PennyMac_SubjectMarketing_SubjectListPast12MoLastListDate");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "PennyMac_SubjectMarketing_SubjectPast12MoSalePrice");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "PennyMac_SubjectMarketing_SubjectPast12MoSalePriceDate");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "PennyMac_SubjectMarketing_SubjectSoldPast12MoOriginalListPrice");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "PennyMac_SubjectMarketing_SubjectSoldPast12MoOriginalListDate");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "PennyMac_SubjectMarketing_SubjectSoldPast12MoLastListPrice");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "PennyMac_SubjectMarketing_SubjectSoldPast12MoLastListDate");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "SubjectMarketing_ListingBrokerName");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "SubjectMarketing_ListingFirmName");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "SubjectMarketing_ListingBrokerPhone");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "SubjectMarketing_SubjectPropertyUnits");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "SubjectMarketing_SubjectLastSalePrice");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "SubjectMarketing_SubjectLastSaleDate");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "SubjectMarketing_HoaFee");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "SaleComps_0__StreetAddress");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "SaleComps_1__StreetAddress");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "SaleComps_2__StreetAddress");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "SaleComps_0__City");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "SaleComps_1__City");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "SaleComps_2__City");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "SaleComps_0__PostalCode");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "SaleComps_1__PostalCode");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "SaleComps_2__PostalCode");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "SaleComps_0__ProximityDistance");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "SaleComps_1__ProximityDistance");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "SaleComps_2__ProximityDistance");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "PennyMac_SaleComps_0__OriginalListDate");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "PennyMac_SaleComps_1__OriginalListDate");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "PennyMac_SaleComps_2__OriginalListDate");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "PennyMac_SaleComps_0__OriginalListPrice");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "PennyMac_SaleComps_1__OriginalListPrice");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "PennyMac_SaleComps_2__OriginalListPrice");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "SaleComps_0__SalePrice");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "SaleComps_1__SalePrice");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "SaleComps_2__SalePrice");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "SaleComps_0__SaleDate");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "SaleComps_1__SaleDate");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "SaleComps_2__SaleDate");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "SaleComps_0__ListPriceAtSale");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "SaleComps_1__ListPriceAtSale");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "SaleComps_2__ListPriceAtSale");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "SaleComps_0__Dom");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "SaleComps_1__Dom");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "SaleComps_2__Dom");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "PennyMac_Subject_TotalDom");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "PennyMac_SaleComps_0__TotalDom");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "PennyMac_SaleComps_1__TotalDom");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "PennyMac_SaleComps_2__TotalDom");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "PennyMac_Subject_FundingSource");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "PennyMac_SaleComps_0__FundingSource");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "PennyMac_SaleComps_1__FundingSource");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "PennyMac_SaleComps_2__FundingSource");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "PennyMac_SubjectMarketing_SubjectConcessions");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "SaleComps_0__Concessions");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "SaleComps_1__Concessions");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "SaleComps_2__Concessions");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "Subject_LotSize");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "SaleComps_0__LotSize");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "SaleComps_1__LotSize");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "SaleComps_2__LotSize");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "PennyMac_Subject_Site");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "PennyMac_SaleComps_0__Site");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "PennyMac_SaleComps_1__Site");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "PennyMac_SaleComps_2__Site");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "Subject_Units");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "SaleComps_0__Units");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "SaleComps_1__Units");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "SaleComps_2__Units");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "PennyMac_Subject_Design");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "PennyMac_SaleComps_0__Design");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "PennyMac_SaleComps_1__Design");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "PennyMac_SaleComps_2__Design");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "PennyMac_Subject_Age");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "PennyMac_SaleComps_0__Age");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "PennyMac_SaleComps_1__Age");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "PennyMac_SaleComps_2__Age");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "Subject_Rooms");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "SaleComps_0__Rooms");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "SaleComps_1__Rooms");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "SaleComps_2__Rooms");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "Subject_Beds");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "SaleComps_0__Beds");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "SaleComps_1__Beds");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "SaleComps_2__Beds");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "Subject_Baths");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "SaleComps_0__Baths");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "SaleComps_1__Baths");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "SaleComps_2__Baths");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "PennyMac_Subject_PartialBaths");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "PennyMac_SaleComps_0__PartialBaths");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "PennyMac_SaleComps_1__PartialBaths");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "PennyMac_SaleComps_2__PartialBaths");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "Subject_GrossLivingArea");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "SaleComps_0__GrossLivingArea");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "SaleComps_1__GrossLivingArea");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "SaleComps_2__GrossLivingArea");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "Subject_Bsmt");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "SaleComps_0__Bsmt");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "SaleComps_1__Bsmt");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "SaleComps_2__Bsmt");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "PennyMac_Subject_BsmtSqFt");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "PennyMac_Subject_BsmtPercentage");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "PennyMac_SaleComps_0__BsmtSqFt");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "PennyMac_SaleComps_0__BsmtPercentage");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "PennyMac_SaleComps_1__BsmtSqFt");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "PennyMac_SaleComps_1__BsmtPercentage");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "PennyMac_SaleComps_2__BsmtSqFt");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "PennyMac_SaleComps_2__BsmtPercentage");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "Subject_GarageCount");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "SaleComps_0__GarageCount");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "SaleComps_1__GarageCount");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "SaleComps_2__GarageCount");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "PennyMac_Subject_PoolSpa");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "PennyMac_SaleComps_0__PoolSpa");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "PennyMac_SaleComps_1__PoolSpa");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "PennyMac_SaleComps_2__PoolSpa");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "Subject_Extras");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "SaleComps_0__Extras");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "SaleComps_1__Extras");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "SaleComps_2__Extras");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "PennyMac_SaleComps_0__HoaFee");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "PennyMac_SaleComps_1__HoaFee");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "PennyMac_SaleComps_2__HoaFee");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "Repairs_0__Description");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "Repairs_0__Amount");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "PennyMac_Marketing_MarketYearBuilt");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "PennyMac_Marketing_ClosedSalesPast6Mo");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "PennyMac_Marketing_MarketGrossLivingArea");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "PennyMac_Marketing_AbsorptionRatePast6Mo");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "PennyMac_Marketing_MarketLotSize");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "PennyMac_Marketing_PendingSalesCount");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "PennyMac_Marketing_MarketBeds");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "PennyMac_Marketing_SupplyMonths");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "PennyMac_Marketing_MarketBaths");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "PennyMac_Marketing_MarketUnits");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "PennyMac_Marketing_AvgListPricePast3Mo");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "PennyMac_Marketing_AvgListPricePast6Mo");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "PennyMac_Marketing_ComparableSalesSearchRadius");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "PennyMac_Marketing_AvgSalePricePast3Mo");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "PennyMac_Marketing_AvgSalePricePast6Mo");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "PennyMac_Marketing_SaleListRatioPast3Mo");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "PennyMac_Marketing_SaleListRatioPast6Mo");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "ListComps_0__StreetAddress");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "ListComps_0__StreetAddress");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "ListComps_1__StreetAddress");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "ListComps_2__StreetAddress");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "ListComps_0__City");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "ListComps_1__City");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "ListComps_2__City");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "ListComps_0__PostalCode");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "ListComps_1__PostalCode");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "ListComps_2__PostalCode");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "ListComps_0__ProximityDistance");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "ListComps_1__ProximityDistance");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "ListComps_2__ProximityDistance");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "ListComps_0__OriginalListPrice");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "ListComps_1__OriginalListPrice");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "ListComps_2__OriginalListPrice");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "ListComps_0__ListPrice");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "ListComps_1__ListPrice");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "ListComps_2__ListPrice");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "ListComps_0__Concessions");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "ListComps_1__Concessions");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "ListComps_2__Concessions");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "ListComps_0__Dom");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "ListComps_1__Dom");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "ListComps_2__Dom");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "PennyMac_ListComps_0__FundingSource");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "PennyMac_ListComps_1__FundingSource");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "PennyMac_ListComps_2__FundingSource");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "ListComps_0__LotSize");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "ListComps_1__LotSize");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "ListComps_2__LotSize");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "PennyMac_ListComps_0__Site");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "PennyMac_ListComps_1__Site");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "PennyMac_ListComps_2__Site");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "ListComps_0__Units");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "ListComps_1__Units");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "ListComps_2__Units");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "PennyMac_ListComps_0__Design");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "PennyMac_ListComps_1__Design");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "PennyMac_ListComps_2__Design");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "PennyMac_ListComps_0__Age");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "PennyMac_ListComps_1__Age");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "PennyMac_ListComps_2__Age");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "ListComps_0__Rooms");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "ListComps_1__Rooms");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "ListComps_2__Rooms");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "ListComps_0__Beds");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "ListComps_1__Beds");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "ListComps_2__Beds");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "ListComps_0__Baths");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "ListComps_1__Baths");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "ListComps_2__Baths");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "PennyMac_ListComps_0__PartialBaths");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "PennyMac_ListComps_1__PartialBaths");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "PennyMac_ListComps_2__PartialBaths");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "ListComps_0__GrossLivingArea");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "ListComps_1__GrossLivingArea");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "ListComps_2__GrossLivingArea");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "ListComps_0__Bsmt");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "ListComps_1__Bsmt");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "ListComps_2__Bsmt");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "PennyMac_ListComps_0__BsmtSqFt");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "PennyMac_ListComps_0__BsmtPercentage");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "PennyMac_ListComps_1__BsmtSqFt");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "PennyMac_ListComps_1__BsmtPercentage");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "PennyMac_ListComps_2__BsmtSqFt");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "PennyMac_ListComps_2__BsmtPercentage");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "ListComps_0__GarageCount");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "ListComps_1__GarageCount");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "ListComps_2__GarageCount");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "PennyMac_ListComps_0__PoolSpa");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "PennyMac_ListComps_1__PoolSpa");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "PennyMac_ListComps_2__PoolSpa");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "ListComps_0__Extras");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "ListComps_1__Extras");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "ListComps_2__Extras");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "PennyMac_ListComps_0__HoaFee");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "PennyMac_ListComps_1__HoaFee");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "PennyMac_ListComps_2__HoaFee");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "SaleComps_0__Comment");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "SaleComps_1__Comment");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "SaleComps_2__Comment");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "ListComps_0__Comment");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "ListComps_1__Comment");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "ListComps_2__Comment");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "QuickSaleListPrice");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "QuickSaleValue");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "PennyMac_AsIsDays");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "AsisListPrice");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "AsIsValue");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "PennyMac_RepairedDays");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "RepairedListPrice");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "RepairedValue");
            SeleniumSetMethods.Clear(driver, ElementType.Id, "ProviderComments");
        }

        public static void CompleteBPO(Driver driver)
        {
            SeleniumSetMethods.Click(driver, ElementType.Id, "Subject_InspectionDate");
            SeleniumSetMethods.Click(driver, ElementType.XPath, "(//button[@type='button'])[2]");
            SeleniumSetMethods.Click(driver, ElementType.Id, "PennyMac_Subject_IsPropertySecure_0");
            SeleniumSetMethods.Click(driver, ElementType.Id, "PennyMac_SubjectMarketing_IsNewConstruction_1");
            SeleniumSetMethods.Click(driver, ElementType.Id, "PennyMac_SubjectMarketing_IsCurrentDisaster_1");
            SeleniumSetMethods.Click(driver, ElementType.Id, "PennyMac_Subject_ZoningDescription");
            SeleniumSetMethods.Click(driver, ElementType.Id, "Subject_LocationType_1");
            SeleniumSetMethods.Click(driver, ElementType.Id, "Marketing_MarketingDays");
            SeleniumSetMethods.Click(driver, ElementType.Id, "PennyMac_Marketing_ReoTrend_1");
            SeleniumSetMethods.Click(driver, ElementType.Id, "PennyMac_Marketing_MarketTimingTrend_1");
            SeleniumSetMethods.Click(driver, ElementType.Id, "PennyMac_Marketing_PrimaryOccupant_0");
            SeleniumSetMethods.Click(driver, ElementType.Id, "PennyMac_Marketing_IsIndustrialWithinQtrMile_1");
            SeleniumSetMethods.Click(driver, ElementType.Id, "PennyMac_Marketing_VacancyPercentage_2");
            SeleniumSetMethods.Click(driver, ElementType.Id, "PennyMac_Marketing_IsNeighborhoodNewConstruction_1");
            SeleniumSetMethods.Click(driver, ElementType.Id, "PennyMac_Marketing_IsDisasterEvidence_1");
            SeleniumSetMethods.Click(driver, ElementType.Id, "Marketing_SalesLow");
            SeleniumSetMethods.Click(driver, ElementType.Id, "Marketing_ListingsLow");
            SeleniumSetMethods.Click(driver, ElementType.Id, "PennyMac_Marketing_NeighborhoodDescription");
            SeleniumSetMethods.Click(driver, ElementType.Id, "PennyMac_Subject_IsRedFlagDamaged_1");
            SeleniumSetMethods.Click(driver, ElementType.Id, "PennyMac_Subject_IsRedFlagConstruction_1");
            SeleniumSetMethods.Click(driver, ElementType.Id, "PennyMac_Subject_IsRedFlagEnvironmental_0");
            SeleniumSetMethods.Click(driver, ElementType.Id, "PennyMac_Subject_IsRedFlagZoning_0");
            SeleniumSetMethods.Click(driver, ElementType.Id, "PennyMac_Subject_IsRedFlagMarketActivity_0");
            SeleniumSetMethods.Click(driver, ElementType.Id, "PennyMac_Subject_IsRedFlagStigma_1");
            SeleniumSetMethods.Click(driver, ElementType.Id, "PennyMac_Subject_IsRedFlagOther_0");
            SeleniumSetMethods.Click(driver, ElementType.Id, "Marketing_MarketConditions_1");
            SeleniumSetMethods.Click(driver, ElementType.Id, "Marketing_MarketPriceStability_2");
            SeleniumSetMethods.Click(driver, ElementType.Id, "Marketing_MarketPriceStabilityPercent");
            SeleniumSetMethods.Click(driver, ElementType.Id, "Marketing_ComparableSupply_1");
            SeleniumSetMethods.Click(driver, ElementType.Id, "Marketing_OwnerPercentage");
            SeleniumSetMethods.Click(driver, ElementType.Id, "PennyMac_SubjectMarketing_ListingStatusPast12Mo_1");
            SeleniumSetMethods.Click(driver, ElementType.Id, "SubjectMarketing_SubjectDom");
            SeleniumSetMethods.Click(driver, ElementType.Id, "PennyMac_SubjectMarketing_SubjectListPast12MoOriginalListDate");
            SeleniumWindowMethods.Sleep(1);
            SeleniumSetMethods.Wait(driver, ElementType.LinkText, "1");
            SeleniumSetMethods.Click(driver, ElementType.LinkText, "1");
            SeleniumSetMethods.Click(driver, ElementType.Id, "PennyMac_SubjectMarketing_SubjectListPast12MoLastListDate");
            SeleniumWindowMethods.Sleep(1);
            SeleniumSetMethods.Wait(driver, ElementType.LinkText, "1");
            SeleniumSetMethods.Click(driver, ElementType.LinkText, "1");
            SeleniumSetMethods.Click(driver, ElementType.Id, "PennyMac_SubjectMarketing_IsSubjectSoldPast12Mo_0");
            SeleniumSetMethods.Click(driver, ElementType.Id, "PennyMac_SubjectMarketing_SubjectPast12MoSalePrice");
            SeleniumSetMethods.Click(driver, ElementType.Id, "PennyMac_SubjectMarketing_SubjectPast12MoSalePriceDate");
            SeleniumWindowMethods.Sleep(1);
            SeleniumSetMethods.Wait(driver, ElementType.LinkText, "1");
            SeleniumSetMethods.Click(driver, ElementType.LinkText, "1");
            SeleniumSetMethods.Click(driver, ElementType.Id, "PennyMac_SubjectMarketing_SubjectSoldPast12MoOriginalListDate");
            SeleniumWindowMethods.Sleep(1);
            SeleniumSetMethods.Wait(driver, ElementType.LinkText, "1");
            SeleniumSetMethods.Click(driver, ElementType.LinkText, "1");
            SeleniumSetMethods.Click(driver, ElementType.Id, "PennyMac_SubjectMarketing_SubjectSoldPast12MoLastListPrice");
            SeleniumSetMethods.Click(driver, ElementType.Id, "PennyMac_SubjectMarketing_SubjectSoldPast12MoLastListDate");
            SeleniumWindowMethods.Sleep(1);
            SeleniumSetMethods.Wait(driver, ElementType.LinkText, "1");
            SeleniumSetMethods.Click(driver, ElementType.LinkText, "1");
            SeleniumSetMethods.Click(driver, ElementType.Id, "SubjectMarketing_SubjectPropertyUnits");
            SeleniumSetMethods.Click(driver, ElementType.Id, "SubjectMarketing_SubjectLastSalePrice");
            SeleniumSetMethods.Click(driver, ElementType.Id, "SubjectMarketing_SubjectLastSaleDate");
            SeleniumSetMethods.Click(driver, ElementType.Id, "SubjectMarketing_SubjectLastSaleDate");
            SeleniumWindowMethods.Sleep(1);
            SeleniumSetMethods.Wait(driver, ElementType.LinkText, "1");
            SeleniumSetMethods.Click(driver, ElementType.LinkText, "1");
            SeleniumSetMethods.Click(driver, ElementType.Id, "SubjectMarketing_SubjectOccupancyStatus_1");
            SeleniumSetMethods.Click(driver, ElementType.Id, "SubjectMarketing_OwnershipStatus_0");
            SeleniumSetMethods.Click(driver, ElementType.Id, "SaleComps_0__PostalCode");
            SeleniumSetMethods.Click(driver, ElementType.Id, "PennyMac_SaleComps_0__OriginalListDate");
            SeleniumWindowMethods.Sleep(1);
            SeleniumSetMethods.Wait(driver, ElementType.LinkText, "1");
            SeleniumSetMethods.Click(driver, ElementType.LinkText, "1");
            SeleniumSetMethods.Click(driver, ElementType.Id, "PennyMac_SaleComps_1__OriginalListDate");
            SeleniumWindowMethods.Sleep(1);
            SeleniumSetMethods.Wait(driver, ElementType.LinkText, "1");
            SeleniumSetMethods.Click(driver, ElementType.LinkText, "1");
            SeleniumSetMethods.Click(driver, ElementType.Id, "PennyMac_SaleComps_2__OriginalListDate");
            SeleniumWindowMethods.Sleep(1);
            SeleniumSetMethods.Wait(driver, ElementType.LinkText, "1");
            SeleniumSetMethods.Click(driver, ElementType.LinkText, "1");
            SeleniumSetMethods.Click(driver, ElementType.Id, "PennyMac_SaleComps_1__OriginalListPrice");
            SeleniumSetMethods.Click(driver, ElementType.Id, "SaleComps_0__SaleDate");
            SeleniumWindowMethods.Sleep(1);
            SeleniumSetMethods.Wait(driver, ElementType.LinkText, "1");
            SeleniumSetMethods.Click(driver, ElementType.LinkText, "1");
            SeleniumSetMethods.Click(driver, ElementType.Id, "SaleComps_1__SaleDate");
            SeleniumWindowMethods.Sleep(1);
            SeleniumSetMethods.Wait(driver, ElementType.LinkText, "1");
            SeleniumSetMethods.Click(driver, ElementType.LinkText, "1");
            SeleniumSetMethods.Click(driver, ElementType.Id, "SaleComps_2__SaleDate");
            SeleniumWindowMethods.Sleep(1);
            SeleniumSetMethods.Wait(driver, ElementType.LinkText, "1");
            SeleniumSetMethods.Click(driver, ElementType.LinkText, "1");
            SeleniumSetMethods.Click(driver, ElementType.Id, "SaleComps_0__Dom");
            SeleniumSetMethods.Click(driver, ElementType.Id, "PennyMac_Subject_IsDistressedSale_1");
            SeleniumSetMethods.Click(driver, ElementType.Id, "PennyMac_SaleComps[0]_IsDistressedSale_1");
            SeleniumSetMethods.Click(driver, ElementType.Id, "PennyMac_SaleComps[1]_IsDistressedSale_0");
            SeleniumSetMethods.Click(driver, ElementType.Id, "PennyMac_SaleComps[2]_IsDistressedSale_1");
            SeleniumSetMethods.Click(driver, ElementType.Id, "Subject_LotSize");
            SeleniumSetMethods.Click(driver, ElementType.Id, "Subject_Units");
            SeleniumSetMethods.Click(driver, ElementType.Id, "Subject_Rooms");
            SeleniumSetMethods.Click(driver, ElementType.Id, "Subject_GarageCount");
            SeleniumSetMethods.Click(driver, ElementType.Id, "SaleComps_1__GarageCount");
            SeleniumSetMethods.Click(driver, ElementType.Id, "SaleComps_2__GarageCount");
            SeleniumSetMethods.Click(driver, ElementType.Id, "PennyMac_Subject_PoolSpa");
            SeleniumSetMethods.Click(driver, ElementType.Id, "PennyMac_SaleComps_0__HoaFee");
            SeleniumSetMethods.Click(driver, ElementType.Id, "PennyMac_SaleComps_0__Comparability");
            SeleniumSetMethods.Click(driver, ElementType.Id, "PennyMac_Marketing_MarketYearBuilt");
            SeleniumSetMethods.Click(driver, ElementType.Id, "PennyMac_Marketing_SaleListRatioPast3Mo");
            SeleniumSetMethods.Click(driver, ElementType.Id, "PennyMac_ListComps_0__OriginalListDate");
            SeleniumWindowMethods.Sleep(1);
            SeleniumSetMethods.Wait(driver, ElementType.LinkText, "1");
            SeleniumSetMethods.Click(driver, ElementType.LinkText, "1");
            SeleniumSetMethods.Click(driver, ElementType.Id, "PennyMac_ListComps_1__OriginalListDate");
            SeleniumSetMethods.Click(driver, ElementType.CssSelector, "span.ui-icon.ui-icon-circle-triangle-w");
            SeleniumWindowMethods.Sleep(1);
            SeleniumSetMethods.Wait(driver, ElementType.LinkText, "17");
            SeleniumSetMethods.Click(driver, ElementType.LinkText, "17");
            SeleniumSetMethods.Click(driver, ElementType.Id, "PennyMac_ListComps_2__OriginalListDate");
            SeleniumWindowMethods.Sleep(1);
            SeleniumSetMethods.Wait(driver, ElementType.LinkText, "15");
            SeleniumSetMethods.Click(driver, ElementType.LinkText, "15");
            SeleniumSetMethods.Click(driver, ElementType.Id, "ListComps_0__OriginalListPrice");
            SeleniumSetMethods.Click(driver, ElementType.Id, "ListComps_0__Dom");
            SeleniumSetMethods.Click(driver, ElementType.Id, "PennyMac_ListComps[0]_IsDistressedSale_1");
            SeleniumSetMethods.Click(driver, ElementType.Id, "PennyMac_ListComps[1]_IsDistressedSale_0");
            SeleniumSetMethods.Click(driver, ElementType.Id, "PennyMac_ListComps[2]_IsDistressedSale_1");
            SeleniumSetMethods.Click(driver, ElementType.Id, "ListComps_0__LotSize");
            SeleniumSetMethods.Click(driver, ElementType.Id, "ListComps_0__Units");
            SeleniumSetMethods.Click(driver, ElementType.Id, "PennyMac_ListComps_0__Age");
            SeleniumSetMethods.Click(driver, ElementType.Id, "ListComps_0__Rooms");
            SeleniumSetMethods.Click(driver, ElementType.Id, "ListComps_0__GrossLivingArea");
            SeleniumSetMethods.Click(driver, ElementType.Id, "PennyMac_ListComps_0__BsmtSqFt");
            SeleniumSetMethods.Click(driver, ElementType.Id, "ListComps_0__GarageCount");
            SeleniumSetMethods.Click(driver, ElementType.Id, "ListComps_1__GarageType");
            SeleniumSetMethods.Click(driver, ElementType.Id, "ListComps_1__GarageCount");
            SeleniumSetMethods.Click(driver, ElementType.Id, "ListComps_2__GarageType");
            SeleniumSetMethods.Click(driver, ElementType.Id, "ListComps_2__GarageCount");
            SeleniumSetMethods.Click(driver, ElementType.Id, "PennyMac_ListComps_0__PoolSpa");
            SeleniumSetMethods.Click(driver, ElementType.Id, "PennyMac_ListComps_0__HoaFee");
            SeleniumSetMethods.Click(driver, ElementType.Id, "QuickSaleListPrice");
            SeleniumSetMethods.Click(driver, ElementType.Id, "PennyMac_AsIsDays");
            SeleniumSetMethods.Click(driver, ElementType.Id, "ProviderComments");
            // Enter Text
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "PennyMac_Subject_OwnerName", "Owner");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "PennyMac_VendorOrderId", "123-66");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "Subject_ParcelNumber", "123-333-55");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "BpoBrokerDistance", "15");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "BpoBrokerYearsExperience", "15");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "PennyMac_Subject_ZoningDescription", "zone");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "PennyMac_Subject_ZoningDataSource", "Zone data");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "PennyMac_Subject_CurrentUse", "Current use: Residential");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "PennyMac_Subject_ProjectedUse", "Project use :Residential");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "PennyMac_Subject_PropertyComments", "subject comments: Residential");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "PennyMac_Marketing_MedianRent", "2500");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "Marketing_MarketingDays", "90");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "Marketing_SalesLow", "350000");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "Marketing_SalesHigh", "425000");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "Marketing_TotalSales", "5");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "Marketing_ListingsLow", "375000");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "Marketing_ListingsHigh", "430000");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "Marketing_TotalListings", "3");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "PennyMac_Marketing_NeighborhoodDescription", "Neighborhood Description: tests");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "PennyMac_Marketing_MarketConditionsComment", "Marketconditions: Test");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "PennyMac_Subject_RedFlagComments", "RED flags: Comments");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "Marketing_MarketPriceStabilityPercent", "10");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "Marketing_MarketPriceStabilityMonths", "24");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "Marketing_OwnerPercentage", "50");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "Marketing_TenantPercentage", "40");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "Marketing_ComparableListingsCount", "4");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "Marketing_ReoListingsCount", "0");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "SubjectMarketing_SubjectDom", "45");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "PennyMac_SubjectMarketing_SubjectListPast12MoOriginalListPrice", "475000");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "PennyMac_SubjectMarketing_SubjectListPast12MoLastListPrice", "470000");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "PennyMac_SubjectMarketing_SubjectPast12MoSalePrice", "575000");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "PennyMac_SubjectMarketing_SubjectSoldPast12MoOriginalListPrice", "600000");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "PennyMac_SubjectMarketing_SubjectSoldPast12MoLastListPrice", "580000");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "SubjectMarketing_ListingBrokerName", "test broker");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "SubjectMarketing_ListingFirmName", "service corp");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "SubjectMarketing_ListingBrokerPhone", "800-963-9999");
            SeleniumSetMethods.SelectDropDown(driver, ElementType.Id, "SubjectMarketing_SubjectPropertyType", "Single Family");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "SubjectMarketing_SubjectPropertyUnits", "1");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "SubjectMarketing_SubjectLastSalePrice", "576000");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "SubjectMarketing_HoaFee", "250.33");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "SaleComps_0__StreetAddress", Global.sc1street);
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "SaleComps_1__StreetAddress", Global.sc2street);
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "SaleComps_2__StreetAddress", Global.sc3street);
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "SaleComps_0__City", Global.sc1city);
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "SaleComps_1__City", Global.sc2city);
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "SaleComps_2__City", Global.sc3city);
            SeleniumSetMethods.SelectDropDown(driver, ElementType.Id, "SaleComps_0__State", Global.sc1state);
            SeleniumSetMethods.SelectDropDown(driver, ElementType.Id, "SaleComps_1__State", Global.sc2state);
            SeleniumSetMethods.SelectDropDown(driver, ElementType.Id, "SaleComps_2__State", Global.sc3state);
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "SaleComps_0__PostalCode", Global.sc1zipcode);
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "SaleComps_1__PostalCode", Global.sc2zipcode);
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "SaleComps_2__PostalCode", Global.sc3zipcode);
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "SaleComps_0__ProximityDistance", "1");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "SaleComps_1__ProximityDistance", "1");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "SaleComps_2__ProximityDistance", "1");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "PennyMac_SaleComps_0__OriginalListPrice", "470000");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "PennyMac_SaleComps_1__OriginalListPrice", "450000");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "PennyMac_SaleComps_2__OriginalListPrice", "440000");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "SaleComps_0__SalePrice", "450000");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "SaleComps_1__SalePrice", "425000");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "SaleComps_2__SalePrice", "425000");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "SaleComps_0__ListPriceAtSale", "450000");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "SaleComps_1__ListPriceAtSale", "430000");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "SaleComps_2__ListPriceAtSale", "425000");
            SeleniumSetMethods.SelectDropDown(driver, ElementType.Id, "Subject_DataSource", "MLS");
            SeleniumSetMethods.SelectDropDown(driver, ElementType.Id, "SaleComps_0__DataSource", "Appraisal");
            SeleniumSetMethods.SelectDropDown(driver, ElementType.Id, "SaleComps_1__DataSource", "MLS");
            SeleniumSetMethods.SelectDropDown(driver, ElementType.Id, "SaleComps_2__DataSource", "Appraisal");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "SaleComps_0__Dom", "90");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "SaleComps_1__Dom", "80");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "SaleComps_2__Dom", "75");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "PennyMac_Subject_TotalDom", "45");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "PennyMac_SaleComps_0__TotalDom", "95");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "PennyMac_SaleComps_1__TotalDom", "80");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "PennyMac_SaleComps_2__TotalDom", "75");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "PennyMac_Subject_FundingSource", "sub fund");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "PennyMac_SaleComps_0__FundingSource", "s1 fund");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "PennyMac_SaleComps_1__FundingSource", "s2 fund");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "PennyMac_SaleComps_2__FundingSource", "s3 fund");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "PennyMac_SubjectMarketing_SubjectConcessions", "sub salecon");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "SaleComps_0__Concessions", "s1 concession");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "SaleComps_1__Concessions", "s2 concession");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "SaleComps_2__Concessions", "s3 concession");
            SeleniumSetMethods.SelectDropDown(driver, ElementType.Id, "SaleComps_0__LocationType", "Suburban");
            SeleniumSetMethods.SelectDropDown(driver, ElementType.Id, "SaleComps_1__LocationType", "Urban");
            SeleniumSetMethods.SelectDropDown(driver, ElementType.Id, "SaleComps_2__LocationType", "Suburban");
            SeleniumSetMethods.SelectDropDown(driver, ElementType.Id, "LotSizeUnitType", "Sq. Ft.");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "Subject_LotSize", "6000");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "SaleComps_0__LotSize", "4500");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "SaleComps_1__LotSize", "5750");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "SaleComps_2__LotSize", "8500");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "PennyMac_Subject_Site", "1");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "PennyMac_SaleComps_0__Site", "1");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "PennyMac_SaleComps_1__Site", "1");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "PennyMac_SaleComps_2__Site", "1");
            SeleniumSetMethods.SelectDropDown(driver, ElementType.Id, "PennyMac_SaleComps_0__PropertyType", "Single Family");
            SeleniumSetMethods.SelectDropDown(driver, ElementType.Id, "PennyMac_SaleComps_1__PropertyType", "Single Family");
            SeleniumSetMethods.SelectDropDown(driver, ElementType.Id, "PennyMac_SaleComps_2__PropertyType", "Single Family");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "Subject_Units", "1");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "SaleComps_0__Units", "1");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "SaleComps_1__Units", "1");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "SaleComps_2__Units", "1");
            SeleniumSetMethods.SelectDropDown(driver, ElementType.Id, "PennyMac_Subject_ConstructionType", "Stone");
            SeleniumSetMethods.SelectDropDown(driver, ElementType.Id, "PennyMac_SaleComps_0__ConstructionType", "Wood");
            SeleniumSetMethods.SelectDropDown(driver, ElementType.Id, "PennyMac_SaleComps_1__ConstructionType", "Other");
            SeleniumSetMethods.SelectDropDown(driver, ElementType.Id, "PennyMac_SaleComps_2__ConstructionType", "Brick");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "PennyMac_Subject_Design", "sub design");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "PennyMac_SaleComps_0__Design", "s1 design");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "PennyMac_SaleComps_1__Design", "s2 design");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "PennyMac_SaleComps_2__Design", "s3 design");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "PennyMac_Subject_Age", "20");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "PennyMac_SaleComps_0__Age", "22");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "PennyMac_SaleComps_1__Age", "23");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "PennyMac_SaleComps_2__Age", "24");
            SeleniumSetMethods.SelectDropDown(driver, ElementType.Id, "PennyMac_Subject_ViewQualityDescription", "Adverse");
            SeleniumSetMethods.SelectDropDown(driver, ElementType.Id, "PennyMac_SaleComps_0__ViewQualityDescription", "Neutral");
            SeleniumSetMethods.SelectDropDown(driver, ElementType.Id, "PennyMac_SaleComps_1__ViewQualityDescription", "Neutral");
            SeleniumSetMethods.SelectDropDown(driver, ElementType.Id, "PennyMac_SaleComps_2__ViewQualityDescription", "Neutral");
            SeleniumSetMethods.SelectDropDown(driver, ElementType.Id, "PennyMac_SaleComps_0__ViewComparison", "Good");
            SeleniumSetMethods.SelectDropDown(driver, ElementType.Id, "PennyMac_SaleComps_1__ViewComparison", "Satisfactory");
            SeleniumSetMethods.SelectDropDown(driver, ElementType.Id, "PennyMac_SaleComps_2__ViewComparison", "Poor");
            SeleniumSetMethods.SelectDropDown(driver, ElementType.Id, "Subject_Condition", "Excellent");
            SeleniumSetMethods.SelectDropDown(driver, ElementType.Id, "SaleComps_0__Condition", "Good");
            SeleniumSetMethods.SelectDropDown(driver, ElementType.Id, "SaleComps_1__Condition", "Average");
            SeleniumSetMethods.SelectDropDown(driver, ElementType.Id, "SaleComps_2__Condition", "Fair");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "Subject_Rooms", "8");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "SaleComps_0__Rooms", "9");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "SaleComps_1__Rooms", "9");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "SaleComps_2__Rooms", "7");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "Subject_Beds", "5");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "SaleComps_0__Beds", "4");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "SaleComps_1__Beds", "5");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "SaleComps_2__Beds", "4");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "Subject_Baths", "3");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "SaleComps_0__Baths", "3");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "SaleComps_1__Baths", "2");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "SaleComps_2__Baths", "3");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "PennyMac_Subject_PartialBaths", "1");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "PennyMac_SaleComps_0__PartialBaths", "0");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "PennyMac_SaleComps_1__PartialBaths", "1");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "PennyMac_SaleComps_2__PartialBaths", "1");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "Subject_GrossLivingArea", "2500");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "SaleComps_0__GrossLivingArea", "2500");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "SaleComps_1__GrossLivingArea", "2500");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "SaleComps_2__GrossLivingArea", "2750");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "Subject_Bsmt", "sub base");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "SaleComps_0__Bsmt", "s1 basement");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "SaleComps_1__Bsmt", "s2 basement");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "SaleComps_2__Bsmt", "s3 basement");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "PennyMac_Subject_BsmtSqFt", "500");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "PennyMac_Subject_BsmtPercentage", "10");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "PennyMac_SaleComps_0__BsmtSqFt", "400");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "PennyMac_SaleComps_0__BsmtPercentage", "0");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "PennyMac_SaleComps_1__BsmtSqFt", "0");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "PennyMac_SaleComps_1__BsmtPercentage", "0");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "PennyMac_SaleComps_2__BsmtSqFt", "250");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "PennyMac_SaleComps_2__BsmtPercentage", "15");
            SeleniumSetMethods.SelectDropDown(driver, ElementType.Id, "Subject_GarageType", "Carport");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "Subject_GarageCount", "2");
            SeleniumSetMethods.SelectDropDown(driver, ElementType.Id, "SaleComps_0__GarageType", "Carport");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "SaleComps_0__GarageCount", "2");
            SeleniumSetMethods.SelectDropDown(driver, ElementType.Id, "SaleComps_1__GarageType", "Carport");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "SaleComps_1__GarageCount", "2");
            SeleniumSetMethods.SelectDropDown(driver, ElementType.Id, "SaleComps_2__GarageType", "Carport");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "SaleComps_2__GarageCount", "2");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "PennyMac_Subject_PoolSpa", "sub pool");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "PennyMac_SaleComps_0__PoolSpa", "s1 pool");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "PennyMac_SaleComps_1__PoolSpa", "s2 pool");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "PennyMac_SaleComps_2__PoolSpa", "s3 pool");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "Subject_Extras", "sub other");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "SaleComps_0__Extras", "s1 other");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "SaleComps_1__Extras", "s2 other");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "SaleComps_2__Extras", "s3 other");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "PennyMac_SaleComps_0__HoaFee", "180");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "PennyMac_SaleComps_1__HoaFee", "550.85");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "PennyMac_SaleComps_2__HoaFee", "550");
            SeleniumSetMethods.SelectDropDown(driver, ElementType.Id, "PennyMac_SaleComps_0__Comparability", "Good");
            SeleniumSetMethods.SelectDropDown(driver, ElementType.Id, "PennyMac_SaleComps_1__Comparability", "Satisfactory");
            SeleniumSetMethods.SelectDropDown(driver, ElementType.Id, "PennyMac_SaleComps_2__Comparability", "Poor");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "Repairs_0__Description", "repair");
            SeleniumSetMethods.SelectDropDown(driver, ElementType.Id, "PennyMac_Repairs_0__RepairType", "Interior");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "Repairs_0__Amount", "100.23");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "PennyMac_Marketing_MarketYearBuilt", "1999");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "PennyMac_Marketing_ClosedSalesPast6Mo", "3");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "PennyMac_Marketing_MarketGrossLivingArea", "1800");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "PennyMac_Marketing_AbsorptionRatePast6Mo", "20");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "PennyMac_Marketing_MarketLotSize", "6500");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "PennyMac_Marketing_PendingSalesCount", "3");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "PennyMac_Marketing_MarketBeds", "4");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "PennyMac_Marketing_SupplyMonths", "2");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "PennyMac_Marketing_MarketBaths", "2.5");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "PennyMac_Marketing_MarketUnits", "1");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "PennyMac_Marketing_AvgListPricePast3Mo", "400000");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "PennyMac_Marketing_AvgListPricePast6Mo", "375000.00");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "PennyMac_Marketing_ComparableSalesSearchRadius", "15.3");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "PennyMac_Marketing_AvgSalePricePast3Mo", "410000");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "PennyMac_Marketing_AvgSalePricePast6Mo", "380000");
            SeleniumSetMethods.SelectDropDown(driver, ElementType.Id, "PennyMac_Marketing_MarketPropertyType", "Single Family");
            SeleniumSetMethods.SelectDropDown(driver, ElementType.Id, "PennyMac_Marketing_ComparableAge", "Last 6 Months");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "PennyMac_Marketing_SaleListRatioPast3Mo", "25");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "PennyMac_Marketing_SaleListRatioPast6Mo", "16");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "ListComps_0__StreetAddress", Global.lc1street);
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "ListComps_1__StreetAddress", Global.lc2street);
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "ListComps_2__StreetAddress", Global.lc3street);
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "ListComps_0__City", Global.lc1city);
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "ListComps_1__City", Global.lc2city);
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "ListComps_2__City", Global.lc3city);
            SeleniumSetMethods.SelectDropDown(driver, ElementType.Id, "ListComps_0__State", Global.lc1state);
            SeleniumSetMethods.SelectDropDown(driver, ElementType.Id, "ListComps_1__State", Global.lc2state);
            SeleniumSetMethods.SelectDropDown(driver, ElementType.Id, "ListComps_2__State", Global.lc3state);
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "ListComps_0__PostalCode", Global.lc1zipcode);
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "ListComps_1__PostalCode", Global.lc2zipcode);
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "ListComps_2__PostalCode", Global.lc3zipcode);
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "ListComps_0__ProximityDistance", "0.4");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "ListComps_1__ProximityDistance", "0.6");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "ListComps_2__ProximityDistance", "0.8");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "ListComps_0__OriginalListPrice", "400000");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "ListComps_1__OriginalListPrice", "410000");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "ListComps_2__OriginalListPrice", "420000");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "ListComps_0__ListPrice", "400000");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "ListComps_1__ListPrice", "409000");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "ListComps_2__ListPrice", "412999");
            SeleniumSetMethods.SelectDropDown(driver, ElementType.Id, "ListComps_0__DataSource", "MLS");
            SeleniumSetMethods.SelectDropDown(driver, ElementType.Id, "ListComps_1__DataSource", "MLS");
            SeleniumSetMethods.SelectDropDown(driver, ElementType.Id, "ListComps_2__DataSource", "MLS");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "ListComps_0__Concessions", "l1 sale conce");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "ListComps_1__Concessions", "l2 salecon");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "ListComps_2__Concessions", "l3salecon");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "ListComps_0__Dom", "25");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "ListComps_1__Dom", "26");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "ListComps_2__Dom", "28");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "PennyMac_ListComps_0__TotalDom", "33");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "PennyMac_ListComps_1__TotalDom", "34");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "PennyMac_ListComps_2__TotalDom", "35");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "PennyMac_ListComps_0__FundingSource", "l1 fund");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "PennyMac_ListComps_1__FundingSource", "l2fund");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "PennyMac_ListComps_2__FundingSource", "l3 fund");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "ListComps_0__LotSize", "6250");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "ListComps_1__LotSize", "5500");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "ListComps_2__LotSize", "5500");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "PennyMac_ListComps_0__Site", "1");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "PennyMac_ListComps_1__Site", "1");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "PennyMac_ListComps_2__Site", "1");
            SeleniumSetMethods.SelectDropDown(driver, ElementType.Id, "PennyMac_ListComps_0__PropertyType", "Single Family");
            SeleniumSetMethods.SelectDropDown(driver, ElementType.Id, "PennyMac_ListComps_1__PropertyType", "Single Family");
            SeleniumSetMethods.SelectDropDown(driver, ElementType.Id, "PennyMac_ListComps_2__PropertyType", "Single Family");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "ListComps_0__Units", "1");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "ListComps_1__Units", "1");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "ListComps_2__Units", "1");
            SeleniumSetMethods.SelectDropDown(driver, ElementType.Id, "PennyMac_ListComps_0__ConstructionType", "Brick");
            SeleniumSetMethods.SelectDropDown(driver, ElementType.Id, "PennyMac_ListComps_1__ConstructionType", "Mix");
            SeleniumSetMethods.SelectDropDown(driver, ElementType.Id, "PennyMac_ListComps_2__ConstructionType", "Stone");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "PennyMac_ListComps_0__Design", "li design");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "PennyMac_ListComps_1__Design", "l2 design");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "PennyMac_ListComps_2__Design", "l3 design");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "PennyMac_ListComps_0__Age", "25");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "PennyMac_ListComps_1__Age", "15");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "PennyMac_ListComps_2__Age", "10");
            SeleniumSetMethods.SelectDropDown(driver, ElementType.Id, "ListComps_0__Condition", "Fair");
            SeleniumSetMethods.SelectDropDown(driver, ElementType.Id, "ListComps_1__Condition", "Good");
            SeleniumSetMethods.SelectDropDown(driver, ElementType.Id, "ListComps_2__Condition", "Poor");
            SeleniumSetMethods.SelectDropDown(driver, ElementType.Id, "PennyMac_ListComps_0__ViewQualityDescription", "Adverse");
            SeleniumSetMethods.SelectDropDown(driver, ElementType.Id, "PennyMac_ListComps_1__ViewQualityDescription", "Neutral");
            SeleniumSetMethods.SelectDropDown(driver, ElementType.Id, "PennyMac_ListComps_2__ViewQualityDescription", "Beneficial");
            SeleniumSetMethods.SelectDropDown(driver, ElementType.Id, "PennyMac_ListComps_0__ViewComparison", "Good");
            SeleniumSetMethods.SelectDropDown(driver, ElementType.Id, "PennyMac_ListComps_1__ViewComparison", "Good");
            SeleniumSetMethods.SelectDropDown(driver, ElementType.Id, "PennyMac_ListComps_2__ViewComparison", "Good");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "ListComps_0__Rooms", "7");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "ListComps_1__Rooms", "6");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "ListComps_2__Rooms", "7");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "ListComps_0__Beds", "4");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "ListComps_1__Beds", "6");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "ListComps_2__Beds", "5");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "ListComps_0__Baths", "3");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "ListComps_1__Baths", "3");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "ListComps_2__Baths", "3");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "PennyMac_ListComps_0__PartialBaths", "1");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "PennyMac_ListComps_1__PartialBaths", "2");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "PennyMac_ListComps_2__PartialBaths", "1");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "ListComps_0__GrossLivingArea", "2750");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "ListComps_1__GrossLivingArea", "2500");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "ListComps_2__GrossLivingArea", "2500");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "ListComps_0__Bsmt", "l1basement");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "ListComps_1__Bsmt", "l2basement");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "ListComps_2__Bsmt", "l3 basement");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "PennyMac_ListComps_0__BsmtSqFt", "0");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "PennyMac_ListComps_0__BsmtPercentage", "0");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "PennyMac_ListComps_1__BsmtSqFt", "500");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "PennyMac_ListComps_1__BsmtPercentage", "100");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "PennyMac_ListComps_2__BsmtSqFt", "150");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "PennyMac_ListComps_2__BsmtPercentage", "20");
            SeleniumSetMethods.SelectDropDown(driver, ElementType.Id, "ListComps_0__GarageType", "Attached");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "ListComps_0__GarageCount", "2");
            SeleniumSetMethods.SelectDropDown(driver, ElementType.Id, "ListComps_1__GarageType", "Detached");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "ListComps_1__GarageCount", "1");
            SeleniumSetMethods.SelectDropDown(driver, ElementType.Id, "ListComps_2__GarageType", "None");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "ListComps_2__GarageCount", "0");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "PennyMac_ListComps_0__PoolSpa", "l1pool");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "PennyMac_ListComps_1__PoolSpa", "l2pool");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "PennyMac_ListComps_2__PoolSpa", "l3pool");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "ListComps_0__Extras", "l1 other");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "ListComps_1__Extras", "l2other");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "ListComps_2__Extras", "l3other");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "PennyMac_ListComps_0__HoaFee", "180");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "PennyMac_ListComps_1__HoaFee", "250");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "PennyMac_ListComps_2__HoaFee", "275");
            SeleniumSetMethods.SelectDropDown(driver, ElementType.Id, "PennyMac_ListComps_0__Comparability", "Good");
            SeleniumSetMethods.SelectDropDown(driver, ElementType.Id, "PennyMac_ListComps_1__Comparability", "Satisfactory");
            SeleniumSetMethods.SelectDropDown(driver, ElementType.Id, "PennyMac_ListComps_2__Comparability", "Poor");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "SaleComps_0__Comment", "sale#1 comments");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "SaleComps_1__Comment", "sale#2 comments");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "SaleComps_2__Comment", "sale#3 comments");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "ListComps_0__Comment", "List1 comments");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "ListComps_1__Comment", "list#2 comments");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "ListComps_2__Comment", "list#3 comments");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "QuickSaleListPrice", "411111");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "QuickSaleValue", "422222");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "PennyMac_AsIsDays", "30");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "AsisListPrice", "433333");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "AsIsValue", "444444");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "PennyMac_RepairedDays", "45");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "RepairedListPrice", "455555");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "RepairedValue", "466666");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "ProviderComments", "comments");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "BrokenRuleComments_SaleCompLotSizeComment", "Testing 123");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "BrokenRuleComments_SaleCompSalePriceComment", "Testing 234");
        }

        public static void Attachments(Driver driver, ENV environment)
        {
            // Add Exterior Attachments to PNMAC Order
            Global.ConsoleOutTab("Begin adding Attachments at " + DateTime.Now);
            if (environment == ENV.QA)
            {
                SeleniumSetMethods.FileUpload(driver, ElementType.Id, "190_1_fileupload", "B1.jpg");
                SeleniumSetMethods.FileUpload(driver, ElementType.Id, "192_1_fileupload", "B2.jpg");
                SeleniumSetMethods.FileUpload(driver, ElementType.Id, "193_1_fileupload", "B3.jpg");
                SeleniumSetMethods.FileUpload(driver, ElementType.Id, "197_1_fileupload", "C1.jpg");
                SeleniumSetMethods.FileUpload(driver, ElementType.Id, "198_1_fileupload", "C2.jpg");
                SeleniumSetMethods.FileUpload(driver, ElementType.Id, "199_1_fileupload", "C3.jpg");
                SeleniumSetMethods.FileUpload(driver, ElementType.Id, "200_1_fileupload", "C4.jpg");
                SeleniumSetMethods.FileUpload(driver, ElementType.Id, "201_1_fileupload", "C5.jpg");
                SeleniumSetMethods.FileUpload(driver, ElementType.Id, "202_1_fileupload", "C6.jpg");
            }
            else if (environment == ENV.UAT)
            {
                SeleniumSetMethods.FileUpload(driver, ElementType.Id, "175_1_fileupload", "B1.jpg");
                SeleniumSetMethods.FileUpload(driver, ElementType.Id, "177_1_fileupload", "B2.jpg");
                SeleniumSetMethods.FileUpload(driver, ElementType.Id, "178_1_fileupload", "B3.jpg");
                SeleniumSetMethods.FileUpload(driver, ElementType.Id, "182_1_fileupload", "C1.jpg");
                SeleniumSetMethods.FileUpload(driver, ElementType.Id, "183_1_fileupload", "C2.jpg");
                SeleniumSetMethods.FileUpload(driver, ElementType.Id, "184_1_fileupload", "C3.jpg");
                SeleniumSetMethods.FileUpload(driver, ElementType.Id, "185_1_fileupload", "C4.jpg");
                SeleniumSetMethods.FileUpload(driver, ElementType.Id, "186_1_fileupload", "C5.jpg");
                SeleniumSetMethods.FileUpload(driver, ElementType.Id, "187_1_fileupload", "C6.jpg");
            }
            // Complete Attachment Section
            SeleniumSetMethods.FileUpload(driver, ElementType.Id, "16_fileupload", "AUpload.pdf");
            SeleniumSetMethods.FileUpload(driver, ElementType.Id, "27_fileupload", "AUpload.pdf");
            SeleniumSetMethods.FileUpload(driver, ElementType.Id, "28_fileupload", "AUpload.pdf");
            SeleniumSetMethods.FileUpload(driver, ElementType.Id, "productUpload_117_fileupload", "AUpload.pdf");
            SeleniumSetMethods.FileUpload(driver, ElementType.Id, "productUpload_124_fileupload", "AUpload.pdf");
            Global.ConsoleOutTab("5 Second Sleep for images to upload");
            SeleniumWindowMethods.Sleep(5);
            SeleniumSetMethods.Wait(driver, ElementType.Id, "btnBpoSave");
            SeleniumSetMethods.Click(driver, ElementType.Id, "btnBpoSave");
            SeleniumWindowMethods.Assertion(driver, Alert.Wait);
            SeleniumWindowMethods.Assertion(driver, Alert.Accept);
            SeleniumWindowMethods.Sleep(2);
            SeleniumSetMethods.Wait(driver, ElementType.Id, "btnBpoSubmit");
            SeleniumSetMethods.Click(driver, ElementType.Id, "btnBpoSubmit");
        }
    }
}
