using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.IE;
using OpenQA.Selenium.Firefox;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;

namespace Selenium3
{
    class Form_REO_FM
    {
        public static void CompleteBPO(Driver driver)
        {
            SeleniumWindowMethods.Sleep(2);
            Global.ConsoleOut("Pause Me");
            SeleniumWindowMethods.Sleep(5);
            SeleniumSetMethods.Click(driver, ElementType.XPath, " //input[@name ='abMcMkt' and @value='s']");
            SeleniumSetMethods.Click(driver, ElementType.XPath, " //input[@name ='abMcEmploy' and @value='i']");
            SeleniumSetMethods.Click(driver, ElementType.XPath, " //input[@name ='abMcPrice' and @value='i']");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abMcPricePerc", "10");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abMcPriceMos", "12");
            SeleniumSetMethods.Click(driver, ElementType.Name, "abMcSupply");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abMcOwnerPerc", "55");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abMcTenentPerc", "20");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abMcCompUnits", "6");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abMcCompLists", "5");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abMcBoards", "0");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abMkLow", "450000");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abMkHigh", "550000");
            SeleniumSetMethods.Click(driver, ElementType.XPath, " //input[@name ='abMkImprove' and @value='a']");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abMkTime", "35");
            SeleniumSetMethods.Click(driver, ElementType.XPath, " //input[@name ='abMkFinTypes' and @value='y']");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abMkFinDesc", "No Financing Issue's @ above property$check11.");
            SeleniumSetMethods.Click(driver, ElementType.XPath, " //input[@name ='abMkOn' and @value='n']");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abMkOnLp", "250,000");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abMkOnDesc", "Test . ~!@#$% = &*()_+=-< d>?\":]{} [;'/.,) <  dfsd > adding  Rest of the Characters. Max allow 100");
            SeleniumSetMethods.Click(driver, ElementType.XPath, " //input[@name ='abMkUnit' and @value='u']");
            SeleniumSetMethods.SelectDropDown(driver, ElementType.Name, "abU1Rooms", "12");
            SeleniumSetMethods.SelectDropDown(driver, ElementType.Name, "abU1Beds", "4");
            SeleniumSetMethods.SelectDropDown(driver, ElementType.Name, "abU1Baths", "3.5");
            SeleniumSetMethods.SelectDropDown(driver, ElementType.Name, "abU1Inspect", "Exterior");
            SeleniumSetMethods.Click(driver, ElementType.Name, "abEnvStruct");
            SeleniumSetMethods.Click(driver, ElementType.Name, "abEnvFlood");
            SeleniumSetMethods.Click(driver, ElementType.Name, "abEnvUnder");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abMkFee", "250");
            SeleniumSetMethods.Click(driver, ElementType.Name, "abMkFeeType");
            SeleniumSetMethods.Click(driver, ElementType.Name, "abMkFeeCur");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abMkFeeDel", "100");
            SeleniumSetMethods.Click(driver, ElementType.Name, "abMkFeeIns");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abMkFeeOth", "test");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abMkAssoc", "Test HOA Association");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abMkAssocPh", "7418529966");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abAddrS1", "1A Test street");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abAddrS2", "21/2 Test corner");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abAddrS3", "3 Main place");
            SeleniumSetMethods.SelectDropDown(driver, ElementType.Name, "abProxS1", "1 Mile");
            SeleniumSetMethods.Click(driver, ElementType.Name, "abCorpS1");
            SeleniumSetMethods.SelectDropDown(driver, ElementType.Name, "abProxS2", "2 Blocks");
            SeleniumSetMethods.SelectDropDown(driver, ElementType.Name, "abProxS3", "1 Mile");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abSpS1", "460000");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abSpS2", "470000");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abSpS3", "480000");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abSaleDtS1", "10/30/2016");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abSaleDtS2", "11/01/2016");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abSaleDtS3", "11/02/2016");
            SeleniumSetMethods.SelectDropDown(driver, ElementType.Name, "abSrce", "MLS");
            SeleniumSetMethods.SelectDropDown(driver, ElementType.Name, "abSrceS1", "TaxRecords");
            SeleniumSetMethods.SelectDropDown(driver, ElementType.Name, "abSrceS2", "MLS");
            SeleniumSetMethods.SelectDropDown(driver, ElementType.Name, "abSrceS3", "Estimated");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abDomS1", "13");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abDomS2", "14");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abDomS3", "15");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abConcS1", "S1 Con");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abConcS1a", "1");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abConcS2", "S#2 Con");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abConcS3", "S#3 Con");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abConcS3a", "-1");
            SeleniumSetMethods.SelectDropDown(driver, ElementType.Name, "abLoc", "Superior");
            SeleniumSetMethods.SelectDropDown(driver, ElementType.Name, "abLocS1", "Superior");
            SeleniumSetMethods.SelectDropDown(driver, ElementType.Name, "abLocS2", "Equal");
            SeleniumSetMethods.SelectDropDown(driver, ElementType.Name, "abLocS3", "Inferior");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abRight", "Fee Simple");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abRightS1", "Fee Simple");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abRightS2", "Fee Simple");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abRightS3", "Fee Simple");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abRightS3a", "1");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abSite", "1");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abSiteS1", "1");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abSiteS1a", "1");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abSiteS2", "1");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abSiteS3", "1");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abView", "sub View");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abViewS1", "S#1 View");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abViewS2", "S#2 View");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abViewS3", "S#3");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abViewS3a", "-2");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abDesign", "Sub Design");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abDesignS1", "S#1 Design");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abDesignS1a", "2");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abDesignS2", "S#2 Design");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abDesignS3", "S#3 Design");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abDesignS3a", "-3");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abQual", "Sub Con");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abQualS1", "S#1 Con");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abQualS1a", "3");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abQualS2", "S#2 Con");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abQualS3", "S#3 Const");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abQualS3a", "-4");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abAge", "10");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abAgeS1", "11");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abAgeS1a", "4");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abAgeS2", "12");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abAgeS3", "14");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abAgeS3a", "-5");
            SeleniumSetMethods.SelectDropDown(driver, ElementType.Name, "abCond", "Good");
            SeleniumSetMethods.SelectDropDown(driver, ElementType.Name, "abCondS1", "Fair");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abCondS1a", "5");
            SeleniumSetMethods.SelectDropDown(driver, ElementType.Name, "abCondS2", "Average");
            SeleniumSetMethods.SelectDropDown(driver, ElementType.Name, "abCondS3", "Fair");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abRooms", "10");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abRoomsS1", "12");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abRoomsS2", "13");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abRoomsS3", "14");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abBeds", "5");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abBedsS1", "6");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abBedsS2", "7");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abBedsS3", "8");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abBaths", "2");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abBathsS2", "2.5");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abBathsS3", "3");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abGla", "1350");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abGlaS1", "1450");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abGlaS2", "1375");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abGlaS3", "1475");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abBsmt", "Sub Basement");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abBsmtS1", "S#1Basement");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abBsmtS1a", "6");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abBsmtS2", "S#2 Basement");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abBsmtS3", "S#3 Basement");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abBsmtS3a", "-2");
            SeleniumSetMethods.SelectDropDown(driver, ElementType.Name, "abUtil", "Yes");
            SeleniumSetMethods.SelectDropDown(driver, ElementType.Name, "abUtilS1", "Yes");
            SeleniumSetMethods.SelectDropDown(driver, ElementType.Name, "abUtilS2", "Yes");
            SeleniumSetMethods.SelectDropDown(driver, ElementType.Name, "abUtilS3", "Yes");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abHeat", "Sub Heat");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abHeatS1", "S#1 Heat");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abHeatS1a", "7");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abHeatS2", "S#2 Heat");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abHeatS3", "S#3 Heat");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abEnergy", "Sub Energy");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abEnergyS1", "S#1 Energy");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abEnergyS2", "S#2 Energy");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abEnergyS3", "S#3 Energy");
            SeleniumSetMethods.SelectDropDown(driver, ElementType.Name, "abGarage", "None");
            SeleniumSetMethods.SelectDropDown(driver, ElementType.Name, "abGarageS1", "None");
            SeleniumSetMethods.SelectDropDown(driver, ElementType.Name, "abGarageS1", "CarPort");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abGarageS1a", "2");
            SeleniumSetMethods.SelectDropDown(driver, ElementType.Name, "abGarageS2", "None");
            SeleniumSetMethods.SelectDropDown(driver, ElementType.Name, "abGarageS2", "CarPort");
            SeleniumSetMethods.SelectDropDown(driver, ElementType.Name, "abGarageS2", "1CarAtt");
            SeleniumSetMethods.SelectDropDown(driver, ElementType.Name, "abGarageS3", "None");
            SeleniumSetMethods.SelectDropDown(driver, ElementType.Name, "abGarageS3", "CarPort");
            SeleniumSetMethods.SelectDropDown(driver, ElementType.Name, "abGarageS3", "1CarAtt");
            SeleniumSetMethods.SelectDropDown(driver, ElementType.Name, "abGarageS3", "2CarAtt");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abPorch", "Sub Porch");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abPorchS1", "S#1 porch");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abPorchS2", "s#2 Porch");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abPorchS3", "S#3 Porch");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abPool", "Sub Fence");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abPoolS1", "S#1 Fence");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abPoolS2", "S#3 Fence");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abPoolS3", "s#3 Fence");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abOther", "Sub other");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abOtherS1", "s1 other");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abOtherS2", "s2 other");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abOtherS2a", "3");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abOtherS3", "s3 other");
            SeleniumSetMethods.Click(driver, ElementType.Id, "btnSaveWork");
            SeleniumSetMethods.Click(driver, ElementType.XPath, "//table[@id='tabBorder2']/tbody/tr[9]/td/table/tbody/tr/td[2]/a/img");
            SeleniumSetMethods.Wait(driver, ElementType.Name, "abRpRec1");
            SeleniumSetMethods.Click(driver, ElementType.XPath, " //input[@name ='abMkBuyer' and @value='o']");
            SeleniumSetMethods.Click(driver, ElementType.XPath, " //input[@name ='abMkStrat' and @value='a']");
            SeleniumSetMethods.Click(driver, ElementType.Name, "abRpRec1");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abRpDesc1", "Paint's");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abRpAmt1", "25");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abRpDesc3", "Cleaning\"s");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abRpAmt3", "50");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abAddrL1", "4");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abAddrL2", "5");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abAddrL3", "6");
            SeleniumSetMethods.SelectDropDown(driver, ElementType.Name, "abProxL1", "1 Block");
            SeleniumSetMethods.Click(driver, ElementType.Name, "abCorpL1");
            SeleniumSetMethods.SelectDropDown(driver, ElementType.Name, "abProxL2", "1 Block");
            SeleniumSetMethods.SelectDropDown(driver, ElementType.Name, "abProxL2", "2 Blocks");
            SeleniumSetMethods.SelectDropDown(driver, ElementType.Name, "abProxL3", "2 Miles");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abSpL1", "425000");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abSpL2", "435000");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abSpL3", "445000");
            // SeleniumSetMethods.SelectDropDown(driver, ElementType.Name, "abSrce", "MLS");
            SeleniumSetMethods.SelectDropDown(driver, ElementType.Name, "abSrceL1", "TaxRecords");
            SeleniumSetMethods.SelectDropDown(driver, ElementType.Name, "abSrceL2", "MLS");
            SeleniumSetMethods.SelectDropDown(driver, ElementType.Name, "abSrceL3", "MLS");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abConcL1", "c1 finance");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abConcL2", "c2 finanace");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abConcL3", "c3 finance");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abDomDt", "30");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abDomL1", "35");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abDomL2", "40");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abDomL3", "45");
            SeleniumSetMethods.SelectDropDown(driver, ElementType.Name, "abLocL1", "Equal");
            SeleniumSetMethods.SelectDropDown(driver, ElementType.Name, "abLocL2", "Inferior");
            SeleniumSetMethods.SelectDropDown(driver, ElementType.Name, "abLocL3", "Superior");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abRightL1", "Fee Simple");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abRightL2", "Fee Simple");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abRightL3", "Fee Simple");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abSiteL1", "2");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abSiteL1a", "10");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abSiteL2", "1");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abSiteL3", "1");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abSiteL3a", "-10");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abViewL1", "c1 view");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abViewL2", "c2 view");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abViewL3", "c3 view");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abDesign", "SUB Design");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abDesignL1", "C1 Design");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abDesignL2", "C2 Design");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abDesignL3", "C3 design");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abQual", "Sub Const");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abQualL1", "c1 Const");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abQualL2", "C2 Const");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abQualL3", "C3 const");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abAgeL1", "15");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abAgeL1a", "-10");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abAgeL2", "10");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abAgeL3", "10");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abAgeL3a", "10");
            SeleniumSetMethods.SelectDropDown(driver, ElementType.Name, "abCondL1", "Average");
            SeleniumSetMethods.SelectDropDown(driver, ElementType.Name, "abCondL2", "Average");
            SeleniumSetMethods.SelectDropDown(driver, ElementType.Name, "abCondL3", "Fair");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abRoomsL1", "11");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abRoomsL2", "12");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abRoomsL3", "12");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abBedsL1", "6");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abBedsL2", "7");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abBedsL3", "6");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abBathsL1", "3");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abBathsL2", "2.5");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abBathsL3", "3");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abGlaL1", "1450");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abGlaL2", "1550");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abGlaL3", "1650");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abBsmtL1", "C1 Basement");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abBsmtL2", "c2 basement");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abBsmtL3", "c3 basement");
            SeleniumSetMethods.SelectDropDown(driver, ElementType.Name, "abUtilL1", "No");
            SeleniumSetMethods.SelectDropDown(driver, ElementType.Name, "abUtilL2", "Yes");
            SeleniumSetMethods.SelectDropDown(driver, ElementType.Name, "abUtilL3", "Yes");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abHeatL1", "c1 heat");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abHeatL2", "C2 heat");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abHeatL3", "c3 heat");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abEnergyL1", "c1 Energy");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abEnergyL2", "c2 Energy");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abEnergyL3", "c3 energy");
            SeleniumSetMethods.SelectDropDown(driver, ElementType.Name, "abGarageL1", "CarPort");
            SeleniumSetMethods.SelectDropDown(driver, ElementType.Name, "abGarageL2", "2CarAtt");
            SeleniumSetMethods.SelectDropDown(driver, ElementType.Name, "abGarageL3", "4CarAtt");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abPorchL1", "C1 Porch");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abPorchL2", "c2 porch");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abPorchL3", "c3 porch");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abPoolL1", "c1 fence");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abPoolL2", "c2 fence");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abPoolL3", "c3 fence");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abOtherL1", "c1 other");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abOtherL2", "c2 other");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abOtherL3", "c3 other");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abMvAsIs", "550000");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abMvAsIsSlp", "511111");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abMvAsIs30Day", "522222");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abMvRep", "575000");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abMvRepSlp", "575111");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abMvRep30Day", "575222");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "txtosAgentNote", "test \n" + "line@2 \n" + "line3 - Test . ~!@#$% = &*()_+=-< d>?\":]{} [;'/.,) <  dfsd > End .");
            SeleniumSetMethods.Click(driver, ElementType.Id, "btnSaveWorkPg2");
            SeleniumWindowMethods.Sleep(1);
        }
    }
}
