using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.IE;
using OpenQA.Selenium.Firefox;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;

namespace Selenium3
{
    class Form_REO_BPO
    {
        public static void CompleteBPO(Driver driver)
        {
            //REO BPO 
            SeleniumWindowMethods.Sleep(2);
            Global.ConsoleOut("Pause Me");
            SeleniumWindowMethods.Sleep(5);
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abNdList", "4");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abNdHouses", "3");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abNdLow", "350000");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abNdHigh", "650000");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abNdClose", "45");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abNdMktTime", "5");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abNdSale", "15");
            SeleniumSetMethods.Click(driver, ElementType.XPath, "//input[@name ='abNdPoo' and @value='f']");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abNdConstr", "No-new construction competition @.Max limit is >54Char");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abNdAssess", "No-special assessmements Pending$.Max limit is >54Chars");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abNdNeg", "Industial Near by");
            SeleniumSetMethods.Click(driver, ElementType.Name, "abNdAppr");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abNdMonthly", "12");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abStyle", "ranch");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abSqFt", "1850");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abRooms", "8");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abBed", "5");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abBath", "2.5");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abRent", "1500");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abBsmt", "250");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abGar", "3");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abLot", "4500");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abAge", "15");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abPrevDom", "45");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abPrevLP", "350000");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abCurrLP", "375000");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abCond", "good");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "txtabMktComments", "PMarket Market plan : Start  TESTS is interested in receiving information about your company and services.  Due to the diversity of our customer base and their varying geographical regions, we review additions based  on particular needs in key areasEND255");
            SeleniumSetMethods.Click(driver, ElementType.Name, "cbRI_roof");
            SeleniumSetMethods.Click(driver, ElementType.Name, "cbRI_termite");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abRI_other", "t@st");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abRI_Ordered", "05/01/2018");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abRI_Haz", "hazardous");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abRI_Pers", "none");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abAddrS1", "511/2 - A S@le street");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abSaleDtS1", "11/01/2016");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abSqFtS1", "1550");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abTotalS1", "3");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abBedS1", "3");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abTotalS1", "6");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abBathS1", "2.5");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abProxS1", "1");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abBsmtS1", "0");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abGarS1", "2");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abLotS1", "2550");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abAgeS1", "13");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abDomS1", "20");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abLpS1", "425000");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abSpS1", "450000");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abOwnerS1", "CD/HUD");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abAddrS2", "52 Sale Drive, Essex, CA");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abSaleDtS2", "11/02/2016");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abSqFtS2", "1650");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abTotalS2", "7");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abBedS2", "4");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abBathS2", "3");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abProxS2", "1");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abBsmtS2", "150");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abGarS2", "3");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abLotS2", "3500");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abAgeS2", "14");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abDomS2", "25");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abLpS2", "430000");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abSpS2", "430000");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abOwnerS2", "Owner Occupant");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abAddrS3", "53A sale place");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abSaleDtS3", "11/03/2016");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abSqFtS3", "1600");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abTotalS3", "7");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abBedS3", "3");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abBathS3", "2.5");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abProxS3", "1");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abBsmtS3", "0");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abGarS3", "2");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abLotS3", "3000");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abAgeS3", "14");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abDomS3", "20");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abLpS3", "435000");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abSpS3", "430000");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abOwnerS3", "FNMA");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abCondS1", "s1 condition");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abFinS1", "s1 Alltype financing,");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abCommS1", "s1 comments-Add description - Providers we seek are at real estate agent END ");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abCondS2", "s2 Conditions");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abFinS2", "s2 finanace");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abCommS2", "s2 comments-Add description - Providers we seek are at real estate agent END ");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abCondS3", "s3 Conditions");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abFinS3", "s2 finanace");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abCommS3", "s3 commnets-Add description - Providers we seek are at real estate agent END ");
            SeleniumSetMethods.Click(driver, ElementType.XPath, "//input[@name = 'abMostCompS' and @value='2']");
            SeleniumSetMethods.Click(driver, ElementType.Name, "cbInspS1");
            SeleniumSetMethods.Click(driver, ElementType.Name, "cbInspS2");
            SeleniumSetMethods.Click(driver, ElementType.Name, "cbInspS3");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abCommS", "SALES:Test comment's limit& max 60 character.Limit \"is\"  END");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abAddrL1", "10 test Drive, Essex, CA");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abStyleL1", "ranch");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abSqFtL1", "1550");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abTotalL1", "8");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abBedL1", "4");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abBathL1", "2.5");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abProxL1", "1");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abBsmtL1", "0");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abGarL1", "3");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abLotL1", "3000");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abAgeL1", "12");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abDomL1", "30");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abOLpL1", "425000");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abLpL1", "435000");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abOwnerL1", "Relocation");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abAddrL2", "11-A t@st place");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abStyleL2", "a-style");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abSqFtL2", "1756");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abTotalL2", "7");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abBedL2", "3");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abBathL2", "3");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abProxL2", "1");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abBsmtL2", "200");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abGarL2", "2");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abLotL2", "3500");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abAgeL2", "14");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abDomL2", "45");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abOLpL2", "475000");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abLpL2", "450000");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abOwnerL2", "Reo-VA");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abAddrL3", "12/A TestStreet");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abStyleL3", "mordern");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abSqFtL3", "1850");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abTotalL3", "6");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abBedL3", "3");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abBathL3", "1.5");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abProxL3", "1");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abBsmtL3", "0");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abGarL3", "4");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abLotL3", "3750");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abAgeL3", "16");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abDomL3", "40");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abOLpL3", "440000");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abLpL3", "440000");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abOwnerL3", "Investor");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abCondL1", "list1 condition");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abFinL1", "c1 finance");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abCommL1", "l1 commnets-Add description - Providers we seek are at real estate agent END ");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abCondL2", "l2 condition");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abFinL2", "c2 finance");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abCommL2", "l2 comments-Add description - Providers we seek are at real estate agent END ");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abCondL3", "l3 condition");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abFinL3", "c3 finance");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abCommL3", "l3 comments-Add description - Providers we seek are at real estate agent END ");
            SeleniumSetMethods.Click(driver, ElementType.XPath, "//input[@name = 'abMostCompL' and @value='1']");
            SeleniumSetMethods.Click(driver, ElementType.Name, "cbInspL1");
            SeleniumSetMethods.Click(driver, ElementType.Name, "cbInspL2");
            SeleniumSetMethods.Click(driver, ElementType.Name, "cbInspL3");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abCommL", "test comments limit to max <60 character's.Limit is$12% END.");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abObo", "Functional- test");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abInflu", "positive influence");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abResale", "resale problem");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abFinan", "all allowed");
            SeleniumSetMethods.Click(driver, ElementType.Name, "cbFirst");
            SeleniumSetMethods.Click(driver, ElementType.Name, "cbInvest");
            SeleniumSetMethods.Click(driver, ElementType.Name, "cbOther");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abFinancier", "all");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abMktStrategy", "both will work");
            SeleniumSetMethods.Click(driver, ElementType.Name, "abViewed");
            SeleniumSetMethods.Click(driver, ElementType.Id, "btnSaveWork");
            SeleniumWindowMethods.Sleep(1);
            SeleniumSetMethods.Click(driver, ElementType.XPath, "//table[@id='tabBorder2']/tbody/tr[22]/td/table/tbody/tr/td[2]/a/img");
            SeleniumSetMethods.Wait(driver, ElementType.Name, "abmv90asis");
            SeleniumWindowMethods.Sleep(1);
            //  SeleniumSetMethods.Clear(driver, ElementType.Id, "abmv90asis");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abmv90asis", "500000");
            // SeleniumSetMethods.Clear(driver, ElementType.Id, "abmv90rep");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abmv90rep", "550000");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "txtmvcomments", "As IS comments: Start 1 TEST'S is interested in receiving information about your company and services. Due to the diversity of our customer base and their varying geographical regions, Max Saved 200. Not saved ");
            //  SeleniumSetMethods.Clear(driver, ElementType.Id, "abslp90asis");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abslp90asis", "400000");
            //   SeleniumSetMethods.Clear(driver, ElementType.Id, "abslp90rep");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abslp90rep", "450000");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "txtslpcomments", "SUGGESTED Info’s: Start 1 TESTS is interested in receiving information about your company and services. Due to the diversity of our customer base and their varying geographical regions, Max Saved 200. Not saved ");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abEstLandValue", "250000");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abHoName", "test association");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abHoAcsz", "123 main street, lake forest , CA 92630");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abHoPhone", "7418529966");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abHoDues", "250");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abHoWhen", "12/01/2016");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abHoLast", "11/01/2016");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abHoDelinq", "none");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abHoMaint", "lawn, pool");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abRdesc1", "window's");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abRcost1", "150");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abRdesc2", "paint\"s");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "abRcost2", "250");
            SeleniumSetMethods.Click(driver, ElementType.XPath, "//input[@name ='abViewed' and @value='N']");
            //   SeleniumSetMethods.EnterText(driver, ElementType.Name, "abBkrDate", "05/20/18");
            SeleniumSetMethods.Click(driver, ElementType.Id, "btnSaveWorkPg2");
        }

        

    }

}
