using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.IE;
using OpenQA.Selenium.Firefox;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;

namespace Selenium3
{
    class Form_REO_PNMAC
    {
        public static void CompleteBPO(Driver driver)
        {
            //REO BPO 
            SeleniumWindowMethods.Sleep(2);
            Global.ConsoleOut("Pause Me");
            SeleniumWindowMethods.Sleep(5);
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "subApn", "123-22");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "subOrderNo", "123");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "subOrderType", "BPO");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "subVendorOrderNo", "vorder#132");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "subBorrower", "Qa test");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "subOwner", "owner of public");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "subCounty", "orange");
            SeleniumSetMethods.Click(driver, ElementType.Id, "subPropTypeSFR");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "subHoa", "180");
            SeleniumSetMethods.Click(driver, ElementType.Id, "subUCNo");
            SeleniumSetMethods.Click(driver, ElementType.Id, "subDisNo");
            SeleniumSetMethods.Click(driver, ElementType.Id, "subDisYes");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "subDisDescr", "04/15/2015");
            SeleniumSetMethods.Click(driver, ElementType.Id, "subListedYes");
            SeleniumSetMethods.Click(driver, ElementType.XPath, "//table[@id='tabBorder1']/tbody/tr/td/div[3]/div[19]/div[2]/label");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "subDOM", "35");
            SeleniumSetMethods.Click(driver, ElementType.Id, "subSoldYes");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "subSP", "575000");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "subSPDt", "09/10/2015");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "subOLP", "580000");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "subOLPDt", "08/11/2015");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "subLLP", "579000");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "subLLPDt", "09/01/2016");
            SeleniumSetMethods.Click(driver, ElementType.Id, "subOccupancyOwner");
            SeleniumSetMethods.Click(driver, ElementType.XPath, "//table[@id='tabBorder1']/tbody/tr/td/div[3]/div[25]/div[2]/label");
            SeleniumSetMethods.Click(driver, ElementType.Id, "subInspectExterior");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "subInspectDt", "07/25/2016");
            SeleniumSetMethods.Click(driver, ElementType.Id, "subSecureYes");
            SeleniumSetMethods.Click(driver, ElementType.XPath, "//table[@id='tabBorder1']/tbody/tr/td/div[3]/div[27]/div[2]/label");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "subZoning", "Zoning");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "subZoningSrce", "Zone Datas source");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "subUseCur", "current");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "subUseProj", "projected use");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "txtSubNotes", "Test subject property comments:");
            SeleniumSetMethods.Click(driver, ElementType.Id, "hoodLocSuburban");
            SeleniumSetMethods.Click(driver, ElementType.Id, "hoodValuesStable");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "hoodDOM", "45");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "hoodRent", "1800");
            SeleniumSetMethods.SelectDropDown(driver, ElementType.Name, "hoodReoTrend", "Stable");
            SeleniumSetMethods.SelectDropDown(driver, ElementType.Name, "hoodTrend", "Increasing");
            SeleniumSetMethods.Click(driver, ElementType.Id, "hoodOccOwner");
            SeleniumSetMethods.Click(driver, ElementType.Id, "hoodIndusYes");
            SeleniumSetMethods.Click(driver, ElementType.Id, "hoodVacancy20");
            SeleniumSetMethods.Click(driver, ElementType.Id, "hoodNewConstructYes");
            SeleniumSetMethods.Click(driver, ElementType.Id, "hoodDisYes");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "hoodDisDt", "04/20/2015");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "hoodListings", "5");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "hoodLpTo", "370,000");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "hoodLpFrom", "425,000");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "hoodSales", "3");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "hoodSpTo", "380,000");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "hoodSpFrom", "430,000");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "txtHoodDescr", "neighborhood description");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "txtHoodMktCondition", "market condition :");
            SeleniumSetMethods.Click(driver, ElementType.Id, "rfDamaged");
            SeleniumSetMethods.Click(driver, ElementType.Id, "rfEnvironmental");
            SeleniumSetMethods.Click(driver, ElementType.Id, "rfZoning");
            SeleniumSetMethods.Click(driver, ElementType.Id, "rfMktActivity");
            SeleniumSetMethods.Click(driver, ElementType.Id, "rfOther");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "txtRfNotes", "Red flag comments:");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "repName1", "repair1");
            SeleniumSetMethods.Click(driver, ElementType.Id, "repIE1I");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "repCost1", "180");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "repName2", "rapair2");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "repName3", "repair3");
            SeleniumSetMethods.Click(driver, ElementType.Id, "repIE2E");
            SeleniumSetMethods.Click(driver, ElementType.Id, "repIE3I");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "repCost2", "2");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "repCost3", "3");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "repName4", "repair4");
            SeleniumSetMethods.Click(driver, ElementType.Id, "repIE4E");
            SeleniumSetMethods.Click(driver, ElementType.XPath, "//table[@id='tabReps']/tbody/tr[5]/td[2]/label[2]");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "repCost4", "4");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "repName5", "5");
            SeleniumSetMethods.Click(driver, ElementType.Id, "repIE5I");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "repCost5", "5");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "repName6", "6");
            SeleniumSetMethods.Click(driver, ElementType.Id, "repIE6E");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "repCost6", "6");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "repName7", "7");
            SeleniumSetMethods.Click(driver, ElementType.Id, "repIE7I");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "repCost7", "7");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "repName8", "8");
            SeleniumSetMethods.Click(driver, ElementType.Id, "repIE8E");
            SeleniumSetMethods.Click(driver, ElementType.XPath, "//table[@id='tabReps']/tbody/tr[9]/td[2]/label[2]");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "repCost8", "8");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "repName9", "9");
            SeleniumSetMethods.Click(driver, ElementType.Id, "repIE9E");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "repCost9", "9");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "maYrBuilt", "1999");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "maGLA", "2500");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "maLotSize", "6500");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "maBeds", "4");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "maBaths", "25");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "maBaths", "2");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "maUnits", "15");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "maUnits", "1");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "maSrchRadius", "15");
            SeleniumSetMethods.SelectDropDown(driver, ElementType.Name, "maPropType", "SFR");
            SeleniumSetMethods.Click(driver, ElementType.Id, "maCompAge12");
            SeleniumSetMethods.Click(driver, ElementType.XPath, "//table[@id='tabBorder1']/tbody/tr/td/div[11]/table/tbody/tr[10]/td[2]/label[2]");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "maClosedSales", "6");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "ma6moAbRate", "25");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "maListsPendings", "33");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "maMoSupply", "4");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "ma6MoAvgLP", "411,111");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "ma3MoAvgLP", "422,222");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "ma6MoAvgSP", "433,333");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "ma3MoAvgSP", "444,444");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "ma6MoSLRatio", "15");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "ma3MoSLRatio", "25");
            SeleniumSetMethods.Click(driver, ElementType.Name, "btnSave");
            SeleniumSetMethods.Click(driver, ElementType.CssSelector, "a > img");
            SeleniumSetMethods.Wait(driver, ElementType.Id, "txts1Addr");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "txts1Addr", "2 S@les Street");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "s1City", "Irvine");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "s1Zip", "92620");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "txts2Addr", "3 Sales place #B");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "s2City", "Irvine");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "s2Zip", "92620");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "txts3Addr", "4 Sales place ");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "s3City", "Irvine");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "s3Zip", "92620");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "txtl1Addr", "5 LIST Street");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "l1City", "Irvine");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "l1Zip", "92620");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "txtl2Addr", "6 L!st Place");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "l2City", "Irvine");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "l2Zip", "92620");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "txtl3Addr", "7 List Place #C ");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "l3City", "Irvine");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "l3Zip", "92620");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "sbSrce", "sub Data");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "s1Srce", "sale#1 Data");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "s2Srce", "sale#2 Data");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "s3Srce", "Sale#3 Data");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "l1Srce", "List#1");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "l2Srce", "List#2 data");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "l3Srce", "List#3 data");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "s1Prox", "1");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "s2Prox", "2");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "s3Prox", "2");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "l1Prox", "1");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "l2Prox", "3");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "l3Prox", "6");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "sbOLDt", "07/11/2016");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "s1OLDt", "07/01/2016");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "s2OLDt", "07/02/2016");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "s3OLDt", "07/03/2016");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "l1OLDt", "07/04/2016");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "l2OLDt", "07/05/2016");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "l3OLDt", "07/06/2016");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "sbOLp", "400,001");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "sbLLP", "400,000");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "s1OLp", "410,000");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "s1LLP", "409,000");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "s1SaleDt", "07/15/2016");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "s2OLp", "411,000");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "s2LLP", "411,000");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "s2SaleDt", "07/16/2016");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "s3OLp", "412,111");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "s3LLP", "412,222");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "s3SaleDt", "07/17/2016");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "l1OLp", "395000");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "l1LLP", "394000");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "l2OLp", "380000");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "l2LLP", "388,333");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "l3OLp", "384,333");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "l3LLP", "382,222");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "s1SP", "408000");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "s2SP", "410000");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "s3SP", "412333");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "sbDom", "32");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "s1Dom", "33");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "s2Dom", "34");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "s3Dom", "35");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "l1Dom", "36");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "l2Dom", "37");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "l3Dom", "38");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "sbCumDom", "41");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "s1CumDom", "42");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "s2CumDom", "43");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "s3CumDom", "44");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "l1CumDom", "45");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "l2CumDom", "46");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "l3CumDom", "47");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "sbSrceFunds", "sub FUND");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "s1SrceFunds", "sal#1 Find");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "s2SrceFunds", "Sale#Fund");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "s3SrceFunds", "Sale#3 Fund");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "l1SrceFunds", "List#1 Fund");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "l2SrceFunds", "List#2 Fund");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "l3SrceFunds", "List#3 Fund");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "sbConcess", "Sub Con");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "s1Concess", "Sale#1 Con");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "s2Concess", "Sale#3 Con");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "s3Concess", "Sale#3 con");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "l1Concess", "List#1 Con");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "l2Concess", "List#2 Con");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "l3Concess", "List#3 Con");
            SeleniumSetMethods.SelectDropDown(driver, ElementType.Id, "sbDistSale", "No");
            SeleniumSetMethods.SelectDropDown(driver, ElementType.Id, "s1DistSale", "No");
            SeleniumSetMethods.SelectDropDown(driver, ElementType.Id, "s2DistSale", "Yes");
            SeleniumSetMethods.SelectDropDown(driver, ElementType.Id, "s3DistSale", "No");
            SeleniumSetMethods.SelectDropDown(driver, ElementType.Id, "l1DistSale", "Yes");
            SeleniumSetMethods.SelectDropDown(driver, ElementType.Id, "l2DistSale", "No");
            SeleniumSetMethods.SelectDropDown(driver, ElementType.Id, "l3DistSale", "No");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "sbLotSize", "2");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "sbSiteSize", "3");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "s1LotSize", "1");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "s1SiteSize", "2");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "s2LotSize", "2");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "s2SiteSize", "3");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "s3LotSize", "3");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "s3SiteSize", "4");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "l1LotSize", "0");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "l1SiteSize", "1");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "l2LotSize", "3");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "l2SiteSize", "2");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "l3LotSize", "4");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "l3SiteSize", "4");
            SeleniumSetMethods.SelectDropDown(driver, ElementType.Name, "sbView", "Neutral");
            SeleniumSetMethods.SelectDropDown(driver, ElementType.Name, "s1View", "Beneficial");
            SeleniumSetMethods.SelectDropDown(driver, ElementType.Name, "s2View", "Adverse");
            SeleniumSetMethods.SelectDropDown(driver, ElementType.Name, "s3View", "Neutral");
            SeleniumSetMethods.SelectDropDown(driver, ElementType.Name, "l1View", "Beneficial");
            SeleniumSetMethods.SelectDropDown(driver, ElementType.Name, "l2View", "Adverse");
            SeleniumSetMethods.SelectDropDown(driver, ElementType.Name, "l3View", "Adverse");
            SeleniumSetMethods.SelectDropDown(driver, ElementType.Name, "s1Comparison", "Good");
            SeleniumSetMethods.SelectDropDown(driver, ElementType.Name, "s2Comparison", "Satisfactory");
            SeleniumSetMethods.SelectDropDown(driver, ElementType.Name, "s3Comparison", "Poor");
            SeleniumSetMethods.SelectDropDown(driver, ElementType.Name, "l1Comparison", "Poor");
            SeleniumSetMethods.SelectDropDown(driver, ElementType.Name, "l2Comparison", "Satisfactory");
            SeleniumSetMethods.SelectDropDown(driver, ElementType.Name, "l3Comparison", "Good");
            SeleniumSetMethods.SelectDropDown(driver, ElementType.Name, "sbPropType", "SFR");
            SeleniumSetMethods.SelectDropDown(driver, ElementType.Name, "s1PropType", "CONDO");
            SeleniumSetMethods.SelectDropDown(driver, ElementType.Name, "s2PropType", "Manufactured");
            SeleniumSetMethods.SelectDropDown(driver, ElementType.Name, "s3PropType", "Other");
            SeleniumSetMethods.SelectDropDown(driver, ElementType.Name, "l1PropType", "SFR");
            SeleniumSetMethods.SelectDropDown(driver, ElementType.Name, "l2PropType", "COOP");
            SeleniumSetMethods.SelectDropDown(driver, ElementType.Name, "l3PropType", "PUD");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "sbUnits", "1");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "s1Units", "2");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "s2Units", "2");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "s3Units", "1");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "l1Units", "1");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "l2Units", "2");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "l3Units", "1");
            SeleniumSetMethods.SelectDropDown(driver, ElementType.Name, "sbConstructType", "Aluminum");
            SeleniumSetMethods.SelectDropDown(driver, ElementType.Name, "s1ConstructType", "Brick");
            SeleniumSetMethods.SelectDropDown(driver, ElementType.Name, "s2ConstructType", "Stone");
            SeleniumSetMethods.SelectDropDown(driver, ElementType.Name, "s3ConstructType", "Vinyl");
            SeleniumSetMethods.SelectDropDown(driver, ElementType.Name, "l1ConstructType", "Wood");
            SeleniumSetMethods.SelectDropDown(driver, ElementType.Name, "l2ConstructType", "Other");
            SeleniumSetMethods.SelectDropDown(driver, ElementType.Name, "l3ConstructType", "Stone");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "sbDesign", "sub Sedign");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "s1Design", "sal#1 Design");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "s2Design", "sale#2 desig");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "s3Design", "Sale#3 desig");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "l1Design", "List#1 desig");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "l2Design", "List#2 desig");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "l3Design", "list#3 desig");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "sbAge", "12");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "s1Age", "13");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "s2Age", "14");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "s3Age", "10");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "l1Age", "3");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "l2Age", "6");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "l3Age", "11");
            SeleniumSetMethods.SelectDropDown(driver, ElementType.Name, "sbCondition", "Good");
            SeleniumSetMethods.SelectDropDown(driver, ElementType.Name, "s1Condition", "Average");
            SeleniumSetMethods.SelectDropDown(driver, ElementType.Name, "s2Condition", "Poor");
            SeleniumSetMethods.SelectDropDown(driver, ElementType.Name, "s3Condition", "Average");
            SeleniumSetMethods.SelectDropDown(driver, ElementType.Name, "l1Condition", "Average");
            SeleniumSetMethods.SelectDropDown(driver, ElementType.Name, "l2Condition", "Good");
            SeleniumSetMethods.SelectDropDown(driver, ElementType.Name, "l3Condition", "Poor");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "sbGla", "2500");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "s1Gla", "1550");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "s2Gla", "2650");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "s3Gla", "1800");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "l1Gla", "2750");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "l2Gla", "1951");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "l3Gla", "2550");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "sbRooms", "6");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "sbBeds", "4");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "sbFull", "3");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "sbPartial", "2");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "s1Rooms", "7");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "s1Beds", "6");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "s1Full", "2");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "s1Partial", "1");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "s2Rooms", "5");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "s2Beds", "3");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "s2Full", "3");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "s2Partial", "0");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "s3Rooms", "8");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "s3Beds", "6");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "s3Full", "3");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "s3Partial", "1");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "l1Rooms", "6");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "l1Beds", "5");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "l1Full", "2");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "l1Partial", "2");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "l2Rooms", "8");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "l2Beds", "4");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "l2Full", "1");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "l2Partial", "1");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "l3Rooms", "6");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "l3Beds", "2");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "l3Beds", "3");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "l3Full", "1");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "l3Partial", "1");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "sbBasement", "sub basement");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "s1Basement", "Sale#1 basem");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "s2Basement", "sale#2 Basem");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "s3Basement", "sale#3 Basem");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "l1Basement", "List#1 basem");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "l2Basement", "L1st#2 Base");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "l3Basement", "list#3 bas");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "sbSF", "100");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "sbPerc", "0");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "s1SF", "1500");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "s1Perc", "10");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "s2SF", "250");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "s2Perc", "100");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "s3SF", "500");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "s3Perc", "15");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "l1SF", "250");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "l1Perc", "10");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "l2SF", "550");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "l2Perc", "0");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "l3SF", "250");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "l3Perc", "0");
            SeleniumSetMethods.SelectDropDown(driver, ElementType.Name, "sbParking", "driveway");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "sbStalls", "2");
            SeleniumSetMethods.SelectDropDown(driver, ElementType.Name, "s1Parking", "garage");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "s1Stalls", "3");
            SeleniumSetMethods.SelectDropDown(driver, ElementType.Name, "s2Parking", "none");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "s2Stalls", "0");
            SeleniumSetMethods.SelectDropDown(driver, ElementType.Name, "s3Parking", "driveway");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "s3Stalls", "2");
            SeleniumSetMethods.SelectDropDown(driver, ElementType.Name, "l1Parking", "garage");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "l1Stalls", "1");
            SeleniumSetMethods.SelectDropDown(driver, ElementType.Name, "l2Parking", "none");
            SeleniumSetMethods.SelectDropDown(driver, ElementType.Name, "l2Parking", "driveway");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "l2Stalls", "3");
            SeleniumSetMethods.SelectDropDown(driver, ElementType.Name, "l3Parking", "none");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "l3Stalls", "0");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "sbPool", "sub pool");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "s1Pool", "Sale#1 Pool");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "s2Pool", "Sale#2 Pool");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "s3Pool", "Sale#3 Pool");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "l1Pool", "List#1 Pool");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "l2Pool", "List#2 Pool");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "l3Pool", "List#3 Pool");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "sbOther", "Sub Other");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "s1Other", "s1# Other");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "s2Other", "Sale#2 Other");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "s3Other", "sale#3 Other");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "l1Other", "List#1 other");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "l2Other", "List#2 Other");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "l3Other", "List#3 Other");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "sbHoa", "180");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "s1Hoa", "175");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "s2Hoa", "170");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "s3Hoa", "0");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "l1Hoa", "125");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "l2Hoa", "250");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "l3Hoa", "222");
            SeleniumSetMethods.SelectDropDown(driver, ElementType.Name, "s1Overall", "Satisfactory");
            SeleniumSetMethods.SelectDropDown(driver, ElementType.Name, "s2Overall", "Good");
            SeleniumSetMethods.SelectDropDown(driver, ElementType.Name, "s3Overall", "Poor");
            SeleniumSetMethods.SelectDropDown(driver, ElementType.Name, "l1Overall", "Satisfactory");
            SeleniumSetMethods.SelectDropDown(driver, ElementType.Name, "l2Overall", "Good");
            SeleniumSetMethods.SelectDropDown(driver, ElementType.Name, "l3Overall", "Poor");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "txts1Notes", "sale# 1 comments: Test");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "txts2Notes", "Sale#2 Comments : Test");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "txts3Notes", "Sale#3 Comments: Test");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "txtl1Notes", "List#1 Commenst : test");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "txtl2Notes", "List #2 Comments: test");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "txtl3Notes", "List#3 Comment s: Test");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "poSugLp30", "511,111");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "poProbSp30", "522,222");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "poDomAsIs", "111");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "poSugLpAsIs", "533,333");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "poProbSpAsIs", "544,444");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "poDomRep", "222");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "poSugLpRep", "555,555");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "poProbSpRep", "566,666");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "txtpoNotes", "Comments : test1 test2 \n" + "line@2 \n" + "line3 - Test . ~!@#$% = &*()_+=-< d>?\":]{} [;'/.,) <  dfsd > End .");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "certSign", "Test");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "certBy", "Test - Prepared By: ");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "certByDate", "07/25/2016");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "certBkr", "Listing Agent test");
            SeleniumSetMethods.SelectDropDown(driver, ElementType.Name, "certState", "California");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "certCompany", "Testt company");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "certComanyAddr", "123 main street, lake forest CA 92630");
            SeleniumSetMethods.EnterText(driver, ElementType.Name, "certPhone", "label=7528529988");
            SeleniumSetMethods.Click(driver, ElementType.Id, "btnSaveWorkPg2");
        }
    }
}
