using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Selenium3
{
    class PNMACBPO
    {

        public static void PNMAC()
        {
            SeleniumSetMethods.Click(ElementType.Id, "Subject_InspectionDate");
            SeleniumSetMethods.Click(ElementType.XPath, "(//button[@type='button'])[2]");
            SeleniumSetMethods.Click(ElementType.Id, "PennyMac_Subject_IsPropertySecure_0");
            SeleniumSetMethods.Click(ElementType.Id, "PennyMac_SubjectMarketing_IsNewConstruction_1");
            SeleniumSetMethods.Click(ElementType.Id, "PennyMac_SubjectMarketing_IsCurrentDisaster_1");
            SeleniumSetMethods.Click(ElementType.Id, "PennyMac_Subject_ZoningDescription");
            SeleniumSetMethods.Click(ElementType.Id, "Subject_LocationType_1");
            SeleniumSetMethods.Click(ElementType.Id, "Marketing_MarketingDays");
            SeleniumSetMethods.Click(ElementType.Id, "PennyMac_Marketing_ReoTrend_1");
            SeleniumSetMethods.Click(ElementType.Id, "PennyMac_Marketing_MarketTimingTrend_1");
            SeleniumSetMethods.Click(ElementType.Id, "PennyMac_Marketing_PrimaryOccupant_0");
            SeleniumSetMethods.Click(ElementType.Id, "PennyMac_Marketing_IsIndustrialWithinQtrMile_1");
            SeleniumSetMethods.Click(ElementType.Id, "PennyMac_Marketing_VacancyPercentage_2");
            SeleniumSetMethods.Click(ElementType.Id, "PennyMac_Marketing_IsNeighborhoodNewConstruction_1");
            SeleniumSetMethods.Click(ElementType.Id, "PennyMac_Marketing_IsDisasterEvidence_1");
            SeleniumSetMethods.Click(ElementType.Id, "Marketing_SalesLow");
            SeleniumSetMethods.Click(ElementType.Id, "Marketing_ListingsLow");
            SeleniumSetMethods.Click(ElementType.Id, "PennyMac_Marketing_NeighborhoodDescription");
            SeleniumSetMethods.Click(ElementType.Id, "PennyMac_Subject_IsRedFlagDamaged_1");
            SeleniumSetMethods.Click(ElementType.Id, "PennyMac_Subject_IsRedFlagConstruction_1");
            SeleniumSetMethods.Click(ElementType.Id, "PennyMac_Subject_IsRedFlagEnvironmental_0");
            SeleniumSetMethods.Click(ElementType.Id, "PennyMac_Subject_IsRedFlagZoning_0");
            SeleniumSetMethods.Click(ElementType.Id, "PennyMac_Subject_IsRedFlagMarketActivity_0");
            SeleniumSetMethods.Click(ElementType.Id, "PennyMac_Subject_IsRedFlagStigma_1");
            SeleniumSetMethods.Click(ElementType.Id, "PennyMac_Subject_IsRedFlagOther_0");
            SeleniumSetMethods.Click(ElementType.Id, "Marketing_MarketConditions_1");
            SeleniumSetMethods.Click(ElementType.Id, "Marketing_MarketPriceStability_2");
            SeleniumSetMethods.Click(ElementType.Id, "Marketing_MarketPriceStabilityPercent");
            SeleniumSetMethods.Click(ElementType.Id, "Marketing_ComparableSupply_1");
            SeleniumSetMethods.Click(ElementType.Id, "Marketing_OwnerPercentage");
            SeleniumSetMethods.Click(ElementType.Id, "PennyMac_SubjectMarketing_ListingStatusPast12Mo_1");
            SeleniumSetMethods.Click(ElementType.Id, "SubjectMarketing_SubjectDom");
            SeleniumSetMethods.Click(ElementType.Id, "PennyMac_SubjectMarketing_SubjectListPast12MoOriginalListDate");
            SeleniumSetMethods.Click(ElementType.LinkText, "1");
            SeleniumSetMethods.Click(ElementType.Id, "PennyMac_SubjectMarketing_SubjectListPast12MoLastListDate");
            SeleniumSetMethods.Click(ElementType.LinkText, "1");
            SeleniumSetMethods.Click(ElementType.Id, "PennyMac_SubjectMarketing_IsSubjectSoldPast12Mo_0");
            SeleniumSetMethods.Click(ElementType.Id, "PennyMac_SubjectMarketing_SubjectPast12MoSalePrice");
            SeleniumSetMethods.Click(ElementType.Id, "PennyMac_SubjectMarketing_SubjectPast12MoSalePriceDate");
            SeleniumSetMethods.Click(ElementType.LinkText, "1");
            SeleniumSetMethods.Click(ElementType.Id, "PennyMac_SubjectMarketing_SubjectSoldPast12MoOriginalListDate");
            SeleniumSetMethods.Click(ElementType.LinkText, "1");
            SeleniumSetMethods.Click(ElementType.Id, "PennyMac_SubjectMarketing_SubjectSoldPast12MoLastListPrice");
            SeleniumSetMethods.Click(ElementType.Id, "PennyMac_SubjectMarketing_SubjectSoldPast12MoLastListDate");
            SeleniumSetMethods.Click(ElementType.LinkText, "1");
            SeleniumSetMethods.Click(ElementType.Id, "SubjectMarketing_SubjectPropertyUnits");
            SeleniumSetMethods.Click(ElementType.Id, "SubjectMarketing_SubjectLastSalePrice");
            SeleniumSetMethods.Click(ElementType.Id, "SubjectMarketing_SubjectLastSaleDate");
            SeleniumSetMethods.Click(ElementType.Id, "SubjectMarketing_SubjectLastSaleDate");
            SeleniumSetMethods.Click(ElementType.LinkText, "1");
            SeleniumSetMethods.Click(ElementType.Id, "SubjectMarketing_SubjectOccupancyStatus_1");
            SeleniumSetMethods.Click(ElementType.Id, "SubjectMarketing_OwnershipStatus_0");
            SeleniumSetMethods.Click(ElementType.Id, "SaleComps_0__PostalCode");
            SeleniumSetMethods.Click(ElementType.Id, "PennyMac_SaleComps_0__OriginalListDate");
            SeleniumSetMethods.Click(ElementType.LinkText, "1");
            SeleniumSetMethods.Click(ElementType.Id, "PennyMac_SaleComps_1__OriginalListDate");
            SeleniumSetMethods.Click(ElementType.LinkText, "1");
            SeleniumSetMethods.Click(ElementType.Id, "PennyMac_SaleComps_2__OriginalListDate");
            SeleniumSetMethods.Click(ElementType.LinkText, "1");
            SeleniumSetMethods.Click(ElementType.Id, "PennyMac_SaleComps_1__OriginalListPrice");
            SeleniumSetMethods.Click(ElementType.Id, "SaleComps_0__SaleDate");
            SeleniumSetMethods.Click(ElementType.LinkText, "1");
            SeleniumSetMethods.Click(ElementType.Id, "SaleComps_1__SaleDate");
            SeleniumSetMethods.Click(ElementType.LinkText, "1");
            SeleniumSetMethods.Click(ElementType.Id, "SaleComps_2__SaleDate");
            SeleniumSetMethods.Click(ElementType.LinkText, "1");
            SeleniumSetMethods.Click(ElementType.Id, "SaleComps_0__Dom");
            SeleniumSetMethods.Click(ElementType.Id, "PennyMac_Subject_IsDistressedSale_1");
            SeleniumSetMethods.Click(ElementType.Id, "PennyMac_SaleComps[0]_IsDistressedSale_1");
            SeleniumSetMethods.Click(ElementType.Id, "PennyMac_SaleComps[1]_IsDistressedSale_0");
            SeleniumSetMethods.Click(ElementType.Id, "PennyMac_SaleComps[2]_IsDistressedSale_1");
            SeleniumSetMethods.Click(ElementType.Id, "Subject_LotSize");
            SeleniumSetMethods.Click(ElementType.Id, "Subject_Units");
            SeleniumSetMethods.Click(ElementType.Id, "Subject_Rooms");
            SeleniumSetMethods.Click(ElementType.Id, "Subject_GarageCount");
            SeleniumSetMethods.Click(ElementType.Id, "SaleComps_1__GarageCount");
            SeleniumSetMethods.Click(ElementType.Id, "SaleComps_2__GarageCount");
            SeleniumSetMethods.Click(ElementType.Id, "PennyMac_Subject_PoolSpa");
            SeleniumSetMethods.Click(ElementType.Id, "PennyMac_SaleComps_0__HoaFee");
            SeleniumSetMethods.Click(ElementType.Id, "PennyMac_SaleComps_0__Comparability");
            SeleniumSetMethods.Click(ElementType.Id, "PennyMac_Marketing_MarketYearBuilt");
            SeleniumSetMethods.Click(ElementType.Id, "PennyMac_Marketing_SaleListRatioPast3Mo");
            SeleniumSetMethods.Click(ElementType.Id, "PennyMac_ListComps_0__OriginalListDate");
            SeleniumSetMethods.Click(ElementType.LinkText, "1");
            SeleniumSetMethods.Click(ElementType.Id, "PennyMac_ListComps_1__OriginalListDate");
            SeleniumSetMethods.Click(ElementType.CssSelector, "span.ui-icon.ui-icon-circle-triangle-w");
            SeleniumSetMethods.Click(ElementType.LinkText, "17");
            SeleniumSetMethods.Click(ElementType.Id, "PennyMac_ListComps_2__OriginalListDate");
            SeleniumSetMethods.Click(ElementType.LinkText, "15");
            SeleniumSetMethods.Click(ElementType.Id, "ListComps_0__OriginalListPrice");
            SeleniumSetMethods.Click(ElementType.Id, "ListComps_0__Dom");
            SeleniumSetMethods.Click(ElementType.Id, "PennyMac_ListComps[0]_IsDistressedSale_1");
            SeleniumSetMethods.Click(ElementType.Id, "PennyMac_ListComps[1]_IsDistressedSale_0");
            SeleniumSetMethods.Click(ElementType.Id, "PennyMac_ListComps[2]_IsDistressedSale_1");
            SeleniumSetMethods.Click(ElementType.Id, "ListComps_0__LotSize");
            SeleniumSetMethods.Click(ElementType.Id, "ListComps_0__Units");
            SeleniumSetMethods.Click(ElementType.Id, "PennyMac_ListComps_0__Age");
            SeleniumSetMethods.Click(ElementType.Id, "ListComps_0__Rooms");
            SeleniumSetMethods.Click(ElementType.Id, "ListComps_0__GrossLivingArea");
            SeleniumSetMethods.Click(ElementType.Id, "PennyMac_ListComps_0__BsmtSqFt");
            SeleniumSetMethods.Click(ElementType.Id, "ListComps_0__GarageCount");
            SeleniumSetMethods.Click(ElementType.Id, "ListComps_1__GarageType");
            SeleniumSetMethods.Click(ElementType.Id, "ListComps_1__GarageCount");
            SeleniumSetMethods.Click(ElementType.Id, "ListComps_2__GarageType");
            SeleniumSetMethods.Click(ElementType.Id, "ListComps_2__GarageCount");
            SeleniumSetMethods.Click(ElementType.Id, "PennyMac_ListComps_0__PoolSpa");
            SeleniumSetMethods.Click(ElementType.Id, "PennyMac_ListComps_0__HoaFee");
            SeleniumSetMethods.Click(ElementType.Id, "QuickSaleListPrice");
            SeleniumSetMethods.Click(ElementType.Id, "PennyMac_AsIsDays");
            SeleniumSetMethods.Click(ElementType.Id, "ProviderComments");

            // Enter Text

            SeleniumSetMethods.EnterText(ElementType.Id, "PennyMac_Subject_OwnerName", "Owner");
            SeleniumSetMethods.EnterText(ElementType.Id, "PennyMac_VendorOrderId", "123-66");
            SeleniumSetMethods.EnterText(ElementType.Id, "Subject_ParcelNumber", "123-333-55");
            SeleniumSetMethods.EnterText(ElementType.Id, "BpoBrokerDistance", "15");
            SeleniumSetMethods.EnterText(ElementType.Id, "BpoBrokerYearsExperience", "15");
            SeleniumSetMethods.EnterText(ElementType.Id, "PennyMac_Subject_ZoningDescription", "zone");
            SeleniumSetMethods.EnterText(ElementType.Id, "PennyMac_Subject_ZoningDataSource", "Zone data");
            SeleniumSetMethods.EnterText(ElementType.Id, "PennyMac_Subject_CurrentUse", "Current use: Residential");
            SeleniumSetMethods.EnterText(ElementType.Id, "PennyMac_Subject_ProjectedUse", "Project use :Residential");
            SeleniumSetMethods.EnterText(ElementType.Id, "PennyMac_Subject_PropertyComments", "subject comments: Residential");
            SeleniumSetMethods.EnterText(ElementType.Id, "PennyMac_Marketing_MedianRent", "2500");
            SeleniumSetMethods.EnterText(ElementType.Id, "Marketing_MarketingDays", "90");
            SeleniumSetMethods.EnterText(ElementType.Id, "Marketing_SalesLow", "350000");
            SeleniumSetMethods.EnterText(ElementType.Id, "Marketing_SalesHigh", "425000");
            SeleniumSetMethods.EnterText(ElementType.Id, "Marketing_TotalSales", "5");
            SeleniumSetMethods.EnterText(ElementType.Id, "Marketing_ListingsLow", "375000");
            SeleniumSetMethods.EnterText(ElementType.Id, "Marketing_ListingsHigh", "430000");
            SeleniumSetMethods.EnterText(ElementType.Id, "Marketing_TotalListings", "3");
            SeleniumSetMethods.EnterText(ElementType.Id, "PennyMac_Marketing_NeighborhoodDescription", "Neighborhood Description: tests");
            SeleniumSetMethods.EnterText(ElementType.Id, "PennyMac_Marketing_MarketConditionsComment", "Marketconditions: Test");
            SeleniumSetMethods.EnterText(ElementType.Id, "PennyMac_Subject_RedFlagComments", "RED flags: Comments");
            SeleniumSetMethods.EnterText(ElementType.Id, "Marketing_MarketPriceStabilityPercent", "10");
            SeleniumSetMethods.EnterText(ElementType.Id, "Marketing_MarketPriceStabilityMonths", "24");
            SeleniumSetMethods.EnterText(ElementType.Id, "Marketing_OwnerPercentage", "50");
            SeleniumSetMethods.EnterText(ElementType.Id, "Marketing_TenantPercentage", "40");
            SeleniumSetMethods.EnterText(ElementType.Id, "Marketing_ComparableListingsCount", "4");
            SeleniumSetMethods.EnterText(ElementType.Id, "Marketing_ReoListingsCount", "0");
            SeleniumSetMethods.EnterText(ElementType.Id, "SubjectMarketing_SubjectDom", "45");
            SeleniumSetMethods.EnterText(ElementType.Id, "PennyMac_SubjectMarketing_SubjectListPast12MoOriginalListPrice", "475000");
            SeleniumSetMethods.EnterText(ElementType.Id, "PennyMac_SubjectMarketing_SubjectListPast12MoLastListPrice", "470000");
            SeleniumSetMethods.EnterText(ElementType.Id, "PennyMac_SubjectMarketing_SubjectPast12MoSalePrice", "575000");
            SeleniumSetMethods.EnterText(ElementType.Id, "PennyMac_SubjectMarketing_SubjectSoldPast12MoOriginalListPrice", "600000");
            SeleniumSetMethods.EnterText(ElementType.Id, "PennyMac_SubjectMarketing_SubjectSoldPast12MoLastListPrice", "580000");
            SeleniumSetMethods.EnterText(ElementType.Id, "SubjectMarketing_ListingBrokerName", "test broker");
            SeleniumSetMethods.EnterText(ElementType.Id, "SubjectMarketing_ListingFirmName", "service corp");
            SeleniumSetMethods.EnterText(ElementType.Id, "SubjectMarketing_ListingBrokerPhone", "800-963-9999");
            SeleniumSetMethods.SelectDropDown(ElementType.Id, "SubjectMarketing_SubjectPropertyType", "Single Family");
            SeleniumSetMethods.EnterText(ElementType.Id, "SubjectMarketing_SubjectPropertyUnits", "1");
            SeleniumSetMethods.EnterText(ElementType.Id, "SubjectMarketing_SubjectLastSalePrice", "576000");
            SeleniumSetMethods.EnterText(ElementType.Id, "SubjectMarketing_HoaFee", "250.33");
            SeleniumSetMethods.EnterText(ElementType.Id, "SaleComps_0__StreetAddress", "1");
            SeleniumSetMethods.EnterText(ElementType.Id, "SaleComps_1__StreetAddress", "2");
            SeleniumSetMethods.EnterText(ElementType.Id, "SaleComps_2__StreetAddress", "3");
            SeleniumSetMethods.EnterText(ElementType.Id, "SaleComps_0__City", "Irvine");
            SeleniumSetMethods.EnterText(ElementType.Id, "SaleComps_1__City", "Irvine");
            SeleniumSetMethods.EnterText(ElementType.Id, "SaleComps_2__City", "Irvine");
            SeleniumSetMethods.SelectDropDown(ElementType.Id, "SaleComps_0__State", "California");
            SeleniumSetMethods.SelectDropDown(ElementType.Id, "SaleComps_1__State", "California");
            SeleniumSetMethods.SelectDropDown(ElementType.Id, "SaleComps_2__State", "California");
            SeleniumSetMethods.EnterText(ElementType.Id, "SaleComps_0__PostalCode", "92620");
            SeleniumSetMethods.EnterText(ElementType.Id, "SaleComps_1__PostalCode", "92620");
            SeleniumSetMethods.EnterText(ElementType.Id, "SaleComps_2__PostalCode", "92620");
            SeleniumSetMethods.EnterText(ElementType.Id, "SaleComps_0__ProximityDistance", "1");
            SeleniumSetMethods.EnterText(ElementType.Id, "SaleComps_1__ProximityDistance", "1");
            SeleniumSetMethods.EnterText(ElementType.Id, "SaleComps_2__ProximityDistance", "1");
            SeleniumSetMethods.EnterText(ElementType.Id, "PennyMac_SaleComps_0__OriginalListPrice", "470000");
            SeleniumSetMethods.EnterText(ElementType.Id, "PennyMac_SaleComps_1__OriginalListPrice", "450000");
            SeleniumSetMethods.EnterText(ElementType.Id, "PennyMac_SaleComps_2__OriginalListPrice", "440000");
            SeleniumSetMethods.EnterText(ElementType.Id, "SaleComps_0__SalePrice", "450000");
            SeleniumSetMethods.EnterText(ElementType.Id, "SaleComps_1__SalePrice", "425000");
            SeleniumSetMethods.EnterText(ElementType.Id, "SaleComps_2__SalePrice", "425000");
            SeleniumSetMethods.EnterText(ElementType.Id, "SaleComps_0__ListPriceAtSale", "450000");
            SeleniumSetMethods.EnterText(ElementType.Id, "SaleComps_1__ListPriceAtSale", "430000");
            SeleniumSetMethods.EnterText(ElementType.Id, "SaleComps_2__ListPriceAtSale", "425000");
            SeleniumSetMethods.SelectDropDown(ElementType.Id, "Subject_DataSource", "MLS");
            SeleniumSetMethods.SelectDropDown(ElementType.Id, "SaleComps_0__DataSource", "Appraisal");
            SeleniumSetMethods.SelectDropDown(ElementType.Id, "SaleComps_1__DataSource", "MLS");
            SeleniumSetMethods.SelectDropDown(ElementType.Id, "SaleComps_2__DataSource", "Appraisal");
            SeleniumSetMethods.EnterText(ElementType.Id, "SaleComps_0__Dom", "90");
            SeleniumSetMethods.EnterText(ElementType.Id, "SaleComps_1__Dom", "80");
            SeleniumSetMethods.EnterText(ElementType.Id, "SaleComps_2__Dom", "75");
            SeleniumSetMethods.EnterText(ElementType.Id, "PennyMac_Subject_TotalDom", "45");
            SeleniumSetMethods.EnterText(ElementType.Id, "PennyMac_SaleComps_0__TotalDom", "95");
            SeleniumSetMethods.EnterText(ElementType.Id, "PennyMac_SaleComps_1__TotalDom", "80");
            SeleniumSetMethods.EnterText(ElementType.Id, "PennyMac_SaleComps_2__TotalDom", "75");
            SeleniumSetMethods.EnterText(ElementType.Id, "PennyMac_Subject_FundingSource", "sub fund");
            SeleniumSetMethods.EnterText(ElementType.Id, "PennyMac_SaleComps_0__FundingSource", "s1 fund");
            SeleniumSetMethods.EnterText(ElementType.Id, "PennyMac_SaleComps_1__FundingSource", "s2 fund");
            SeleniumSetMethods.EnterText(ElementType.Id, "PennyMac_SaleComps_2__FundingSource", "s3 fund");
            SeleniumSetMethods.EnterText(ElementType.Id, "PennyMac_SubjectMarketing_SubjectConcessions", "sub salecon");
            SeleniumSetMethods.EnterText(ElementType.Id, "SaleComps_0__Concessions", "s1 concession");
            SeleniumSetMethods.EnterText(ElementType.Id, "SaleComps_1__Concessions", "s2 concession");
            SeleniumSetMethods.EnterText(ElementType.Id, "SaleComps_2__Concessions", "s3 concession");
            SeleniumSetMethods.SelectDropDown(ElementType.Id, "SaleComps_0__LocationType", "Suburban");
            SeleniumSetMethods.SelectDropDown(ElementType.Id, "SaleComps_1__LocationType", "Urban");
            SeleniumSetMethods.SelectDropDown(ElementType.Id, "SaleComps_2__LocationType", "Suburban");
            SeleniumSetMethods.SelectDropDown(ElementType.Id, "LotSizeUnitType", "Sq. Ft.");
            SeleniumSetMethods.EnterText(ElementType.Id, "Subject_LotSize", "6000");
            SeleniumSetMethods.EnterText(ElementType.Id, "SaleComps_0__LotSize", "4500");
            SeleniumSetMethods.EnterText(ElementType.Id, "SaleComps_1__LotSize", "5750");
            SeleniumSetMethods.EnterText(ElementType.Id, "SaleComps_2__LotSize", "8500");
            SeleniumSetMethods.EnterText(ElementType.Id, "PennyMac_Subject_Site", "1");
            SeleniumSetMethods.EnterText(ElementType.Id, "PennyMac_SaleComps_0__Site", "1");
            SeleniumSetMethods.EnterText(ElementType.Id, "PennyMac_SaleComps_1__Site", "1");
            SeleniumSetMethods.EnterText(ElementType.Id, "PennyMac_SaleComps_2__Site", "1");
            SeleniumSetMethods.SelectDropDown(ElementType.Id, "PennyMac_SaleComps_0__PropertyType", "Single Family");
            SeleniumSetMethods.SelectDropDown(ElementType.Id, "PennyMac_SaleComps_1__PropertyType", "Single Family");
            SeleniumSetMethods.SelectDropDown(ElementType.Id, "PennyMac_SaleComps_2__PropertyType", "Single Family");
            SeleniumSetMethods.EnterText(ElementType.Id, "Subject_Units", "1");
            SeleniumSetMethods.EnterText(ElementType.Id, "SaleComps_0__Units", "1");
            SeleniumSetMethods.EnterText(ElementType.Id, "SaleComps_1__Units", "1");
            SeleniumSetMethods.EnterText(ElementType.Id, "SaleComps_2__Units", "1");
            SeleniumSetMethods.SelectDropDown(ElementType.Id, "PennyMac_Subject_ConstructionType", "Stone");
            SeleniumSetMethods.SelectDropDown(ElementType.Id, "PennyMac_SaleComps_0__ConstructionType", "Wood");
            SeleniumSetMethods.SelectDropDown(ElementType.Id, "PennyMac_SaleComps_1__ConstructionType", "Other");
            SeleniumSetMethods.SelectDropDown(ElementType.Id, "PennyMac_SaleComps_2__ConstructionType", "Brick");
            SeleniumSetMethods.EnterText(ElementType.Id, "PennyMac_Subject_Design", "sub design");
            SeleniumSetMethods.EnterText(ElementType.Id, "PennyMac_SaleComps_0__Design", "s1 design");
            SeleniumSetMethods.EnterText(ElementType.Id, "PennyMac_SaleComps_1__Design", "s2 design");
            SeleniumSetMethods.EnterText(ElementType.Id, "PennyMac_SaleComps_2__Design", "s3 design");
            SeleniumSetMethods.EnterText(ElementType.Id, "PennyMac_Subject_Age", "20");
            SeleniumSetMethods.EnterText(ElementType.Id, "PennyMac_SaleComps_0__Age", "22");
            SeleniumSetMethods.EnterText(ElementType.Id, "PennyMac_SaleComps_1__Age", "23");
            SeleniumSetMethods.EnterText(ElementType.Id, "PennyMac_SaleComps_2__Age", "24");
            SeleniumSetMethods.SelectDropDown(ElementType.Id, "PennyMac_Subject_ViewQualityDescription", "Adverse");
            SeleniumSetMethods.SelectDropDown(ElementType.Id, "PennyMac_SaleComps_0__ViewQualityDescription", "Neutral");
            SeleniumSetMethods.SelectDropDown(ElementType.Id, "PennyMac_SaleComps_1__ViewQualityDescription", "Neutral");
            SeleniumSetMethods.SelectDropDown(ElementType.Id, "PennyMac_SaleComps_2__ViewQualityDescription", "Neutral");
            SeleniumSetMethods.SelectDropDown(ElementType.Id, "PennyMac_SaleComps_0__ViewComparison", "Good");
            SeleniumSetMethods.SelectDropDown(ElementType.Id, "PennyMac_SaleComps_1__ViewComparison", "Satisfactory");
            SeleniumSetMethods.SelectDropDown(ElementType.Id, "PennyMac_SaleComps_2__ViewComparison", "Poor");
            SeleniumSetMethods.SelectDropDown(ElementType.Id, "Subject_Condition", "Excellent");
            SeleniumSetMethods.SelectDropDown(ElementType.Id, "SaleComps_0__Condition", "Good");
            SeleniumSetMethods.SelectDropDown(ElementType.Id, "SaleComps_1__Condition", "Average");
            SeleniumSetMethods.SelectDropDown(ElementType.Id, "SaleComps_2__Condition", "Fair");
            SeleniumSetMethods.EnterText(ElementType.Id, "Subject_Rooms", "8");
            SeleniumSetMethods.EnterText(ElementType.Id, "SaleComps_0__Rooms", "9");
            SeleniumSetMethods.EnterText(ElementType.Id, "SaleComps_1__Rooms", "9");
            SeleniumSetMethods.EnterText(ElementType.Id, "SaleComps_2__Rooms", "7");
            SeleniumSetMethods.EnterText(ElementType.Id, "Subject_Beds", "5");
            SeleniumSetMethods.EnterText(ElementType.Id, "SaleComps_0__Beds", "4");
            SeleniumSetMethods.EnterText(ElementType.Id, "SaleComps_1__Beds", "5");
            SeleniumSetMethods.EnterText(ElementType.Id, "SaleComps_2__Beds", "4");
            SeleniumSetMethods.EnterText(ElementType.Id, "Subject_Baths", "3");
            SeleniumSetMethods.EnterText(ElementType.Id, "SaleComps_0__Baths", "3");
            SeleniumSetMethods.EnterText(ElementType.Id, "SaleComps_1__Baths", "2");
            SeleniumSetMethods.EnterText(ElementType.Id, "SaleComps_2__Baths", "3");
            SeleniumSetMethods.EnterText(ElementType.Id, "PennyMac_Subject_PartialBaths", "1");
            SeleniumSetMethods.EnterText(ElementType.Id, "PennyMac_SaleComps_0__PartialBaths", "0");
            SeleniumSetMethods.EnterText(ElementType.Id, "PennyMac_SaleComps_1__PartialBaths", "1");
            SeleniumSetMethods.EnterText(ElementType.Id, "PennyMac_SaleComps_2__PartialBaths", "1");
            SeleniumSetMethods.EnterText(ElementType.Id, "Subject_GrossLivingArea", "2500");
            SeleniumSetMethods.EnterText(ElementType.Id, "SaleComps_0__GrossLivingArea", "2500");
            SeleniumSetMethods.EnterText(ElementType.Id, "SaleComps_1__GrossLivingArea", "2500");
            SeleniumSetMethods.EnterText(ElementType.Id, "SaleComps_2__GrossLivingArea", "2750");
            SeleniumSetMethods.EnterText(ElementType.Id, "Subject_Bsmt", "sub base");
            SeleniumSetMethods.EnterText(ElementType.Id, "SaleComps_0__Bsmt", "s1 basement");
            SeleniumSetMethods.EnterText(ElementType.Id, "SaleComps_1__Bsmt", "s2 basement");
            SeleniumSetMethods.EnterText(ElementType.Id, "SaleComps_2__Bsmt", "s3 basement");
            SeleniumSetMethods.EnterText(ElementType.Id, "PennyMac_Subject_BsmtSqFt", "500");
            SeleniumSetMethods.EnterText(ElementType.Id, "PennyMac_Subject_BsmtPercentage", "10");
            SeleniumSetMethods.EnterText(ElementType.Id, "PennyMac_SaleComps_0__BsmtSqFt", "400");
            SeleniumSetMethods.EnterText(ElementType.Id, "PennyMac_SaleComps_0__BsmtPercentage", "0");
            SeleniumSetMethods.EnterText(ElementType.Id, "PennyMac_SaleComps_1__BsmtSqFt", "0");
            SeleniumSetMethods.EnterText(ElementType.Id, "PennyMac_SaleComps_1__BsmtPercentage", "0");
            SeleniumSetMethods.EnterText(ElementType.Id, "PennyMac_SaleComps_2__BsmtSqFt", "250");
            SeleniumSetMethods.EnterText(ElementType.Id, "PennyMac_SaleComps_2__BsmtPercentage", "15");
            SeleniumSetMethods.SelectDropDown(ElementType.Id, "Subject_GarageType", "Carport");
            SeleniumSetMethods.EnterText(ElementType.Id, "Subject_GarageCount", "2");
            SeleniumSetMethods.SelectDropDown(ElementType.Id, "SaleComps_0__GarageType", "Carport");
            SeleniumSetMethods.EnterText(ElementType.Id, "SaleComps_0__GarageCount", "2");
            SeleniumSetMethods.SelectDropDown(ElementType.Id, "SaleComps_1__GarageType", "Carport");
            SeleniumSetMethods.EnterText(ElementType.Id, "SaleComps_1__GarageCount", "2");
            SeleniumSetMethods.SelectDropDown(ElementType.Id, "SaleComps_2__GarageType", "Carport");
            SeleniumSetMethods.EnterText(ElementType.Id, "SaleComps_2__GarageCount", "2");
            SeleniumSetMethods.EnterText(ElementType.Id, "PennyMac_Subject_PoolSpa", "sub pool");
            SeleniumSetMethods.EnterText(ElementType.Id, "PennyMac_SaleComps_0__PoolSpa", "s1 pool");
            SeleniumSetMethods.EnterText(ElementType.Id, "PennyMac_SaleComps_1__PoolSpa", "s2 pool");
            SeleniumSetMethods.EnterText(ElementType.Id, "PennyMac_SaleComps_2__PoolSpa", "s3 pool");
            SeleniumSetMethods.EnterText(ElementType.Id, "Subject_Extras", "sub other");
            SeleniumSetMethods.EnterText(ElementType.Id, "SaleComps_0__Extras", "s1 other");
            SeleniumSetMethods.EnterText(ElementType.Id, "SaleComps_1__Extras", "s2 other");
            SeleniumSetMethods.EnterText(ElementType.Id, "SaleComps_2__Extras", "s3 other");
            SeleniumSetMethods.EnterText(ElementType.Id, "PennyMac_SaleComps_0__HoaFee", "180");
            SeleniumSetMethods.EnterText(ElementType.Id, "PennyMac_SaleComps_1__HoaFee", "550.85");
            SeleniumSetMethods.EnterText(ElementType.Id, "PennyMac_SaleComps_2__HoaFee", "550");
            SeleniumSetMethods.SelectDropDown(ElementType.Id, "PennyMac_SaleComps_0__Comparability", "Good");
            SeleniumSetMethods.SelectDropDown(ElementType.Id, "PennyMac_SaleComps_1__Comparability", "Satisfactory");
            SeleniumSetMethods.SelectDropDown(ElementType.Id, "PennyMac_SaleComps_2__Comparability", "Poor");
            SeleniumSetMethods.EnterText(ElementType.Id, "Repairs_0__Description", "repair");
            SeleniumSetMethods.SelectDropDown(ElementType.Id, "PennyMac_Repairs_0__RepairType", "Interior");
            SeleniumSetMethods.EnterText(ElementType.Id, "Repairs_0__Amount", "100.23");
            SeleniumSetMethods.EnterText(ElementType.Id, "PennyMac_Marketing_MarketYearBuilt", "1999");
            SeleniumSetMethods.EnterText(ElementType.Id, "PennyMac_Marketing_ClosedSalesPast6Mo", "3");
            SeleniumSetMethods.EnterText(ElementType.Id, "PennyMac_Marketing_MarketGrossLivingArea", "1800");
            SeleniumSetMethods.EnterText(ElementType.Id, "PennyMac_Marketing_AbsorptionRatePast6Mo", "20");
            SeleniumSetMethods.EnterText(ElementType.Id, "PennyMac_Marketing_MarketLotSize", "6500");
            SeleniumSetMethods.EnterText(ElementType.Id, "PennyMac_Marketing_PendingSalesCount", "3");
            SeleniumSetMethods.EnterText(ElementType.Id, "PennyMac_Marketing_MarketBeds", "4");
            SeleniumSetMethods.EnterText(ElementType.Id, "PennyMac_Marketing_SupplyMonths", "2");
            SeleniumSetMethods.EnterText(ElementType.Id, "PennyMac_Marketing_MarketBaths", "2.5");
            SeleniumSetMethods.EnterText(ElementType.Id, "PennyMac_Marketing_MarketUnits", "1");
            SeleniumSetMethods.EnterText(ElementType.Id, "PennyMac_Marketing_AvgListPricePast3Mo", "400000");
            SeleniumSetMethods.EnterText(ElementType.Id, "PennyMac_Marketing_AvgListPricePast6Mo", "375000.00");
            SeleniumSetMethods.EnterText(ElementType.Id, "PennyMac_Marketing_ComparableSalesSearchRadius", "15.3");
            SeleniumSetMethods.EnterText(ElementType.Id, "PennyMac_Marketing_AvgSalePricePast3Mo", "410000");
            SeleniumSetMethods.EnterText(ElementType.Id, "PennyMac_Marketing_AvgSalePricePast6Mo", "380000");
            SeleniumSetMethods.SelectDropDown(ElementType.Id, "PennyMac_Marketing_MarketPropertyType", "Single Family");
            SeleniumSetMethods.SelectDropDown(ElementType.Id, "PennyMac_Marketing_ComparableAge", "Last 6 Months");
            SeleniumSetMethods.EnterText(ElementType.Id, "PennyMac_Marketing_SaleListRatioPast3Mo", "25");
            SeleniumSetMethods.EnterText(ElementType.Id, "PennyMac_Marketing_SaleListRatioPast6Mo", "16");
            SeleniumSetMethods.EnterText(ElementType.Id, "ListComps_0__StreetAddress", "3");
            SeleniumSetMethods.EnterText(ElementType.Id, "ListComps_0__StreetAddress", "4");
            SeleniumSetMethods.EnterText(ElementType.Id, "ListComps_1__StreetAddress", "5");
            SeleniumSetMethods.EnterText(ElementType.Id, "ListComps_2__StreetAddress", "6");
            SeleniumSetMethods.EnterText(ElementType.Id, "ListComps_0__City", "Irvine");
            SeleniumSetMethods.EnterText(ElementType.Id, "ListComps_1__City", "Irvine");
            SeleniumSetMethods.EnterText(ElementType.Id, "ListComps_2__City", "irvine");
            SeleniumSetMethods.SelectDropDown(ElementType.Id, "ListComps_0__State", "California");
            SeleniumSetMethods.SelectDropDown(ElementType.Id, "ListComps_1__State", "California");
            SeleniumSetMethods.SelectDropDown(ElementType.Id, "ListComps_2__State", "California");
            SeleniumSetMethods.EnterText(ElementType.Id, "ListComps_0__PostalCode", "92620");
            SeleniumSetMethods.EnterText(ElementType.Id, "ListComps_1__PostalCode", "92620");
            SeleniumSetMethods.EnterText(ElementType.Id, "ListComps_2__PostalCode", "92620");
            SeleniumSetMethods.EnterText(ElementType.Id, "ListComps_0__ProximityDistance", "0.4");
            SeleniumSetMethods.EnterText(ElementType.Id, "ListComps_1__ProximityDistance", "0.6");
            SeleniumSetMethods.EnterText(ElementType.Id, "ListComps_2__ProximityDistance", "0.8");
            SeleniumSetMethods.EnterText(ElementType.Id, "ListComps_0__OriginalListPrice", "400000");
            SeleniumSetMethods.EnterText(ElementType.Id, "ListComps_1__OriginalListPrice", "410000");
            SeleniumSetMethods.EnterText(ElementType.Id, "ListComps_2__OriginalListPrice", "420000");
            SeleniumSetMethods.EnterText(ElementType.Id, "ListComps_0__ListPrice", "400000");
            SeleniumSetMethods.EnterText(ElementType.Id, "ListComps_1__ListPrice", "409000");
            SeleniumSetMethods.EnterText(ElementType.Id, "ListComps_2__ListPrice", "412999");
            SeleniumSetMethods.SelectDropDown(ElementType.Id, "ListComps_0__DataSource", "MLS");
            SeleniumSetMethods.SelectDropDown(ElementType.Id, "ListComps_1__DataSource", "MLS");
            SeleniumSetMethods.SelectDropDown(ElementType.Id, "ListComps_2__DataSource", "MLS");
            SeleniumSetMethods.EnterText(ElementType.Id, "ListComps_0__Concessions", "l1 sale conce");
            SeleniumSetMethods.EnterText(ElementType.Id, "ListComps_1__Concessions", "l2 salecon");
            SeleniumSetMethods.EnterText(ElementType.Id, "ListComps_2__Concessions", "l3salecon");
            SeleniumSetMethods.EnterText(ElementType.Id, "ListComps_0__Dom", "25");
            SeleniumSetMethods.EnterText(ElementType.Id, "ListComps_1__Dom", "26");
            SeleniumSetMethods.EnterText(ElementType.Id, "ListComps_2__Dom", "28");
            SeleniumSetMethods.EnterText(ElementType.Id, "PennyMac_ListComps_0__TotalDom", "33");
            SeleniumSetMethods.EnterText(ElementType.Id, "PennyMac_ListComps_1__TotalDom", "34");
            SeleniumSetMethods.EnterText(ElementType.Id, "PennyMac_ListComps_2__TotalDom", "35");
            SeleniumSetMethods.EnterText(ElementType.Id, "PennyMac_ListComps_0__FundingSource", "l1 fund");
            SeleniumSetMethods.EnterText(ElementType.Id, "PennyMac_ListComps_1__FundingSource", "l2fund");
            SeleniumSetMethods.EnterText(ElementType.Id, "PennyMac_ListComps_2__FundingSource", "l3 fund");
            SeleniumSetMethods.EnterText(ElementType.Id, "ListComps_0__LotSize", "6250");
            SeleniumSetMethods.EnterText(ElementType.Id, "ListComps_1__LotSize", "5500");
            SeleniumSetMethods.EnterText(ElementType.Id, "ListComps_2__LotSize", "5500");
            SeleniumSetMethods.EnterText(ElementType.Id, "PennyMac_ListComps_0__Site", "1");
            SeleniumSetMethods.EnterText(ElementType.Id, "PennyMac_ListComps_1__Site", "1");
            SeleniumSetMethods.EnterText(ElementType.Id, "PennyMac_ListComps_2__Site", "1");
            SeleniumSetMethods.SelectDropDown(ElementType.Id, "PennyMac_ListComps_0__PropertyType", "Single Family");
            SeleniumSetMethods.SelectDropDown(ElementType.Id, "PennyMac_ListComps_1__PropertyType", "Single Family");
            SeleniumSetMethods.SelectDropDown(ElementType.Id, "PennyMac_ListComps_2__PropertyType", "Single Family");
            SeleniumSetMethods.EnterText(ElementType.Id, "ListComps_0__Units", "1");
            SeleniumSetMethods.EnterText(ElementType.Id, "ListComps_1__Units", "1");
            SeleniumSetMethods.EnterText(ElementType.Id, "ListComps_2__Units", "1");
            SeleniumSetMethods.SelectDropDown(ElementType.Id, "PennyMac_ListComps_0__ConstructionType", "Brick");
            SeleniumSetMethods.SelectDropDown(ElementType.Id, "PennyMac_ListComps_1__ConstructionType", "Mix");
            SeleniumSetMethods.SelectDropDown(ElementType.Id, "PennyMac_ListComps_2__ConstructionType", "Stone");
            SeleniumSetMethods.EnterText(ElementType.Id, "PennyMac_ListComps_0__Design", "li design");
            SeleniumSetMethods.EnterText(ElementType.Id, "PennyMac_ListComps_1__Design", "l2 design");
            SeleniumSetMethods.EnterText(ElementType.Id, "PennyMac_ListComps_2__Design", "l3 design");
            SeleniumSetMethods.EnterText(ElementType.Id, "PennyMac_ListComps_0__Age", "25");
            SeleniumSetMethods.EnterText(ElementType.Id, "PennyMac_ListComps_1__Age", "15");
            SeleniumSetMethods.EnterText(ElementType.Id, "PennyMac_ListComps_2__Age", "10");
            SeleniumSetMethods.SelectDropDown(ElementType.Id, "ListComps_0__Condition", "Fair");
            SeleniumSetMethods.SelectDropDown(ElementType.Id, "ListComps_1__Condition", "Good");
            SeleniumSetMethods.SelectDropDown(ElementType.Id, "ListComps_2__Condition", "Poor");
            SeleniumSetMethods.SelectDropDown(ElementType.Id, "PennyMac_ListComps_0__ViewQualityDescription", "Adverse");
            SeleniumSetMethods.SelectDropDown(ElementType.Id, "PennyMac_ListComps_1__ViewQualityDescription", "Neutral");
            SeleniumSetMethods.SelectDropDown(ElementType.Id, "PennyMac_ListComps_2__ViewQualityDescription", "Beneficial");
            SeleniumSetMethods.SelectDropDown(ElementType.Id, "PennyMac_ListComps_0__ViewComparison", "Good");
            SeleniumSetMethods.SelectDropDown(ElementType.Id, "PennyMac_ListComps_1__ViewComparison", "Good");
            SeleniumSetMethods.SelectDropDown(ElementType.Id, "PennyMac_ListComps_2__ViewComparison", "Good");
            SeleniumSetMethods.EnterText(ElementType.Id, "ListComps_0__Rooms", "7");
            SeleniumSetMethods.EnterText(ElementType.Id, "ListComps_1__Rooms", "6");
            SeleniumSetMethods.EnterText(ElementType.Id, "ListComps_2__Rooms", "7");
            SeleniumSetMethods.EnterText(ElementType.Id, "ListComps_0__Beds", "4");
            SeleniumSetMethods.EnterText(ElementType.Id, "ListComps_1__Beds", "6");
            SeleniumSetMethods.EnterText(ElementType.Id, "ListComps_2__Beds", "5");
            SeleniumSetMethods.EnterText(ElementType.Id, "ListComps_0__Baths", "3");
            SeleniumSetMethods.EnterText(ElementType.Id, "ListComps_1__Baths", "3");
            SeleniumSetMethods.EnterText(ElementType.Id, "ListComps_2__Baths", "3");
            SeleniumSetMethods.EnterText(ElementType.Id, "PennyMac_ListComps_0__PartialBaths", "1");
            SeleniumSetMethods.EnterText(ElementType.Id, "PennyMac_ListComps_1__PartialBaths", "2");
            SeleniumSetMethods.EnterText(ElementType.Id, "PennyMac_ListComps_2__PartialBaths", "1");
            SeleniumSetMethods.EnterText(ElementType.Id, "ListComps_0__GrossLivingArea", "2750");
            SeleniumSetMethods.EnterText(ElementType.Id, "ListComps_1__GrossLivingArea", "2500");
            SeleniumSetMethods.EnterText(ElementType.Id, "ListComps_2__GrossLivingArea", "2500");
            SeleniumSetMethods.EnterText(ElementType.Id, "ListComps_0__Bsmt", "l1basement");
            SeleniumSetMethods.EnterText(ElementType.Id, "ListComps_1__Bsmt", "l2basement");
            SeleniumSetMethods.EnterText(ElementType.Id, "ListComps_2__Bsmt", "l3 basement");
            SeleniumSetMethods.EnterText(ElementType.Id, "PennyMac_ListComps_0__BsmtSqFt", "0");
            SeleniumSetMethods.EnterText(ElementType.Id, "PennyMac_ListComps_0__BsmtPercentage", "0");
            SeleniumSetMethods.EnterText(ElementType.Id, "PennyMac_ListComps_1__BsmtSqFt", "500");
            SeleniumSetMethods.EnterText(ElementType.Id, "PennyMac_ListComps_1__BsmtPercentage", "100");
            SeleniumSetMethods.EnterText(ElementType.Id, "PennyMac_ListComps_2__BsmtSqFt", "150");
            SeleniumSetMethods.EnterText(ElementType.Id, "PennyMac_ListComps_2__BsmtPercentage", "20");
            SeleniumSetMethods.SelectDropDown(ElementType.Id, "ListComps_0__GarageType", "Attached");
            SeleniumSetMethods.EnterText(ElementType.Id, "ListComps_0__GarageCount", "2");
            SeleniumSetMethods.SelectDropDown(ElementType.Id, "ListComps_1__GarageType", "Detached");
            SeleniumSetMethods.EnterText(ElementType.Id, "ListComps_1__GarageCount", "1");
            SeleniumSetMethods.SelectDropDown(ElementType.Id, "ListComps_2__GarageType", "None");
            SeleniumSetMethods.EnterText(ElementType.Id, "ListComps_2__GarageCount", "0");
            SeleniumSetMethods.EnterText(ElementType.Id, "PennyMac_ListComps_0__PoolSpa", "l1pool");
            SeleniumSetMethods.EnterText(ElementType.Id, "PennyMac_ListComps_1__PoolSpa", "l2pool");
            SeleniumSetMethods.EnterText(ElementType.Id, "PennyMac_ListComps_2__PoolSpa", "l3pool");
            SeleniumSetMethods.EnterText(ElementType.Id, "ListComps_0__Extras", "l1 other");
            SeleniumSetMethods.EnterText(ElementType.Id, "ListComps_1__Extras", "l2other");
            SeleniumSetMethods.EnterText(ElementType.Id, "ListComps_2__Extras", "l3other");
            SeleniumSetMethods.EnterText(ElementType.Id, "PennyMac_ListComps_0__HoaFee", "180");
            SeleniumSetMethods.EnterText(ElementType.Id, "PennyMac_ListComps_1__HoaFee", "250");
            SeleniumSetMethods.EnterText(ElementType.Id, "PennyMac_ListComps_2__HoaFee", "275");
            SeleniumSetMethods.SelectDropDown(ElementType.Id, "PennyMac_ListComps_0__Comparability", "Good");
            SeleniumSetMethods.SelectDropDown(ElementType.Id, "PennyMac_ListComps_1__Comparability", "Satisfactory");
            SeleniumSetMethods.SelectDropDown(ElementType.Id, "PennyMac_ListComps_2__Comparability", "Poor");
            SeleniumSetMethods.EnterText(ElementType.Id, "SaleComps_0__Comment", "sale#1 comments");
            SeleniumSetMethods.EnterText(ElementType.Id, "SaleComps_1__Comment", "sale#2 comments");
            SeleniumSetMethods.EnterText(ElementType.Id, "SaleComps_2__Comment", "sale#3 comments");
            SeleniumSetMethods.EnterText(ElementType.Id, "ListComps_0__Comment", "List1 comments");
            SeleniumSetMethods.EnterText(ElementType.Id, "ListComps_1__Comment", "list#2 comments");
            SeleniumSetMethods.EnterText(ElementType.Id, "ListComps_2__Comment", "list#3 comments");
            SeleniumSetMethods.EnterText(ElementType.Id, "QuickSaleListPrice", "411111");
            SeleniumSetMethods.EnterText(ElementType.Id, "QuickSaleValue", "422222");
            SeleniumSetMethods.EnterText(ElementType.Id, "PennyMac_AsIsDays", "30");
            SeleniumSetMethods.EnterText(ElementType.Id, "AsisListPrice", "433333");
            SeleniumSetMethods.EnterText(ElementType.Id, "AsIsValue", "444444");
            SeleniumSetMethods.EnterText(ElementType.Id, "PennyMac_RepairedDays", "45");
            SeleniumSetMethods.EnterText(ElementType.Id, "RepairedListPrice", "455555");
            SeleniumSetMethods.EnterText(ElementType.Id, "RepairedValue", "466666");
            SeleniumSetMethods.EnterText(ElementType.Id, "ProviderComments", "comments");
            SeleniumSetMethods.EnterText(ElementType.Id, "BrokenRuleComments_SaleCompLotSizeComment", "Testing 123");
            SeleniumSetMethods.EnterText(ElementType.Id, "BrokenRuleComments_SaleCompSalePriceComment", "Testing 234");

            // Add images
            SeleniumSetMethods.Clear(ElementType.Id, "190_1_fileupload");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(ElementType.Id, "190_1_fileupload", "\\\\hqfs1\\Public\\IT\\QA\\Pictures\\B1.jpg");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.Clear(ElementType.Id, "192_1_fileupload");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(ElementType.Id, "192_1_fileupload", "\\\\hqfs1\\Public\\IT\\QA\\Pictures\\B2.jpg");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.Clear(ElementType.Id, "193_1_fileupload");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(ElementType.Id, "193_1_fileupload", "\\\\hqfs1\\Public\\IT\\QA\\Pictures\\B3.jpg");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.Clear(ElementType.Id, "197_1_fileupload");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(ElementType.Id, "197_1_fileupload", "\\\\hqfs1\\Public\\IT\\QA\\Pictures\\C1.jpg");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.Clear(ElementType.Id, "198_1_fileupload");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(ElementType.Id, "198_1_fileupload", "\\\\hqfs1\\Public\\IT\\QA\\Pictures\\C2.jpg");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.Clear(ElementType.Id, "199_1_fileupload");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(ElementType.Id, "199_1_fileupload", "\\\\hqfs1\\Public\\IT\\QA\\Pictures\\C3.jpg");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.Clear(ElementType.Id, "200_1_fileupload");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(ElementType.Id, "200_1_fileupload", "\\\\hqfs1\\Public\\IT\\QA\\Pictures\\C4.jpg");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.Clear(ElementType.Id, "201_1_fileupload");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(ElementType.Id, "201_1_fileupload", "\\\\hqfs1\\Public\\IT\\QA\\Pictures\\C5.jpg");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.Clear(ElementType.Id, "202_1_fileupload");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(ElementType.Id, "202_1_fileupload", "\\\\hqfs1\\Public\\IT\\QA\\Pictures\\C6.jpg");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.Clear(ElementType.Id, "16_fileupload");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(ElementType.Id, "16_fileupload", "\\\\hqfs1\\Public\\IT\\QA\\Pictures\\AUpload.pdf");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.Clear(ElementType.Id, "27_fileupload");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumSetMethods.EnterText(ElementType.Id, "27_fileupload", "\\\\hqfs1\\Public\\IT\\QA\\Pictures\\AUpload.pdf");
            SeleniumWindowMethods.ThrottlingSleep();
            SeleniumWindowMethods.Sleep(30);
            SeleniumSetMethods.Wait(ElementType.Id, "btnBpoSave");
            SeleniumSetMethods.Click(ElementType.Id, "btnBpoSave");
            SeleniumSetMethods.AlertWait();
            SeleniumWindowMethods.Assertion(Alert.Accept);
            SeleniumWindowMethods.Sleep(5);


        }


    }


}
