using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.IE;
using OpenQA.Selenium.Firefox;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;


namespace Selenium3
{
    class Portal_Buyer
    {

        public static void Search(Driver driver)
        {

            // Navigate to web page
            SeleniumSetMethods.Navigate(Driver.driver1,  "https://qa-buyer.res.net");
            SeleniumSetMethods.Wait(driver, ElementType.Id, "propertiesTabLink");
            SeleniumSetMethods.Click(driver, ElementType.Id, "propertiesTabLink");
            SeleniumSetMethods.Wait(driver, ElementType.Id, "location");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "location", "34747");
            SeleniumSetMethods.Wait(driver, ElementType.CssSelector, "#propertiesSubmit > img");
            SeleniumSetMethods.Click(driver, ElementType.CssSelector,"#propertiesSubmit > img");
            SeleniumWindowMethods.ScreenShot(driver, "SoPurdy");
            SeleniumSetMethods.Wait(driver, ElementType.Id, "clearPropertiesSearch");
            SeleniumSetMethods.Click(driver, ElementType.Id, "clearPropertiesSearch");
            SeleniumSetMethods.Wait(driver, ElementType.Id, "logoBP");
            SeleniumSetMethods.Click(driver, ElementType.Id, "logoBP");
            SeleniumSetMethods.Wait(driver, ElementType.Id, "propertiesTabLink");
            SeleniumSetMethods.Click(driver, ElementType.Id, "propertiesTabLink");
            SeleniumSetMethods.Wait(driver, ElementType.Id, "location");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "location", "Springfield");
            SeleniumSetMethods.Wait(driver, ElementType.CssSelector, "#propertiesSubmit > img");
            SeleniumSetMethods.Click(driver, ElementType.CssSelector, "#propertiesSubmit > img");
            SeleniumSetMethods.Wait(driver, ElementType.Id, "clearPropertiesSearch");
            SeleniumSetMethods.Click(driver, ElementType.Id, "clearPropertiesSearch");
            SeleniumSetMethods.Wait(driver, ElementType.Id, "logoBP");
            SeleniumSetMethods.Click(driver, ElementType.Id, "logoBP");
            SeleniumSetMethods.Wait(driver, ElementType.Id, "propertiesTabLink");
            SeleniumSetMethods.Click(driver, ElementType.Id, "propertiesTabLink");
            SeleniumSetMethods.Wait(driver, ElementType.Id, "location");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "location", "34747, Reunion, FL");
            SeleniumSetMethods.Wait(driver, ElementType.CssSelector, "#propertiesSubmit > img");
            SeleniumSetMethods.Click(driver, ElementType.CssSelector, "#propertiesSubmit > img");
            SeleniumSetMethods.Wait(driver, ElementType.Id, "clearPropertiesSearch");
            SeleniumSetMethods.Click(driver, ElementType.Id, "clearPropertiesSearch");
            SeleniumSetMethods.Wait(driver, ElementType.Id, "logoBP");
            SeleniumSetMethods.Click(driver, ElementType.Id, "logoBP");
            SeleniumSetMethods.Wait(driver, ElementType.Id, "propertiesTabLink");
            SeleniumSetMethods.Click(driver, ElementType.Id, "propertiesTabLink");
            SeleniumSetMethods.Wait(driver, ElementType.Id, "location");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "location", "30004");
            SeleniumSetMethods.Wait(driver, ElementType.CssSelector, "#propertiesSubmit > img");
            SeleniumSetMethods.Click(driver, ElementType.CssSelector, "#propertiesSubmit > img");
            SeleniumSetMethods.Wait(driver, ElementType.Id, "withinRadius");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "withinRadius", "50 Miles");
            SeleniumSetMethods.Wait(driver, ElementType.CssSelector, "#propertySearchOptionContainer > form:nth-child(1) > div:nth-child(1) > div:nth-child(1) > div:nth-child(1) > div:nth-child(1) > div:nth-child(9) > div:nth-child(2) > a:nth-child(1)");
            SeleniumSetMethods.Click(driver, ElementType.CssSelector, "#propertySearchOptionContainer > form:nth-child(1) > div:nth-child(1) > div:nth-child(1) > div:nth-child(1) > div:nth-child(1) > div:nth-child(9) > div:nth-child(2) > a:nth-child(1)");
            SeleniumSetMethods.Wait(driver, ElementType.Id, "minPrice");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "minPrice", "$100K");
            SeleniumSetMethods.Wait(driver, ElementType.Id, "maxPrice");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "maxPrice", "$250K");
            SeleniumSetMethods.Wait(driver, ElementType.CssSelector, "#propertySearchOptionContainer > form:nth-child(1) > div:nth-child(1) > div:nth-child(1) > div:nth-child(1) > div:nth-child(1) > div:nth-child(9) > div:nth-child(2) > a:nth-child(1)");
            SeleniumSetMethods.Click(driver, ElementType.CssSelector, "#propertySearchOptionContainer > form:nth-child(1) > div:nth-child(1) > div:nth-child(1) > div:nth-child(1) > div:nth-child(1) > div:nth-child(9) > div:nth-child(2) > a:nth-child(1)");
            SeleniumSetMethods.Wait(driver, ElementType.Id, "minBeds");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "minBeds", "3+");
            SeleniumSetMethods.Wait(driver, ElementType.CssSelector, "#propertySearchOptionContainer > form:nth-child(1) > div:nth-child(1) > div:nth-child(1) > div:nth-child(1) > div:nth-child(1) > div:nth-child(9) > div:nth-child(2) > a:nth-child(1)");
            SeleniumSetMethods.Click(driver, ElementType.CssSelector, "#propertySearchOptionContainer > form:nth-child(1) > div:nth-child(1) > div:nth-child(1) > div:nth-child(1) > div:nth-child(1) > div:nth-child(9) > div:nth-child(2) > a:nth-child(1)");
            SeleniumSetMethods.Wait(driver, ElementType.Id, "minBaths");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "minBaths", "3+");
            SeleniumSetMethods.Wait(driver, ElementType.CssSelector, "#propertySearchOptionContainer > form:nth-child(1) > div:nth-child(1) > div:nth-child(1) > div:nth-child(1) > div:nth-child(1) > div:nth-child(9) > div:nth-child(2) > a:nth-child(1)");
            SeleniumSetMethods.Click(driver, ElementType.CssSelector, "#propertySearchOptionContainer > form:nth-child(1) > div:nth-child(1) > div:nth-child(1) > div:nth-child(1) > div:nth-child(1) > div:nth-child(9) > div:nth-child(2) > a:nth-child(1)");
            SeleniumSetMethods.Wait(driver, ElementType.Id, "clearPropertiesSearch");
            SeleniumSetMethods.Click(driver, ElementType.Id, "clearPropertiesSearch");
            SeleniumSetMethods.Wait(driver, ElementType.Id, "MLSNumber");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "MLSNumber", "LO7793433");
            SeleniumSetMethods.Wait(driver, ElementType.CssSelector, "#propertySearchOptionContainer > form:nth-child(1) > div:nth-child(1) > div:nth-child(1) > div:nth-child(1) > div:nth-child(1) > div:nth-child(9) > div:nth-child(2) > a:nth-child(1)");
            SeleniumSetMethods.Click(driver, ElementType.CssSelector, "#propertySearchOptionContainer > form:nth-child(1) > div:nth-child(1) > div:nth-child(1) > div:nth-child(1) > div:nth-child(1) > div:nth-child(9) > div:nth-child(2) > a:nth-child(1)");
            SeleniumSetMethods.Wait(driver, ElementType.Id, "clearPropertiesSearch");
            SeleniumSetMethods.Click(driver, ElementType.Id, "clearPropertiesSearch");
            SeleniumSetMethods.Wait(driver, ElementType.Id, "location");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "location", "90210");
            SeleniumSetMethods.Wait(driver, ElementType.Id, "withinRadius");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "withinRadius", "50 Miles");
            SeleniumSetMethods.Wait(driver, ElementType.Id, "propertyTypeLink");
            SeleniumSetMethods.Click(driver, ElementType.Id, "propertyTypeLink");
            SeleniumSetMethods.Wait(driver, ElementType.Id, "propertyTypeNone");
            SeleniumSetMethods.Click(driver, ElementType.Id, "propertyTypeNone");
            SeleniumSetMethods.Click(driver, ElementType.Id, "propertytypeChk1");
            SeleniumSetMethods.Wait(driver, ElementType.CssSelector, "#propertySearchOptionContainer > form:nth-child(1) > div:nth-child(1) > div:nth-child(1) > div:nth-child(1) > div:nth-child(1) > div:nth-child(9) > div:nth-child(2) > a:nth-child(1)");
            SeleniumSetMethods.Click(driver, ElementType.CssSelector, "#propertySearchOptionContainer > form:nth-child(1) > div:nth-child(1) > div:nth-child(1) > div:nth-child(1) > div:nth-child(1) > div:nth-child(9) > div:nth-child(2) > a:nth-child(1)");
            SeleniumSetMethods.Wait(driver, ElementType.Id, "propertyTypeLink");
            SeleniumSetMethods.Click(driver, ElementType.Id, "propertyTypeLink");
            SeleniumSetMethods.Wait(driver, ElementType.Id, "propertytypeChk1");
            SeleniumSetMethods.Click(driver, ElementType.Id, "propertytypeChk1");
            SeleniumSetMethods.Click(driver, ElementType.Id, "propertytypeChk2");
            SeleniumSetMethods.Wait(driver, ElementType.CssSelector, "#propertySearchOptionContainer > form:nth-child(1) > div:nth-child(1) > div:nth-child(1) > div:nth-child(1) > div:nth-child(1) > div:nth-child(9) > div:nth-child(2) > a:nth-child(1)");
            SeleniumSetMethods.Click(driver, ElementType.CssSelector, "#propertySearchOptionContainer > form:nth-child(1) > div:nth-child(1) > div:nth-child(1) > div:nth-child(1) > div:nth-child(1) > div:nth-child(9) > div:nth-child(2) > a:nth-child(1)");
            SeleniumSetMethods.Wait(driver, ElementType.Id, "propertyTypeLink");
            SeleniumSetMethods.Click(driver, ElementType.Id, "propertyTypeLink");
            SeleniumSetMethods.Wait(driver, ElementType.Id, "propertytypeChk2");
            SeleniumSetMethods.Click(driver, ElementType.Id, "propertytypeChk2");
            SeleniumSetMethods.Click(driver, ElementType.Id, "propertytypeChk7");
            SeleniumSetMethods.Wait(driver, ElementType.CssSelector, "#propertySearchOptionContainer > form:nth-child(1) > div:nth-child(1) > div:nth-child(1) > div:nth-child(1) > div:nth-child(1) > div:nth-child(9) > div:nth-child(2) > a:nth-child(1)");
            SeleniumSetMethods.Click(driver, ElementType.CssSelector, "#propertySearchOptionContainer > form:nth-child(1) > div:nth-child(1) > div:nth-child(1) > div:nth-child(1) > div:nth-child(1) > div:nth-child(9) > div:nth-child(2) > a:nth-child(1)");
            SeleniumSetMethods.Wait(driver, ElementType.Id, "propertyTypeLink");
            SeleniumSetMethods.Click(driver, ElementType.Id, "propertyTypeLink");
            SeleniumSetMethods.Wait(driver, ElementType.Id, "propertytypeChk7");
            SeleniumSetMethods.Click(driver, ElementType.Id, "propertytypeChk7");
            SeleniumSetMethods.Click(driver, ElementType.Id, "propertytypeChk9");
            SeleniumSetMethods.Wait(driver, ElementType.CssSelector, "#propertySearchOptionContainer > form:nth-child(1) > div:nth-child(1) > div:nth-child(1) > div:nth-child(1) > div:nth-child(1) > div:nth-child(9) > div:nth-child(2) > a:nth-child(1)");
            SeleniumSetMethods.Click(driver, ElementType.CssSelector, "#propertySearchOptionContainer > form:nth-child(1) > div:nth-child(1) > div:nth-child(1) > div:nth-child(1) > div:nth-child(1) > div:nth-child(9) > div:nth-child(2) > a:nth-child(1)");
            SeleniumSetMethods.Wait(driver, ElementType.Id, "propertyTypeLink");
            SeleniumSetMethods.Click(driver, ElementType.Id, "propertyTypeLink");
            SeleniumSetMethods.Wait(driver, ElementType.Id, "propertytypeChk9");
            SeleniumSetMethods.Click(driver, ElementType.Id, "propertytypeChk9");
            SeleniumSetMethods.Click(driver, ElementType.Id, "propertytypeChk13");
            SeleniumSetMethods.Wait(driver, ElementType.CssSelector, "#propertySearchOptionContainer > form:nth-child(1) > div:nth-child(1) > div:nth-child(1) > div:nth-child(1) > div:nth-child(1) > div:nth-child(9) > div:nth-child(2) > a:nth-child(1)");
            SeleniumSetMethods.Click(driver, ElementType.CssSelector, "#propertySearchOptionContainer > form:nth-child(1) > div:nth-child(1) > div:nth-child(1) > div:nth-child(1) > div:nth-child(1) > div:nth-child(9) > div:nth-child(2) > a:nth-child(1)");
            SeleniumSetMethods.Wait(driver, ElementType.Id, "propertyTypeLink");
            SeleniumSetMethods.Click(driver, ElementType.Id, "propertyTypeLink");
            SeleniumSetMethods.Wait(driver, ElementType.Id, "propertytypeChk13");
            SeleniumSetMethods.Click(driver, ElementType.Id, "propertytypeChk13");
            SeleniumSetMethods.Click(driver, ElementType.Id, "propertytypeChk5");
            SeleniumSetMethods.Wait(driver, ElementType.CssSelector, "#propertySearchOptionContainer > form:nth-child(1) > div:nth-child(1) > div:nth-child(1) > div:nth-child(1) > div:nth-child(1) > div:nth-child(9) > div:nth-child(2) > a:nth-child(1)");
            SeleniumSetMethods.Click(driver, ElementType.CssSelector, "#propertySearchOptionContainer > form:nth-child(1) > div:nth-child(1) > div:nth-child(1) > div:nth-child(1) > div:nth-child(1) > div:nth-child(9) > div:nth-child(2) > a:nth-child(1)");
            SeleniumSetMethods.Wait(driver, ElementType.Id, "propertyTypeLink");
            SeleniumSetMethods.Click(driver, ElementType.Id, "propertyTypeLink");
            SeleniumSetMethods.Wait(driver, ElementType.Id, "propertytypeChk5");
            SeleniumSetMethods.Click(driver, ElementType.Id, "propertytypeChk5");
            SeleniumSetMethods.Click(driver, ElementType.Id, "propertytypeChk10");
            SeleniumSetMethods.Wait(driver, ElementType.CssSelector, "#propertySearchOptionContainer > form:nth-child(1) > div:nth-child(1) > div:nth-child(1) > div:nth-child(1) > div:nth-child(1) > div:nth-child(9) > div:nth-child(2) > a:nth-child(1)");
            SeleniumSetMethods.Click(driver, ElementType.CssSelector, "#propertySearchOptionContainer > form:nth-child(1) > div:nth-child(1) > div:nth-child(1) > div:nth-child(1) > div:nth-child(1) > div:nth-child(9) > div:nth-child(2) > a:nth-child(1)");
            SeleniumSetMethods.Wait(driver, ElementType.Id, "propertyTypeAll");
            SeleniumSetMethods.Click(driver, ElementType.Id, "propertyTypeAll");
            SeleniumSetMethods.Wait(driver, ElementType.Id, "propertyListingLink");
            SeleniumSetMethods.Click(driver, ElementType.Id, "propertyListingLink");
            SeleniumSetMethods.Wait(driver, ElementType.Id, "propertyListingsNone");
            SeleniumSetMethods.Click(driver, ElementType.Id, "propertyListingsNone");
            SeleniumSetMethods.Click(driver, ElementType.Id, "listingTypeChk1");
            SeleniumSetMethods.Wait(driver, ElementType.CssSelector, "#propertySearchOptionContainer > form:nth-child(1) > div:nth-child(1) > div:nth-child(1) > div:nth-child(1) > div:nth-child(1) > div:nth-child(9) > div:nth-child(2) > a:nth-child(1)");
            SeleniumSetMethods.Click(driver, ElementType.CssSelector, "#propertySearchOptionContainer > form:nth-child(1) > div:nth-child(1) > div:nth-child(1) > div:nth-child(1) > div:nth-child(1) > div:nth-child(9) > div:nth-child(2) > a:nth-child(1)");
            SeleniumSetMethods.Wait(driver, ElementType.Id, "propertyListingLink");
            SeleniumSetMethods.Click(driver, ElementType.Id, "propertyListingLink");
            SeleniumSetMethods.Wait(driver, ElementType.Id, "listingTypeChk1");
            SeleniumSetMethods.Click(driver, ElementType.Id, "listingTypeChk1");
            SeleniumSetMethods.Click(driver, ElementType.Id, "listingTypeChk3");
            SeleniumSetMethods.Wait(driver, ElementType.CssSelector, "#propertySearchOptionContainer > form:nth-child(1) > div:nth-child(1) > div:nth-child(1) > div:nth-child(1) > div:nth-child(1) > div:nth-child(9) > div:nth-child(2) > a:nth-child(1)");
            SeleniumSetMethods.Click(driver, ElementType.CssSelector, "#propertySearchOptionContainer > form:nth-child(1) > div:nth-child(1) > div:nth-child(1) > div:nth-child(1) > div:nth-child(1) > div:nth-child(9) > div:nth-child(2) > a:nth-child(1)");
            SeleniumSetMethods.Wait(driver, ElementType.Id, "propertyListingLink");
            SeleniumSetMethods.Click(driver, ElementType.Id, "propertyListingLink");
            SeleniumSetMethods.Wait(driver, ElementType.Id, "listingTypeChk3");
            SeleniumSetMethods.Click(driver, ElementType.Id, "listingTypeChk3");
            SeleniumSetMethods.Click(driver, ElementType.Id, "listingTypeChk2");
            SeleniumSetMethods.Wait(driver, ElementType.CssSelector, "#propertySearchOptionContainer > form:nth-child(1) > div:nth-child(1) > div:nth-child(1) > div:nth-child(1) > div:nth-child(1) > div:nth-child(9) > div:nth-child(2) > a:nth-child(1)");
            SeleniumSetMethods.Click(driver, ElementType.CssSelector, "#propertySearchOptionContainer > form:nth-child(1) > div:nth-child(1) > div:nth-child(1) > div:nth-child(1) > div:nth-child(1) > div:nth-child(9) > div:nth-child(2) > a:nth-child(1)");
            SeleniumSetMethods.Wait(driver, ElementType.Id, "propertyListingsAll");
            SeleniumSetMethods.Click(driver, ElementType.Id, "propertyListingsAll");
            SeleniumSetMethods.Wait(driver, ElementType.Id, "propertyStatusLnk");
            SeleniumSetMethods.Click(driver, ElementType.Id, "propertyStatusLnk");
            SeleniumSetMethods.Wait(driver, ElementType.Id, "propertyStatusNone");
            SeleniumSetMethods.Click(driver, ElementType.Id, "propertyStatusNone");
            SeleniumSetMethods.Wait(driver, ElementType.Id, "SearchPrelisted");
            SeleniumSetMethods.Click(driver, ElementType.Id, "SearchPrelisted");
            SeleniumSetMethods.Wait(driver, ElementType.CssSelector, "#propertySearchOptionContainer > form:nth-child(1) > div:nth-child(1) > div:nth-child(1) > div:nth-child(1) > div:nth-child(1) > div:nth-child(9) > div:nth-child(2) > a:nth-child(1)");
            SeleniumSetMethods.Click(driver, ElementType.CssSelector, "#propertySearchOptionContainer > form:nth-child(1) > div:nth-child(1) > div:nth-child(1) > div:nth-child(1) > div:nth-child(1) > div:nth-child(9) > div:nth-child(2) > a:nth-child(1)");
            SeleniumSetMethods.Wait(driver, ElementType.Id, "propertyStatusLnk");
            SeleniumSetMethods.Click(driver, ElementType.Id, "propertyStatusLnk");
            SeleniumSetMethods.Wait(driver, ElementType.Id, "SearchPrelisted");
            SeleniumSetMethods.Click(driver, ElementType.Id, "SearchPrelisted");
            SeleniumSetMethods.Click(driver, ElementType.Id, "propertyStatusChk2");
            SeleniumSetMethods.Wait(driver, ElementType.CssSelector, "#propertySearchOptionContainer > form:nth-child(1) > div:nth-child(1) > div:nth-child(1) > div:nth-child(1) > div:nth-child(1) > div:nth-child(9) > div:nth-child(2) > a:nth-child(1)");
            SeleniumSetMethods.Click(driver, ElementType.CssSelector, "#propertySearchOptionContainer > form:nth-child(1) > div:nth-child(1) > div:nth-child(1) > div:nth-child(1) > div:nth-child(1) > div:nth-child(9) > div:nth-child(2) > a:nth-child(1)");
            SeleniumSetMethods.Wait(driver, ElementType.Id, "propertyStatusLnk");
            SeleniumSetMethods.Click(driver, ElementType.Id, "propertyStatusLnk");
            SeleniumSetMethods.Wait(driver, ElementType.Id, "propertyStatusChk2");
            SeleniumSetMethods.Click(driver, ElementType.Id, "propertyStatusChk2");
            SeleniumSetMethods.Click(driver, ElementType.Id, "propertyStatusChk3");
            SeleniumSetMethods.Wait(driver, ElementType.CssSelector, "#propertySearchOptionContainer > form:nth-child(1) > div:nth-child(1) > div:nth-child(1) > div:nth-child(1) > div:nth-child(1) > div:nth-child(9) > div:nth-child(2) > a:nth-child(1)");
            SeleniumSetMethods.Click(driver, ElementType.CssSelector, "#propertySearchOptionContainer > form:nth-child(1) > div:nth-child(1) > div:nth-child(1) > div:nth-child(1) > div:nth-child(1) > div:nth-child(9) > div:nth-child(2) > a:nth-child(1)");
            SeleniumSetMethods.Wait(driver, ElementType.Id, "propertyStatusLnk");
            SeleniumSetMethods.Click(driver, ElementType.Id, "propertyStatusLnk");
            SeleniumSetMethods.Wait(driver, ElementType.Id, "propertyStatusChk3");
            SeleniumSetMethods.Click(driver, ElementType.Id, "propertyStatusChk3");
            SeleniumSetMethods.Click(driver, ElementType.Id, "propertyStatusChk6");
            SeleniumSetMethods.Wait(driver, ElementType.CssSelector, "#propertySearchOptionContainer > form:nth-child(1) > div:nth-child(1) > div:nth-child(1) > div:nth-child(1) > div:nth-child(1) > div:nth-child(9) > div:nth-child(2) > a:nth-child(1)");
            SeleniumSetMethods.Click(driver, ElementType.CssSelector, "#propertySearchOptionContainer > form:nth-child(1) > div:nth-child(1) > div:nth-child(1) > div:nth-child(1) > div:nth-child(1) > div:nth-child(9) > div:nth-child(2) > a:nth-child(1)");
            SeleniumSetMethods.Wait(driver, ElementType.Id, "propertyStatusAll");
            SeleniumSetMethods.Click(driver, ElementType.Id, "propertyStatusAll");
            SeleniumSetMethods.Wait(driver, ElementType.Id, "additionalInfoLnk");
            SeleniumSetMethods.Click(driver, ElementType.Id, "additionalInfoLnk");
            SeleniumSetMethods.Wait(driver, ElementType.Id, "minSqFt");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "minSqFt", "1000+");
            SeleniumSetMethods.Wait(driver, ElementType.CssSelector, "#propertySearchOptionContainer > form:nth-child(1) > div:nth-child(1) > div:nth-child(1) > div:nth-child(1) > div:nth-child(1) > div:nth-child(9) > div:nth-child(2) > a:nth-child(1)");
            SeleniumSetMethods.Click(driver, ElementType.CssSelector, "#propertySearchOptionContainer > form:nth-child(1) > div:nth-child(1) > div:nth-child(1) > div:nth-child(1) > div:nth-child(1) > div:nth-child(9) > div:nth-child(2) > a:nth-child(1)");
            SeleniumSetMethods.Wait(driver, ElementType.Id, "additionalInfoLnk");
            SeleniumSetMethods.Click(driver, ElementType.Id, "additionalInfoLnk");
            SeleniumSetMethods.Wait(driver, ElementType.Id, "minLotSize");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "minLotSize", "4000+");
            SeleniumSetMethods.Wait(driver, ElementType.CssSelector, "#propertySearchOptionContainer > form:nth-child(1) > div:nth-child(1) > div:nth-child(1) > div:nth-child(1) > div:nth-child(1) > div:nth-child(9) > div:nth-child(2) > a:nth-child(1)");
            SeleniumSetMethods.Click(driver, ElementType.CssSelector, "#propertySearchOptionContainer > form:nth-child(1) > div:nth-child(1) > div:nth-child(1) > div:nth-child(1) > div:nth-child(1) > div:nth-child(9) > div:nth-child(2) > a:nth-child(1)");
            SeleniumSetMethods.Wait(driver, ElementType.Id, "additionalInfoLnk");
            SeleniumSetMethods.Click(driver, ElementType.Id, "additionalInfoLnk");
            SeleniumSetMethods.Wait(driver, ElementType.Id, "yearBuilt");
            SeleniumSetMethods.EnterText(driver, ElementType.Id, "yearBuilt", "1960");
            SeleniumSetMethods.Wait(driver, ElementType.CssSelector, "#propertySearchOptionContainer > form:nth-child(1) > div:nth-child(1) > div:nth-child(1) > div:nth-child(1) > div:nth-child(1) > div:nth-child(9) > div:nth-child(2) > a:nth-child(1)");
            SeleniumSetMethods.Click(driver, ElementType.CssSelector, "#propertySearchOptionContainer > form:nth-child(1) > div:nth-child(1) > div:nth-child(1) > div:nth-child(1) > div:nth-child(1) > div:nth-child(9) > div:nth-child(2) > a:nth-child(1)");
            
        }

    }

}
